package generator

import (
	"fmt"
	"strings"

	"path"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"

	sdm "github.com/kapow-tech/sdm/sdmprotos" // Import the generated code for annotations
)

// GenerateFile generates the SDM artifacts for a single proto file.
// After iterating all files, call GenerateHelpers(gen, anyFile) exactly once.
func GenerateFile(gen *protogen.Plugin, file *protogen.File) {
	if len(file.Messages) == 0 {
		return
	}

	// generate Go models
	generateModels(gen, file)
	// generate SQL schema
	generateSQL(gen, file)
	// generate GORM repository
	generateRepo(gen, file)
}

// GenerateHelpers emits sdm_helpers.go exactly once for the whole package.
// Must be called from main.go AFTER the GenerateFile loop — not inside it.
// GenerateFile runs once per proto file; calling this inside it would produce
// one helpers file per message type, causing "pgArrayLiteral redeclared" errors.
func GenerateHelpers(gen *protogen.Plugin, file *protogen.File) {
	// Derive the package directory from the file prefix, e.g.:
	//   file.GeneratedFilenamePrefix = "ttf/users"  →  dir = "ttf"
	// Using path.Dir (not filepath) because protogen paths are always forward-slash.
	dir := path.Dir(file.GeneratedFilenamePrefix)
	filename := path.Join(dir, "sdm_helpers.go")
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	needProtojson := packageHasMessageJsonField(gen)

	g.P("// Code generated by sdm. DO NOT EDIT.")
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	g.P("import (")
	g.P(`	"strings"`)
	if needProtojson {
		g.P(`	"context"`)
		g.P(`	"fmt"`)
		g.P(`	"reflect"`)
		g.P(`	"google.golang.org/protobuf/encoding/protojson"`)
		g.P(`	"google.golang.org/protobuf/proto"`)
		g.P(`	"gorm.io/gorm/schema"`)
	}
	g.P(")")
	g.P()
	g.P("// pgArrayLiteral serialises a string slice as a PostgreSQL array literal.")
	g.P("// e.g. []string{\"A\", \"B\"} → \"{A,B}\"")
	g.P("// fmt.Sprintf(\"%v\", slice) produces \"[A B]\" which is NOT valid PostgreSQL —")
	g.P("// this helper produces \"{A,B}\" which survives a ::text[] cast.")
	g.P("func pgArrayLiteral(vals []string) string {")
	g.P(`  return "{" + strings.Join(vals, ",") + "}"`)
	g.P("}")
	if needProtojson {
		g.P()
		emitProtojsonSerializer(g)
	}
}

// emitProtojsonSerializer writes a GORM serializer that marshals/unmarshals
// proto messages using protojson, registered as "protojson" in init(). View
// and PII struct fields use it via the tag `serializer:protojson`, so reads
// surface a typed *Message rather than raw JSON bytes and writes accept the
// same typed value (GORM calls Value() to produce JSONB bytes).
func emitProtojsonSerializer(g *protogen.GeneratedFile) {
	g.P("type protojsonSerializer struct{}")
	g.P()
	g.P("func init() {")
	g.P(`	schema.RegisterSerializer("protojson", protojsonSerializer{})`)
	g.P("}")
	g.P()
	g.P("func (protojsonSerializer) Scan(ctx context.Context, field *schema.Field, dst reflect.Value, dbValue interface{}) error {")
	g.P("	if dbValue == nil { return nil }")
	g.P("	var data []byte")
	g.P("	switch v := dbValue.(type) {")
	g.P("	case []byte: data = v")
	g.P("	case string:  data = []byte(v)")
	g.P("	default: return fmt.Errorf(\"protojson: unsupported source type %T for field %s\", dbValue, field.Name)")
	g.P("	}")
	g.P("	if len(data) == 0 { return nil }")
	g.P("	ft := field.FieldType")
	g.P("	if ft.Kind() != reflect.Ptr {")
	g.P("		return fmt.Errorf(\"protojson: field %s must be a pointer to a proto.Message\", field.Name)")
	g.P("	}")
	g.P("	ptr := reflect.New(ft.Elem())")
	g.P("	msg, ok := ptr.Interface().(proto.Message)")
	g.P("	if !ok {")
	g.P("		return fmt.Errorf(\"protojson: field %s does not implement proto.Message\", field.Name)")
	g.P("	}")
	g.P("	if err := protojson.Unmarshal(data, msg); err != nil { return err }")
	g.P("	field.ReflectValueOf(ctx, dst).Set(ptr)")
	g.P("	return nil")
	g.P("}")
	g.P()
	g.P("func (protojsonSerializer) Value(ctx context.Context, field *schema.Field, dst reflect.Value, fieldValue interface{}) (interface{}, error) {")
	g.P("	if fieldValue == nil { return nil, nil }")
	g.P("	v := reflect.ValueOf(fieldValue)")
	g.P("	if v.Kind() == reflect.Ptr && v.IsNil() { return nil, nil }")
	g.P("	msg, ok := fieldValue.(proto.Message)")
	g.P("	if !ok {")
	g.P("		return nil, fmt.Errorf(\"protojson: field %s does not implement proto.Message (got %T)\", field.Name, fieldValue)")
	g.P("	}")
	g.P("	return protojson.Marshal(msg)")
	g.P("}")
}

// packageHasMessageJsonField scans all files this plugin is generating to
// decide whether sdm_helpers.go should emit the protojson serializer + init.
func packageHasMessageJsonField(gen *protogen.Plugin) bool {
	for _, f := range gen.Files {
		if !f.Generate {
			continue
		}
		if fileHasMessageJsonField(f) {
			return true
		}
	}
	return false
}

func generateModels(gen *protogen.Plugin, file *protogen.File) {
	filename := file.GeneratedFilenamePrefix + "_sdm_model.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	// Detect whether any recorded message has a repeated (list) field.
	// If so, the View struct needs pq.StringArray — import github.com/lib/pq.
	needPq := false
	for _, msg := range file.Messages {
		if !isSdmRecord(msg) {
			continue
		}
		for _, field := range msg.Fields {
			if field.Desc.IsList() {
				needPq = true
				break
			}
		}
	}

	g.P("// Code generated by sdm. DO NOT EDIT.")
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	g.P("import (")
	g.P(`	"time"`)
	if fileHasStringJsonField(file) {
		g.P(`	"gorm.io/datatypes"`)
	}
	if needPq {
		g.P(`	"github.com/lib/pq"`)
	}
	g.P(`	"gorm.io/gorm"`)
	g.P(")")
	g.P()

	for _, msg := range file.Messages {
		if !isSdmRecord(msg) {
			continue // value-type message (e.g. Money) — used inline as JSON, no tables
		}
		generateMessageModels(g, msg)
	}
}

func generateMessageModels(g *protogen.GeneratedFile, msg *protogen.Message) {
	modelName := msg.GoIdent.GoName

	// PII Table Structure
	g.P("type ", modelName, "Pii struct {")
	for _, field := range msg.Fields {
		opts := getFieldOptions(field)
		if opts.PrimaryKey || opts.Pii || opts.QueryIndex || opts.References != "" {
			goType := goTypeForField(field)
			tag := "column:" + string(field.Desc.Name())
			if opts.PrimaryKey {
				tag += ";primaryKey"
			}
			if opts.Unique {
				tag += ";uniqueIndex"
			}
			if opts.AutoIncrement {
				tag += ";autoIncrement"
			}
			if isJsonStored(field, opts) {
				tag += ";type:jsonb"
			}
			if needsProtojsonMarshal(field) {
				tag += ";serializer:protojson"
			}
			g.P(field.GoName, " ", goType, " `gorm:\"", tag, "\"`")
		}
	}
	// Default audit fields on every PII model. GORM populates CreatedAt and
	// UpdatedAt on INSERT/UPDATE by name convention; IsDeleted is a soft-delete
	// flag that the generated read methods filter on.
	g.P("CreatedAt time.Time `gorm:\"column:created_at;autoCreateTime\"`")
	g.P("UpdatedAt time.Time `gorm:\"column:updated_at;autoUpdateTime\"`")
	g.P("IsDeleted bool `gorm:\"column:is_deleted;default:false\"`")
	g.P("}")
	g.P()

	// Chain Table Structure
	g.P("type ", modelName, "Chain struct {")
	g.P("Key string `gorm:\"primaryKey;column:key\"`")
	g.P("FieldName string `gorm:\"primaryKey;column:field_name\"`")
	g.P("Version int64 `gorm:\"primaryKey;column:version;autoIncrement\"`")
	g.P("TxHash string `gorm:\"column:tx_hash\"`")
	g.P("FieldValue string `gorm:\"column:field_value\"`")
	g.P("CreatedAt time.Time `gorm:\"column:created_at\"`")
	g.P("}")
	g.P()

	// View Structure (Combined)
	// FIX: repeated (list) fields use pq.StringArray instead of []string.
	// pq.StringArray implements driver.Valuer and sql.Scanner so GORM can
	// scan a text[] column directly. Plain []string has no such implementation
	// and causes "unsupported data type: &[]" at startup.
	g.P("type ", modelName, "View struct {")
	for _, field := range msg.Fields {
		var goType, viewTag string
		if field.Desc.IsList() {
			goType = "pq.StringArray"
			viewTag = fmt.Sprintf("column:%s;type:text[]", field.Desc.Name())
		} else {
			goType = goTypeForField(field)
			viewTag = "column:" + string(field.Desc.Name())
			if needsProtojsonMarshal(field) {
				// View column comes from a ::jsonb cast over the chain's TEXT field_value
				// (or directly from the PII JSONB column). The serializer decodes those
				// bytes into a typed *Message on read.
				viewTag += ";serializer:protojson"
			}
		}
		g.P(field.GoName, " ", goType, " `gorm:\"", viewTag, "\"`")

		opts := getFieldOptions(field)
		if opts.Hashed {
			g.P("Hashed", field.GoName, " string `gorm:\"column:hashed_", field.Desc.Name(), "\"`")
		}
	}
	// Audit columns surfaced from the PII table on the view.
	g.P("CreatedAt time.Time `gorm:\"column:created_at\"`")
	g.P("UpdatedAt time.Time `gorm:\"column:updated_at\"`")
	g.P("IsDeleted bool `gorm:\"column:is_deleted\"`")
	g.P("TxHash string `gorm:\"column:tx_hash\"`")
	g.P("}")
	g.P()

	// TableName overrides
	g.P("func (", modelName, "Pii) TableName() string { return \"pii_", strings.ToLower(modelName), "s\" }")
	g.P("func (", modelName, "Chain) TableName() string { return \"chain_", strings.ToLower(modelName), "s\" }")
	g.P("func (", modelName, "View) TableName() string { return \"", strings.ToLower(modelName), "s\" }")
	g.P()

	// EnsureUnique method
	g.P("func (c *", modelName, "Chain) EnsureUnique(tx *gorm.DB) bool {")
	g.P("  var count int64")
	g.P("  err := tx.Model(&", modelName, "Chain{}).Where(\"field_name = ? AND field_value = ?\", c.FieldName, c.FieldValue).Count(&count).Error")
	g.P("  if err != nil {")
	g.P("    return false")
	g.P("  }")
	g.P("  return count == 0")
	g.P("}")
	g.P()
}

// chainKeyCols returns the columns used as the chain key for a message.
func chainKeyCols(msg *protogen.Message) []string {
	var cols []string
	for _, field := range msg.Fields {
		if getFieldOptions(field).ChainIdentifierKey {
			cols = append(cols, string(field.Desc.Name()))
		}
	}
	if len(cols) > 0 {
		return cols
	}
	for _, field := range msg.Fields {
		if getFieldOptions(field).PrimaryKey {
			cols = append(cols, string(field.Desc.Name()))
		}
	}
	return cols
}

// chainKeyGoFields returns the protogen fields used as the chain key.
func chainKeyGoFields(msg *protogen.Message) []*protogen.Field {
	var fields []*protogen.Field
	for _, field := range msg.Fields {
		if getFieldOptions(field).ChainIdentifierKey {
			fields = append(fields, field)
		}
	}
	if len(fields) > 0 {
		return fields
	}
	for _, field := range msg.Fields {
		if getFieldOptions(field).PrimaryKey {
			fields = append(fields, field)
		}
	}
	return fields
}

// sqlCompositeKeyExpr builds the SQL expression that reproduces the compositeKey.
func sqlCompositeKeyExpr(keyCols []string) string {
	if len(keyCols) == 1 {
		return "p." + keyCols[0]
	}
	parts := make([]string, len(keyCols))
	for i, col := range keyCols {
		parts[i] = "p." + col
	}
	return strings.Join(parts, " || ':' || ")
}

func generateSQL(gen *protogen.Plugin, file *protogen.File) {
	filename := file.GeneratedFilenamePrefix + "_sdm_schema.sql"
	g := gen.NewGeneratedFile(filename, "")

	g.P("-- Code generated by sdm. DO NOT EDIT.")
	g.P()

	for _, msg := range file.Messages {
		if !isSdmRecord(msg) {
			continue
		}
		modelName := strings.ToLower(msg.GoIdent.GoName)

		// PII Table
		g.P("CREATE TABLE IF NOT EXISTS pii_", modelName, "s (")
		pkCols := []string{}
		uniqueFields := []string{}
		type fkEntry struct{ col, refTable, refCol string }
		var fkFields []fkEntry

		for _, field := range msg.Fields {
			opts := getFieldOptions(field)
			// References fields must materialize as PII columns so the FK constraint
			// has a column to attach to. Otherwise CREATE TABLE fails with "column
			// X referenced in foreign key constraint does not exist."
			if opts.PrimaryKey || opts.Pii || opts.QueryIndex || opts.References != "" {
				sqlType := sqlTypeForField(field, opts)
				g.P(fmt.Sprintf("  %s %s,", field.Desc.Name(), sqlType))
				if opts.PrimaryKey {
					pkCols = append(pkCols, string(field.Desc.Name()))
				}
				if opts.Unique {
					uniqueFields = append(uniqueFields, string(field.Desc.Name()))
				}
			}
			if opts.References != "" {
				refTable, refCol := parseReference(opts.References)
				fkFields = append(fkFields, fkEntry{string(field.Desc.Name()), refTable, refCol})
			}
		}

		// Default audit columns on every PII table. The Go-side counterparts on
		// {Model}Pii / {Model}View are spliced in by generateMessageModels.
		g.P("  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,")
		g.P("  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,")
		g.P("  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,")

		type constraint struct{ line string }
		var constraints []constraint
		if len(pkCols) > 0 {
			constraints = append(constraints, constraint{
				fmt.Sprintf("  PRIMARY KEY (%s)", strings.Join(pkCols, ", ")),
			})
		}
		for _, uf := range uniqueFields {
			constraints = append(constraints, constraint{fmt.Sprintf("  UNIQUE (%s)", uf)})
		}
		for _, fk := range fkFields {
			constraints = append(constraints, constraint{
				fmt.Sprintf("  FOREIGN KEY (%s) REFERENCES %s(%s)", fk.col, fk.refTable, fk.refCol),
			})
		}
		for i, c := range constraints {
			if i < len(constraints)-1 {
				g.P(c.line + ",")
			} else {
				g.P(c.line)
			}
		}
		g.P(");")
		g.P()

		// Chain Table
		// version is scoped to (key, field_name) — each new entry for a field of a
		// given record gets MAX(version)+1 for that group, set by the BEFORE INSERT
		// trigger below. A global BIGSERIAL would leak insert order across all
		// records and make per-field history harder to read.
		g.P("CREATE TABLE IF NOT EXISTS chain_", modelName, "s (")
		g.P("  key TEXT NOT NULL,")
		g.P("  field_name TEXT NOT NULL,")
		g.P("  version BIGINT NOT NULL,")
		g.P("  tx_hash TEXT,")
		g.P("  field_value TEXT,")
		g.P("  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,")
		g.P("  PRIMARY KEY (key, field_name, version)")
		g.P(");")
		g.P()

		// Per-(key, field_name) version trigger.
		triggerFn := fmt.Sprintf("chain_%ss_set_version", modelName)
		triggerName := fmt.Sprintf("chain_%ss_set_version_trigger", modelName)
		chainTable := fmt.Sprintf("chain_%ss", modelName)
		g.P("CREATE OR REPLACE FUNCTION ", triggerFn, "()")
		g.P("RETURNS TRIGGER AS $$")
		g.P("BEGIN")
		g.P("  IF NEW.version IS NULL OR NEW.version = 0 THEN")
		g.P("    NEW.version := COALESCE(")
		g.P("      (SELECT MAX(version) FROM ", chainTable, " WHERE key = NEW.key AND field_name = NEW.field_name),")
		g.P("      0")
		g.P("    ) + 1;")
		g.P("  END IF;")
		g.P("  RETURN NEW;")
		g.P("END;")
		g.P("$$ LANGUAGE plpgsql;")
		g.P()
		g.P("DROP TRIGGER IF EXISTS ", triggerName, " ON ", chainTable, ";")
		g.P("CREATE TRIGGER ", triggerName)
		g.P("BEFORE INSERT ON ", chainTable)
		g.P("FOR EACH ROW EXECUTE FUNCTION ", triggerFn, "();")
		g.P()

		// View
		g.P("CREATE OR REPLACE VIEW ", modelName, "s AS")

		selects := []string{}
		joins := []string{}

		chainKeyExpr := sqlCompositeKeyExpr(chainKeyCols(msg))

		for _, field := range msg.Fields {
			opts := getFieldOptions(field)
			colName := string(field.Desc.Name())

			if opts.PrimaryKey || opts.Pii || opts.QueryIndex || opts.References != "" {
				selects = append(selects, fmt.Sprintf("p.%s", colName))
			} else {
				alias := "c_" + colName
				joins = append(joins, fmt.Sprintf(
					"LEFT JOIN (SELECT DISTINCT ON (key, field_name) field_value, key FROM chain_%ss WHERE field_name='%s' ORDER BY key, field_name, version DESC) %s ON %s = %s.key",
					modelName, colName, alias, chainKeyExpr, alias))
				// Chain field_value is TEXT; cast to JSONB so the view column has
				// the right type for JSON operators (->, ->>, @>, etc.).
				valueExpr := fmt.Sprintf("%s.field_value", alias)
				if isJsonStored(field, opts) {
					valueExpr += "::jsonb"
				}
				selects = append(selects, fmt.Sprintf("%s AS %s", valueExpr, colName))
			}

			if opts.Hashed {
				hashedName := "hashed_" + colName
				alias := "c_" + hashedName
				joins = append(joins, fmt.Sprintf(
					"LEFT JOIN (SELECT DISTINCT ON (key, field_name) field_value, key FROM chain_%ss WHERE field_name='%s' ORDER BY key, field_name, version DESC) %s ON %s = %s.key",
					modelName, hashedName, alias, chainKeyExpr, alias))
				selects = append(selects, fmt.Sprintf("%s.field_value AS %s", alias, hashedName))
			}
		}

		// Surface PII audit columns through the view so callers can read them
		// without joining pii_X separately.
		selects = append(selects, "p.created_at", "p.updated_at", "p.is_deleted")

		g.P("  SELECT")
		g.P("    ", strings.Join(selects, ",\n    "))
		g.P("  FROM pii_", modelName, "s p")
		for _, join := range joins {
			g.P("  ", join)
		}
		g.P(";")
		g.P()
	}
}

func generateRepo(gen *protogen.Plugin, file *protogen.File) {
	filename := file.GeneratedFilenamePrefix + "_sdm_repo.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	needSha256 := false
	needHex := false
	for _, msg := range file.Messages {
		if !isSdmRecord(msg) {
			continue
		}
		for _, field := range msg.Fields {
			opts := getFieldOptions(field)
			if opts.Hashed {
				needSha256 = true
				needHex = true
			}
		}
	}
	needDatatypes := fileHasPiiStringJsonField(file)
	needProtojson := fileHasChainMessageField(file)

	g.P("// Code generated by sdm. DO NOT EDIT.")
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	g.P("import (")
	g.P(`	"context"`)
	if needSha256 {
		g.P(`	"crypto/sha256"`)
	}
	if needHex {
		g.P(`	"encoding/hex"`)
	}
	g.P(`	"fmt"`)
	// "strings" not imported here — pgArrayLiteral lives in sdm_helpers.go,
	// generated once per package by GenerateHelpers to avoid redeclaration errors.
	if needProtojson {
		g.P(`	"google.golang.org/protobuf/encoding/protojson"`)
	}
	if needDatatypes {
		g.P(`	"gorm.io/datatypes"`)
	}
	g.P(`	"gorm.io/gorm"`)
	g.P(`	"gorm.io/gorm/clause"`)
	g.P(")")
	g.P()

	for _, msg := range file.Messages {
		if !isSdmRecord(msg) {
			continue
		}
		modelName := msg.GoIdent.GoName

		// Repo struct
		g.P("type ", modelName, "Repo struct {")
		g.P("  db *gorm.DB")
		g.P("}")
		g.P()

		g.P("func New", modelName, "Repo(db *gorm.DB) *", modelName, "Repo {")
		g.P("  return &", modelName, "Repo{db: db}")
		g.P("}")
		g.P()

		// collect all PK fields — needed by Fetch, Exists, and their param lists.
		var pkFields []*protogen.Field
		for _, field := range msg.Fields {
			if getFieldOptions(field).PrimaryKey {
				pkFields = append(pkFields, field)
			}
		}

		// compositeKeyExpr is the Go expression that produces the chain key string.
		// Uses chain_identifier_key fields if annotated (e.g. user_id UUID), else PKs.
		// Using a UUID keeps chain keys stable and opaque even when the PK is an
		// auto-incremented integer that could leak insertion order.
		// Must stay in sync with sqlCompositeKeyExpr used in the SQL view.
		keyFields := chainKeyGoFields(msg)
		var compositeKeyExpr string
		if len(keyFields) == 1 {
			compositeKeyExpr = fmt.Sprintf("fmt.Sprintf(\"%%v\", model.%s)", keyFields[0].GoName)
		} else {
			fmtParts := make([]string, len(keyFields))
			argParts := make([]string, len(keyFields))
			for i, f := range keyFields {
				fmtParts[i] = "%v"
				argParts[i] = "model." + f.GoName
			}
			compositeKeyExpr = fmt.Sprintf("fmt.Sprintf(\"%s\", %s)",
				strings.Join(fmtParts, ":"), strings.Join(argParts, ", "))
		}

		// emitMessageJsonMarshals pre-computes []byte for any chain-stored message
		// fields. The chain table's field_value is TEXT, so we serialize manually
		// here; for PII-table message fields GORM does this via the protojson
		// serializer registered in sdm_helpers.go.
		emitMessageJsonMarshals := func(accept func(*protogen.Field, SdmOptions) bool) {
			for _, field := range msg.Fields {
				opts := getFieldOptions(field)
				if !needsProtojsonMarshal(field) || !accept(field, opts) {
					continue
				}
				varName := jsonVarName(field)
				g.P("    var ", varName, " []byte")
				g.P("    if model.", field.GoName, " != nil {")
				g.P("      _b, err := protojson.Marshal(model.", field.GoName, ")")
				g.P("      if err != nil { return err }")
				g.P("      ", varName, " = _b")
				g.P("    }")
			}
		}

		chainAccept := func(field *protogen.Field, opts SdmOptions) bool {
			// References fields live in the PII table (the FK is on the PII column);
			// don't double-record them in the chain.
			return !opts.PrimaryKey && !opts.Pii && opts.References == ""
		}

		emitPiiStruct := func() {
			g.P("    pii := ", modelName, "Pii{")
			for _, field := range msg.Fields {
				opts := getFieldOptions(field)
				if opts.Pii || opts.PrimaryKey || opts.References != "" {
					if opts.AutoIncrement {
						continue
					}
					// PII struct field types match the Go shape: *Message for nested
					// proto messages (GORM serializes via the protojson serializer);
					// datatypes.JSON for string + (sdm.json)=true (cheap []byte cast);
					// scalar for everything else.
					switch {
					case needsProtojsonMarshal(field):
						g.P("      ", field.GoName, ": model.", field.GoName, ",")
					case opts.Json:
						g.P("      ", field.GoName, ": datatypes.JSON(model.", field.GoName, "),")
					default:
						g.P("      ", field.GoName, ": model.", field.GoName, ",")
					}
				}
			}
			g.P("    }")
		}

		emitChainEntries := func() {
			g.P("    compositeKey := ", compositeKeyExpr)
			emitMessageJsonMarshals(chainAccept)
			for _, field := range msg.Fields {
				opts := getFieldOptions(field)
				if opts.PrimaryKey {
					continue
				}
				if opts.References != "" {
					continue // references field is in PII, not chain
				}
				if !opts.Pii {
					// FIX: repeated fields must be serialised as a PG array literal.
					// fmt.Sprintf("%v", []string{"A","B"}) → "[A B]" which is invalid SQL.
					// pgArrayLiteral produces "{A,B}" which PostgreSQL accepts as text[].
					// JSON fields are datatypes.JSON ([]byte) — fmt %v would render the
					// byte slice as "[123 34 …]", so we cast to string to preserve the
					// JSON text exactly.
					var fieldValueExpr string
					switch {
					case needsProtojsonMarshal(field):
						fieldValueExpr = fmt.Sprintf("string(%s)", jsonVarName(field))
					case opts.Json:
						fieldValueExpr = fmt.Sprintf("string(model.%s)", field.GoName)
					case field.Desc.IsList():
						fieldValueExpr = fmt.Sprintf("pgArrayLiteral(model.%s)", field.GoName)
					default:
						fieldValueExpr = fmt.Sprintf("fmt.Sprintf(\"%%v\", model.%s)", field.GoName)
					}
					g.P("    if err := tx.Create(&", modelName, "Chain{")
					g.P("      Key:        compositeKey,")
					g.P("      FieldName:  \"", field.Desc.Name(), "\",")
					g.P("      FieldValue: ", fieldValueExpr, ",")
					g.P("    }).Error; err != nil { return err }")
				}
				if opts.Hashed {
					g.P("    // Hash ", field.GoName)
					g.P("    h_", field.GoName, " := sha256.Sum256([]byte(fmt.Sprintf(\"%v\", model.", field.GoName, ")))")
					g.P("    hashed_", field.GoName, " := hex.EncodeToString(h_", field.GoName, "[:])")
					g.P("    if err := tx.Create(&", modelName, "Chain{")
					g.P("      Key:        compositeKey,")
					g.P("      FieldName:  \"hashed_", field.Desc.Name(), "\",")
					g.P("      FieldValue: hashed_", field.GoName, ",")
					g.P("    }).Error; err != nil { return err }")
				}
			}
		}

		emitAutoIncrementCopyback := func() {
			for _, field := range msg.Fields {
				opts := getFieldOptions(field)
				if opts.AutoIncrement {
					g.P("    model.", field.GoName, " = pii.", field.GoName, " // copy DB-generated value back to model")
				}
			}
		}

		// ── SavePii ──────────────────────────────────────────────────────────────
		g.P("func (r *", modelName, "Repo) SavePii(ctx context.Context, model *", modelName, ") error {")
		g.P("  return r.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {")
		emitPiiStruct()
		g.P("    if err := tx.Create(&pii).Error; err != nil { return err }")
		emitAutoIncrementCopyback()
		g.P("    return nil")
		g.P("  })")
		g.P("}")
		g.P()

		// ── SaveChain ────────────────────────────────────────────────────────────
		g.P("func (r *", modelName, "Repo) SaveChain(ctx context.Context, model *", modelName, ") error {")
		g.P("  return r.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {")
		g.P("    // Save Chain Fields")
		emitChainEntries()
		g.P("    return nil")
		g.P("  })")
		g.P("}")
		g.P()

		// ── Save ─────────────────────────────────────────────────────────────────
		g.P("func (r *", modelName, "Repo) Save(ctx context.Context, model *", modelName, ") error {")
		g.P("  return r.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {")
		emitPiiStruct()
		g.P("    if err := tx.Clauses(clause.OnConflict{DoNothing: true}).Create(&pii).Error; err != nil { return err }")
		emitAutoIncrementCopyback()
		g.P()
		g.P("    // Save Chain Fields")
		emitChainEntries()
		g.P("    return nil")
		g.P("  })")
		g.P("}")
		g.P()

		// build WHERE clause params once — shared by Fetch and Exists.
		fetchParams := make([]string, len(pkFields))
		whereExprs := make([]string, len(pkFields))
		whereArgs := make([]string, len(pkFields))
		for i, f := range pkFields {
			paramName := strings.ToLower(f.GoName[:1]) + f.GoName[1:]
			fetchParams[i] = paramName + " " + goTypeForField(f)
			whereExprs[i] = string(f.Desc.Name()) + " = ?"
			whereArgs[i] = paramName
		}

		// notDeleted is the soft-delete filter appended to every read method.
		// Driven by the IsDeleted column on the PII table; the view inherits it.
		const notDeleted = `.Where("is_deleted = ?", false)`

		// ── Fetch ────────────────────────────────────────────────────────────────
		g.P("func (r *", modelName, "Repo) Fetch(ctx context.Context, ",
			strings.Join(fetchParams, ", "), ") (*", modelName, "View, error) {")
		g.P("  var view ", modelName, "View")
		g.P("  if err := r.db.WithContext(ctx).Where(\"", strings.Join(whereExprs, " AND "), "\", ",
			strings.Join(whereArgs, ", "), ")", notDeleted, ".First(&view).Error; err != nil {")
		g.P("    return nil, err")
		g.P("  }")
		g.P("  return &view, nil")
		g.P("}")
		g.P()

		// ── FetchBy{UniqueField} ─────────────────────────────────────────────────
		for _, field := range msg.Fields {
			opts := getFieldOptions(field)
			if !opts.Unique {
				continue
			}
			paramName := strings.ToLower(field.GoName[:1]) + field.GoName[1:]
			g.P("func (r *", modelName, "Repo) FetchBy", field.GoName,
				"(ctx context.Context, ", paramName, " ", goTypeForField(field), ") (*", modelName, "View, error) {")
			g.P("  var view ", modelName, "View")
			g.P("  if err := r.db.WithContext(ctx).Where(\"", field.Desc.Name(), " = ?\", ", paramName, ")", notDeleted, ".First(&view).Error; err != nil {")
			g.P("    return nil, err")
			g.P("  }")
			g.P("  return &view, nil")
			g.P("}")
			g.P()
		}

		// ── FetchBy{PkField} (composite PK only) ────────────────────────────────
		if len(pkFields) > 1 {
			for _, field := range pkFields {
				paramName := strings.ToLower(field.GoName[:1]) + field.GoName[1:]
				g.P("func (r *", modelName, "Repo) FetchBy", field.GoName,
					"(ctx context.Context, ", paramName, " ", goTypeForField(field), ") ([]", modelName, "View, error) {")
				g.P("  var views []", modelName, "View")
				g.P("  if err := r.db.WithContext(ctx).Where(\"", field.Desc.Name(), " = ?\", ", paramName, ")", notDeleted, ".Find(&views).Error; err != nil {")
				g.P("    return nil, err")
				g.P("  }")
				g.P("  return views, nil")
				g.P("}")
				g.P()
			}
		}

		// ── Exists ───────────────────────────────────────────────────────────────
		g.P("func (r *", modelName, "Repo) Exists(ctx context.Context, ",
			strings.Join(fetchParams, ", "), ") (bool, error) {")
		g.P("  var count int64")
		g.P("  if err := r.db.WithContext(ctx).Model(&", modelName, "Pii{}).Where(\"",
			strings.Join(whereExprs, " AND "), "\", ", strings.Join(whereArgs, ", "), ")", notDeleted, ".Count(&count).Error; err != nil {")
		g.P("    return false, err")
		g.P("  }")
		g.P("  return count > 0, nil")
		g.P("}")
		g.P()

		// ── ExistsBy{UniqueField} ────────────────────────────────────────────────
		for _, field := range msg.Fields {
			opts := getFieldOptions(field)
			if !opts.Unique {
				continue
			}
			paramName := strings.ToLower(field.GoName[:1]) + field.GoName[1:]
			g.P("func (r *", modelName, "Repo) ExistsBy", field.GoName,
				"(ctx context.Context, ", paramName, " ", goTypeForField(field), ") (bool, error) {")
			g.P("  var count int64")
			g.P("  if err := r.db.WithContext(ctx).Model(&", modelName, "Pii{}).Where(\"",
				field.Desc.Name(), " = ?\", ", paramName, ")", notDeleted, ".Count(&count).Error; err != nil {")
			g.P("    return false, err")
			g.P("  }")
			g.P("  return count > 0, nil")
			g.P("}")
			g.P()
		}
	}
}

// parseReference splits a "MessageName.field_name" references annotation into
// the PII table name and column name used in SQL FK constraints.
func parseReference(ref string) (table, column string) {
	parts := strings.SplitN(ref, ".", 2)
	if len(parts) != 2 {
		return "", ""
	}
	return "pii_" + strings.ToLower(parts[0]) + "s", parts[1]
}

type SdmOptions struct {
	PrimaryKey         bool
	ChainIdentifierKey bool // if set, this field is used as the chain key instead of the PK
	Pii                bool
	QueryIndex         bool
	Hashed             bool
	Unique             bool
	AutoIncrement      bool
	Json               bool // stored as Postgres JSONB and Go datatypes.JSON
	References         string
}

func getFieldOptions(field *protogen.Field) SdmOptions {
	opts := field.Desc.Options()

	getBool := func(ext protoreflect.ExtensionType) bool {
		if proto.HasExtension(opts, ext) {
			return proto.GetExtension(opts, ext).(bool)
		}
		return false
	}

	getString := func(ext protoreflect.ExtensionType) string {
		if proto.HasExtension(opts, ext) {
			return proto.GetExtension(opts, ext).(string)
		}
		return ""
	}

	return SdmOptions{
		PrimaryKey:         getBool(sdm.E_PrimaryKey),
		ChainIdentifierKey: getBool(sdm.E_ChainIdentifierKey),
		Pii:                getBool(sdm.E_Pii),
		QueryIndex:         getBool(sdm.E_QueryIndex),
		Hashed:             getBool(sdm.E_Hashed),
		Unique:             getBool(sdm.E_Unique),
		AutoIncrement:      getBool(sdm.E_AutoIncrement),
		Json:               getBool(sdm.E_Json),
		References:         getString(sdm.E_References),
	}
}

// isJsonStored reports whether a field is materialized as JSON: either marked
// with (sdm.json)=true on a string field, or any message-kind field (which has
// no scalar SQL mapping and is always serialized as JSON).
func isJsonStored(field *protogen.Field, opts SdmOptions) bool {
	return opts.Json || field.Desc.Kind() == protoreflect.MessageKind
}

// needsProtojsonMarshal reports whether converting model.X → datatypes.JSON
// requires protojson.Marshal (returns []byte, error) rather than a cheap
// string→[]byte conversion.
func needsProtojsonMarshal(field *protogen.Field) bool {
	return field.Desc.Kind() == protoreflect.MessageKind
}

// jsonVarName produces the local variable name used to hold the marshaled JSON
// bytes for a message-kind field, e.g. field.GoName=Amount → "amountJSON".
func jsonVarName(field *protogen.Field) string {
	return strings.ToLower(field.GoName[:1]) + field.GoName[1:] + "JSON"
}

// goTypeForField maps proto field kinds to Go types.
//   - Message-kind fields → typed *MessageName pointer (GORM uses protojson serializer)
//   - (sdm.json)=true string fields → datatypes.JSON (raw bytes)
//   - repeated fields → []string / []int64 on the domain model and repo params;
//     the View struct uses pq.StringArray directly in generateMessageModels
//   - scalars → string / int64
func goTypeForField(field *protogen.Field) string {
	if field.Desc.Kind() == protoreflect.MessageKind {
		return "*" + field.Message.GoIdent.GoName
	}
	if getFieldOptions(field).Json {
		return "datatypes.JSON"
	}
	base := func() string {
		switch field.Desc.Kind() {
		case protoreflect.StringKind:
			return "string"
		case protoreflect.Int64Kind, protoreflect.Int32Kind:
			return "int64"
		default:
			return "string"
		}
	}()
	if field.Desc.IsList() {
		return "[]" + base
	}
	return base
}

// sqlTypeForField emits BIGSERIAL for auto_increment fields, JSONB for
// json-stored fields (annotated or message-kind), TEXT/BIGINT otherwise.
// Repeated fields are chain-only and never appear in the PII table.
func sqlTypeForField(field *protogen.Field, opts SdmOptions) string {
	if opts.AutoIncrement {
		return "BIGSERIAL"
	}
	if isJsonStored(field, opts) {
		return "JSONB"
	}
	switch field.Desc.Kind() {
	case protoreflect.StringKind:
		return "TEXT"
	case protoreflect.Int64Kind, protoreflect.Int32Kind:
		return "BIGINT"
	default:
		return "TEXT"
	}
}

// fileHasStringJsonField reports whether any string field is annotated with
// (sdm.json)=true — that's the only case where the generated Go references
// datatypes.JSON (message-kind fields use a typed pointer instead).
func fileHasStringJsonField(file *protogen.File) bool {
	for _, msg := range file.Messages {
		if !isSdmRecord(msg) {
			continue
		}
		for _, field := range msg.Fields {
			opts := getFieldOptions(field)
			if opts.Json && field.Desc.Kind() == protoreflect.StringKind {
				return true
			}
		}
	}
	return false
}

// fileHasMessageJsonField reports whether any field is a nested proto message
// on a recorded message — drives the protojson serializer emission in helpers.
func fileHasMessageJsonField(file *protogen.File) bool {
	for _, msg := range file.Messages {
		if !isSdmRecord(msg) {
			continue
		}
		for _, field := range msg.Fields {
			if needsProtojsonMarshal(field) {
				return true
			}
		}
	}
	return false
}

// fileHasChainMessageField reports whether any chain-stored (non-PII, non-PK)
// field is a nested proto message — drives the protojson import in the repo
// file, since chain entries marshal manually into the TEXT field_value column.
func fileHasChainMessageField(file *protogen.File) bool {
	for _, msg := range file.Messages {
		if !isSdmRecord(msg) {
			continue
		}
		for _, field := range msg.Fields {
			if !needsProtojsonMarshal(field) {
				continue
			}
			opts := getFieldOptions(field)
			if !opts.Pii && !opts.PrimaryKey && opts.References == "" {
				return true
			}
		}
	}
	return false
}

// fileHasPiiStringJsonField reports whether any PII-routed string field is
// annotated (sdm.json)=true. That's the only place the repo file references
// datatypes.JSON — the PII struct literal casts model.X (string) to JSONB
// bytes. Chain entries use a plain string→string conversion, so they don't
// pull in datatypes.
func fileHasPiiStringJsonField(file *protogen.File) bool {
	for _, msg := range file.Messages {
		if !isSdmRecord(msg) {
			continue
		}
		for _, field := range msg.Fields {
			opts := getFieldOptions(field)
			if opts.Pii && opts.Json && field.Desc.Kind() == protoreflect.StringKind {
				return true
			}
		}
	}
	return false
}

// isSdmRecord reports whether a message should produce SDM tables (PII/chain/
// view + repo). A record needs at least one primary_key field — value-type
// messages (e.g. `Money { value, unit }` used inline as JSON) have none and
// must be skipped to avoid empty CREATE TABLE statements and broken views.
func isSdmRecord(msg *protogen.Message) bool {
	for _, field := range msg.Fields {
		if getFieldOptions(field).PrimaryKey {
			return true
		}
	}
	return false
}
