package generator

import (
	"fmt"
	"strings"

	"path"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"

	sdm "github.com/kapow-tech/sdm/sdmprotos" // Import the generated code for annotations
)

// Options configures optional generator features.
//
// CreateAuditTables controls whether each PII-backed message gets an
// audit_pii_<name>s table, the AFTER UPDATE/DELETE trigger, the
// <Name>PiiAudit Go struct, and the Repo.AuditLog method. When false,
// the actor still flows into pii.created_by / chain.created_by (those
// columns are independent), but the `sdm.actor` session-variable assignment
// is skipped — nothing reads it.
type Options struct {
	CreateAuditTables bool
}

// DefaultOptions returns the options used when callers don't supply any —
// audit tables are emitted by default.
func DefaultOptions() Options {
	return Options{CreateAuditTables: true}
}

// GenerateFile generates the SDM artifacts for a single proto file.
// After iterating all files, call GenerateHelpers(gen, anyFile) exactly once.
func GenerateFile(gen *protogen.Plugin, file *protogen.File, opts Options) {
	if len(file.Messages) == 0 {
		return
	}

	// generate Go models
	generateModels(gen, file, opts)
	// generate SQL schema
	generateSQL(gen, file, opts)
	// generate GORM repository
	generateRepo(gen, file, opts)
}

// GenerateHelpers emits sdm_helpers.go exactly once for the whole package.
// Must be called from main.go AFTER the GenerateFile loop — not inside it.
// GenerateFile runs once per proto file; calling this inside it would produce
// one helpers file per message type, causing "pgArrayLiteral redeclared" errors.
func GenerateHelpers(gen *protogen.Plugin, file *protogen.File) {
	// Derive the package directory from the file prefix, e.g.:
	//   file.GeneratedFilenamePrefix = "ttf/users"  →  dir = "ttf"
	// Using path.Dir (not filepath) because protogen paths are always forward-slash.
	dir := path.Dir(file.GeneratedFilenamePrefix)
	filename := path.Join(dir, "sdm_helpers.go")
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	needProtojson := packageHasMessageJsonField(gen)
	needProtojsonArray := packageHasRepeatedMessageField(gen)
	needReflectStack := needProtojson || needProtojsonArray
	// encoding/json is used by the array serializer to split the bytes into
	// per-element JSON.RawMessage before per-element protojson.Unmarshal.
	needEncodingJson := needProtojsonArray

	g.P("// Code generated by sdm. DO NOT EDIT.")
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	g.P("import (")
	if needEncodingJson {
		g.P(`	"encoding/json"`)
	}
	// `context` is always needed: WithActor / actorFromContext use it.
	g.P(`	"context"`)
	g.P(`	"strings"`)
	g.P(`	"time"`)
	if needReflectStack {
		g.P(`	"fmt"`)
		g.P(`	"reflect"`)
		g.P(`	"google.golang.org/protobuf/encoding/protojson"`)
		g.P(`	"google.golang.org/protobuf/proto"`)
		g.P(`	"gorm.io/gorm/schema"`)
	}
	g.P(")")
	g.P()
	g.P("// pgArrayLiteral serialises a string slice as a PostgreSQL array literal.")
	g.P("// e.g. []string{\"A\", \"B\"} → \"{A,B}\"")
	g.P("// fmt.Sprintf(\"%v\", slice) produces \"[A B]\" which is NOT valid PostgreSQL —")
	g.P("// this helper produces \"{A,B}\" which survives a ::text[] cast.")
	g.P("func pgArrayLiteral(vals []string) string {")
	g.P(`  return "{" + strings.Join(vals, ",") + "}"`)
	g.P("}")
	g.P()
	g.P("// ChangeLogEntry is a single (version → value, timestamp) row in a ChangeLog.")
	g.P("// Value is the raw chain field_value (TEXT). Numeric / JSON / array fields")
	g.P("// are returned as their stored string form — callers cast as needed.")
	g.P("type ChangeLogEntry struct {")
	g.P("  Value     string    `json:\"value\"`")
	g.P("  Timestamp time.Time `json:\"timestamp\"`")
	g.P("}")
	g.P()
	g.P("// ChangeLog maps field_name → version → entry. Versions are 1-based and")
	g.P("// monotonically increasing per (key, field_name), assigned by the chain")
	g.P("// table's BEFORE INSERT trigger.")
	g.P("type ChangeLog map[string]map[int64]ChangeLogEntry")
	g.P()
	g.P("// actorKey is the context key carrying the actor identifier that")
	g.P("// populates created_by on PII rows, created_by on chain rows, and")
	g.P("// changed_by on audit rows (via the AFTER UPDATE/DELETE trigger).")
	g.P("// Unexported so callers must go through WithActor / actorFromContext.")
	g.P("type actorKey struct{}")
	g.P()
	g.P("// WithActor returns a derived context that propagates the actor")
	g.P("// identifier to any PII mutation made through the generated")
	g.P("// Save / SaveAll / SaveChain methods. Inside the same transaction")
	g.P("// as the write the repo sets the Postgres session variable")
	g.P("// `sdm.actor` from this value (scoping the attribution to that")
	g.P("// transaction) AND assigns it to the created_by column on INSERT.")
	g.P("// The AFTER UPDATE/DELETE trigger reads the same session variable")
	g.P("// to populate audit_pii_<name>s.changed_by. Direct GORM operations")
	g.P("// (db.Exec / db.Delete) that do not pass through Save / SaveAll")
	g.P("// record '' for changed_by.")
	g.P("func WithActor(ctx context.Context, actorID string) context.Context {")
	g.P("  return context.WithValue(ctx, actorKey{}, actorID)")
	g.P("}")
	g.P()
	g.P("// actorFromContext extracts the actor identifier installed by")
	g.P("// WithActor, or \"\" if absent. Used by generated repo methods.")
	g.P("func actorFromContext(ctx context.Context) string {")
	g.P("  if v, ok := ctx.Value(actorKey{}).(string); ok { return v }")
	g.P("  return \"\"")
	g.P("}")
	if needProtojson {
		g.P()
		emitProtojsonSerializer(g)
	}
	if needProtojsonArray {
		g.P()
		emitProtojsonArraySerializer(g)
	}
}

// emitProtojsonSerializer writes a GORM serializer that marshals/unmarshals
// proto messages using protojson, registered as "protojson" in init(). View
// and PII struct fields use it via the tag `serializer:protojson`, so reads
// surface a typed *Message rather than raw JSON bytes and writes accept the
// same typed value (GORM calls Value() to produce JSONB bytes).
func emitProtojsonSerializer(g *protogen.GeneratedFile) {
	g.P("type protojsonSerializer struct{}")
	g.P()
	g.P("func init() {")
	g.P(`	schema.RegisterSerializer("protojson", protojsonSerializer{})`)
	g.P("}")
	g.P()
	g.P("func (protojsonSerializer) Scan(ctx context.Context, field *schema.Field, dst reflect.Value, dbValue interface{}) error {")
	g.P("	if dbValue == nil { return nil }")
	g.P("	var data []byte")
	g.P("	switch v := dbValue.(type) {")
	g.P("	case []byte: data = v")
	g.P("	case string:  data = []byte(v)")
	g.P("	default: return fmt.Errorf(\"protojson: unsupported source type %T for field %s\", dbValue, field.Name)")
	g.P("	}")
	g.P("	if len(data) == 0 { return nil }")
	g.P("	ft := field.FieldType")
	g.P("	if ft.Kind() != reflect.Ptr {")
	g.P("		return fmt.Errorf(\"protojson: field %s must be a pointer to a proto.Message\", field.Name)")
	g.P("	}")
	g.P("	ptr := reflect.New(ft.Elem())")
	g.P("	msg, ok := ptr.Interface().(proto.Message)")
	g.P("	if !ok {")
	g.P("		return fmt.Errorf(\"protojson: field %s does not implement proto.Message\", field.Name)")
	g.P("	}")
	g.P("	if err := protojson.Unmarshal(data, msg); err != nil { return err }")
	g.P("	field.ReflectValueOf(ctx, dst).Set(ptr)")
	g.P("	return nil")
	g.P("}")
	g.P()
	g.P("func (protojsonSerializer) Value(ctx context.Context, field *schema.Field, dst reflect.Value, fieldValue interface{}) (interface{}, error) {")
	g.P("	if fieldValue == nil { return nil, nil }")
	g.P("	v := reflect.ValueOf(fieldValue)")
	g.P("	if v.Kind() == reflect.Ptr && v.IsNil() { return nil, nil }")
	g.P("	msg, ok := fieldValue.(proto.Message)")
	g.P("	if !ok {")
	g.P("		return nil, fmt.Errorf(\"protojson: field %s does not implement proto.Message (got %T)\", field.Name, fieldValue)")
	g.P("	}")
	g.P("	return protojson.Marshal(msg)")
	g.P("}")
}

// emitProtojsonArraySerializer writes a GORM serializer that handles slices of
// proto messages — i.e. `[]*MessageType` fields with the tag
// `serializer:protojsonArray`. The wire format is a JSON array of objects, one
// per element, each canonical protojson. Used by both View and PII when a
// repeated message field is present.
//
// Scan: splits the bytes via encoding/json into []json.RawMessage, then
// protojson.Unmarshals each element into a fresh *Message of the slice's
// element type. Empty / nil input is treated as a nil slice.
//
// Value: walks the slice via reflection, protojson.Marshals each element,
// and joins the bytes as `[a,b,c]`. Nil / empty slice produces `[]` so the
// stored bytes remain valid JSON (the view's `::jsonb` cast would otherwise
// reject an empty string).
func emitProtojsonArraySerializer(g *protogen.GeneratedFile) {
	g.P("type protojsonArraySerializer struct{}")
	g.P()
	g.P("func init() {")
	g.P(`	schema.RegisterSerializer("protojsonArray", protojsonArraySerializer{})`)
	g.P("}")
	g.P()
	g.P("func (protojsonArraySerializer) Scan(ctx context.Context, field *schema.Field, dst reflect.Value, dbValue interface{}) error {")
	g.P("	if dbValue == nil { return nil }")
	g.P("	var data []byte")
	g.P("	switch v := dbValue.(type) {")
	g.P("	case []byte: data = v")
	g.P("	case string:  data = []byte(v)")
	g.P("	default: return fmt.Errorf(\"protojsonArray: unsupported source type %T for field %s\", dbValue, field.Name)")
	g.P("	}")
	g.P("	if len(data) == 0 { return nil }")
	g.P("	ft := field.FieldType")
	g.P("	if ft.Kind() != reflect.Slice {")
	g.P("		return fmt.Errorf(\"protojsonArray: field %s must be a slice\", field.Name)")
	g.P("	}")
	g.P("	elemType := ft.Elem()")
	g.P("	if elemType.Kind() != reflect.Ptr {")
	g.P("		return fmt.Errorf(\"protojsonArray: field %s slice element must be a pointer\", field.Name)")
	g.P("	}")
	g.P("	var raw []json.RawMessage")
	g.P("	if err := json.Unmarshal(data, &raw); err != nil { return err }")
	g.P("	slice := reflect.MakeSlice(ft, 0, len(raw))")
	g.P("	for _, r := range raw {")
	g.P("		ptr := reflect.New(elemType.Elem())")
	g.P("		msg, ok := ptr.Interface().(proto.Message)")
	g.P("		if !ok {")
	g.P("			return fmt.Errorf(\"protojsonArray: field %s element does not implement proto.Message\", field.Name)")
	g.P("		}")
	g.P("		if err := protojson.Unmarshal(r, msg); err != nil { return err }")
	g.P("		slice = reflect.Append(slice, ptr)")
	g.P("	}")
	g.P("	field.ReflectValueOf(ctx, dst).Set(slice)")
	g.P("	return nil")
	g.P("}")
	g.P()
	g.P("func (protojsonArraySerializer) Value(ctx context.Context, field *schema.Field, dst reflect.Value, fieldValue interface{}) (interface{}, error) {")
	g.P("	if fieldValue == nil { return []byte(\"[]\"), nil }")
	g.P("	v := reflect.ValueOf(fieldValue)")
	g.P("	if v.Kind() != reflect.Slice {")
	g.P("		return nil, fmt.Errorf(\"protojsonArray: field %s must be a slice (got %T)\", field.Name, fieldValue)")
	g.P("	}")
	g.P("	if v.Len() == 0 { return []byte(\"[]\"), nil }")
	g.P("	parts := make([]string, 0, v.Len())")
	g.P("	for i := 0; i < v.Len(); i++ {")
	g.P("		elem := v.Index(i).Interface()")
	g.P("		msg, ok := elem.(proto.Message)")
	g.P("		if !ok {")
	g.P("			return nil, fmt.Errorf(\"protojsonArray: field %s element %d does not implement proto.Message (got %T)\", field.Name, i, elem)")
	g.P("		}")
	g.P("		b, err := protojson.Marshal(msg)")
	g.P("		if err != nil { return nil, err }")
	g.P("		parts = append(parts, string(b))")
	g.P("	}")
	g.P("	return []byte(\"[\" + strings.Join(parts, \",\") + \"]\"), nil")
	g.P("}")
}

// packageHasMessageJsonField scans all files this plugin is generating to
// decide whether sdm_helpers.go should emit the protojson serializer + init.
func packageHasMessageJsonField(gen *protogen.Plugin) bool {
	for _, f := range gen.Files {
		if !f.Generate {
			continue
		}
		if fileHasMessageJsonField(f) {
			return true
		}
	}
	return false
}

// packageHasRepeatedMessageField scans all files for any repeated message
// field on a recorded message — drives the protojsonArray serializer emission
// in helpers. Used by both the View `[]*Message` column type and the PII
// `[]*Message` column type.
func packageHasRepeatedMessageField(gen *protogen.Plugin) bool {
	for _, f := range gen.Files {
		if !f.Generate {
			continue
		}
		if fileHasRepeatedMessageField(f) {
			return true
		}
	}
	return false
}

func generateModels(gen *protogen.Plugin, file *protogen.File, opts Options) {
	filename := file.GeneratedFilenamePrefix + "_sdm_model.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	// Repeated scalar fields — in either View or PII — use pq.StringArray.
	needPq := false
	for _, msg := range file.Messages {
		if !isSdmRecord(msg) {
			continue
		}
		for _, field := range msg.Fields {
			if field.Desc.IsList() && field.Desc.Kind() != protoreflect.MessageKind {
				needPq = true
				break
			}
		}
	}

	// timestamppb is needed by AsBaseModel for Timestamp fields
	// (time.Time → *timestamppb.Timestamp).
	needTimestamppb := fileHasTimestampField(file)

	g.P("// Code generated by sdm. DO NOT EDIT.")
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	// datatypes.JSON is used by string fields annotated (sdm.json)=true AND by
	// every PII-backed message's `<Name>PiiAudit.LastValue` column (jsonb).
	// The audit-table contribution is gated by opts.CreateAuditTables — when
	// audit is off, no PiiAudit struct is emitted so the import isn't needed
	// solely for that.
	needDatatypes := fileHasStringJsonField(file) ||
		(opts.CreateAuditTables && fileHasPiiBackedMessage(file))

	g.P("import (")
	g.P(`	"time"`)
	if needDatatypes {
		g.P(`	"gorm.io/datatypes"`)
	}
	if needPq {
		g.P(`	"github.com/lib/pq"`)
	}
	g.P(`	"gorm.io/gorm"`)
	if needTimestamppb {
		g.P(`	"google.golang.org/protobuf/types/known/timestamppb"`)
	}
	g.P(")")
	g.P()

	for _, msg := range file.Messages {
		if !isSdmRecord(msg) {
			continue // value-type message (e.g. Money) — used inline as JSON, no tables
		}
		generateMessageModels(g, msg, opts)
	}
}

func generateMessageModels(g *protogen.GeneratedFile, msg *protogen.Message, genOpts Options) {
	modelName := msg.GoIdent.GoName
	chainOnly := isChainOnly(msg)

	// ── PII Table Structure (skipped for chain-only messages) ────────────────
	if !chainOnly {
		g.P("type ", modelName, "Pii struct {")
		for _, field := range msg.Fields {
			opts := getFieldOptions(field)
			if !(opts.PrimaryKey || opts.Pii || opts.QueryIndex || opts.References != "") {
				continue
			}
			var goType, tag string
			switch {
			case field.Desc.IsList() && field.Desc.Kind() == protoreflect.MessageKind:
				// repeated *MessageType in PII — typed slice with JSONB storage
				// via the protojsonArray serializer.
				goType = "[]*" + field.Message.GoIdent.GoName
				tag = "column:" + string(field.Desc.Name()) + ";type:jsonb;serializer:protojsonArray"
			case field.Desc.IsList():
				// repeated scalar in PII — pq.StringArray maps to text[].
				goType = "pq.StringArray"
				tag = "column:" + string(field.Desc.Name()) + ";type:text[]"
			default:
				goType = goTypeForField(field)
				tag = "column:" + string(field.Desc.Name())
				if opts.PrimaryKey {
					tag += ";primaryKey"
				}
				if opts.Unique {
					tag += ";uniqueIndex"
				}
				if opts.AutoIncrement {
					tag += ";autoIncrement"
				}
				if isJsonStored(field, opts) {
					tag += ";type:jsonb"
				}
				if needsProtojsonMarshal(field) {
					tag += ";serializer:protojson"
				}
			}
			g.P(field.GoName, " ", goType, " `gorm:\"", tag, "\"`")
		}
		// Audit columns — always present on every PII table.
		// DeletedAt uses gorm.DeletedAt so GORM's soft-delete scope applies automatically.
		// CreatedBy captures the actor at INSERT (from WithActor(ctx, …))
		// and is preserved across upserts. "Who last updated this row" is
		// not stored here — read it from the latest audit_pii_<name>s row,
		// which the AFTER UPDATE trigger writes from the same `sdm.actor`
		// session variable.
		g.P("CreatedAt time.Time `gorm:\"column:created_at\"`")
		g.P("UpdatedAt time.Time `gorm:\"column:updated_at\"`")
		g.P("DeletedAt gorm.DeletedAt `gorm:\"column:deleted_at\"`")
		g.P("CreatedBy string `gorm:\"column:created_by\"`")
		g.P("}")
		g.P()
	}

	// ── Chain Table Structure ─────────────────────────────────────────────────
	// Chain rows are append-only, so the only actor column is CreatedBy
	// (populated from WithActor(ctx, …) at insert time).
	g.P("type ", modelName, "Chain struct {")
	g.P("Key string `gorm:\"primaryKey;column:key\"`")
	g.P("FieldName string `gorm:\"primaryKey;column:field_name\"`")
	g.P("Version int64 `gorm:\"primaryKey;column:version;autoIncrement\"`")
	g.P("TxHash string `gorm:\"column:tx_hash\"`")
	g.P("FieldValue string `gorm:\"column:field_value\"`")
	g.P("CreatedAt time.Time `gorm:\"column:created_at\"`")
	g.P("CreatedBy string `gorm:\"column:created_by\"`")
	g.P("}")
	g.P()

	// ── View Structure ────────────────────────────────────────────────────────
	// repeated scalar fields use pq.StringArray (text[] column).
	// repeated message fields use []*Message via protojsonArray serializer —
	// the underlying column is JSONB (chain TEXT cast to ::jsonb in the view,
	// or PII's native JSONB column) and the serializer decodes per-element.
	g.P("type ", modelName, "View struct {")
	for _, field := range msg.Fields {
		var goType, viewTag string
		if field.Desc.IsList() {
			if field.Desc.Kind() == protoreflect.MessageKind {
				goType = "[]*" + field.Message.GoIdent.GoName
				viewTag = fmt.Sprintf("column:%s;type:jsonb;serializer:protojsonArray", field.Desc.Name())
			} else {
				goType = "pq.StringArray"
				viewTag = fmt.Sprintf("column:%s;type:text[]", field.Desc.Name())
			}
		} else {
			goType = goTypeForViewField(field)
			viewTag = "column:" + string(field.Desc.Name())
			if needsProtojsonMarshal(field) {
				// View column comes from a ::jsonb cast over the chain's TEXT field_value
				// (or directly from the PII JSONB column). The serializer decodes those
				// bytes into a typed *Message on read.
				viewTag += ";serializer:protojson"
			}
		}
		g.P(field.GoName, " ", goType, " `gorm:\"", viewTag, "\"`")

		opts := getFieldOptions(field)
		if opts.Hashed {
			g.P("Hashed", field.GoName, " string `gorm:\"column:hashed_", field.Desc.Name(), "\"`")
		}
	}
	// Audit columns surfaced from the PII table on the view.
	// DeletedAt uses gorm.DeletedAt so GORM's soft-delete scope also applies
	// to view queries (a redundant safety net; read methods also emit an
	// explicit `deleted_at IS NULL` filter for clarity).
	// CreatedBy is the actor at INSERT; "who last updated" is intentionally
	// not exposed here — query audit_pii_<name>s for that.
	g.P("CreatedAt time.Time `gorm:\"column:created_at\"`")
	g.P("UpdatedAt time.Time `gorm:\"column:updated_at\"`")
	g.P("DeletedAt gorm.DeletedAt `gorm:\"column:deleted_at\"`")
	g.P("CreatedBy string `gorm:\"column:created_by\"`")
	g.P("TxHash string `gorm:\"column:tx_hash\"`")
	g.P("}")
	g.P()

	// ── TableName overrides ───────────────────────────────────────────────────
	if !chainOnly {
		g.P("func (", modelName, "Pii) TableName() string { return \"pii_", strings.ToLower(modelName), "s\" }")
	}
	g.P("func (", modelName, "Chain) TableName() string { return \"chain_", strings.ToLower(modelName), "s\" }")
	g.P("func (", modelName, "View) TableName() string { return \"", strings.ToLower(modelName), "s\" }")
	g.P()

	// ── PII Audit struct ──────────────────────────────────────────────────────
	// Mirror of audit_pii_<name>s. The table + trigger are emitted by
	// generateSQL only for PII-backed messages, so the struct is only emitted
	// here when !chainOnly. Skipped entirely when audit tables are disabled
	// via Options.CreateAuditTables=false.
	if !chainOnly && genOpts.CreateAuditTables {
		g.P("type ", modelName, "PiiAudit struct {")
		g.P("  Id         int64          `gorm:\"column:id;primaryKey;autoIncrement\"`")
		g.P("  RefId      string         `gorm:\"column:ref_id\"`")
		g.P("  LastValue  datatypes.JSON `gorm:\"column:last_value;type:jsonb\"`")
		g.P("  ChangeType string         `gorm:\"column:change_type\"`")
		g.P("  ChangedBy  string         `gorm:\"column:changed_by\"`")
		g.P("  ChangedAt  time.Time      `gorm:\"column:changed_at\"`")
		g.P("}")
		g.P()
		g.P("func (", modelName, "PiiAudit) TableName() string { return \"audit_pii_", strings.ToLower(modelName), "s\" }")
		g.P()
	}

	// ── EnsureUnique method ───────────────────────────────────────────────────
	g.P("func (c *", modelName, "Chain) EnsureUnique(tx *gorm.DB) bool {")
	g.P("  var count int64")
	g.P("  err := tx.Model(&", modelName, "Chain{}).Where(\"field_name = ? AND field_value = ?\", c.FieldName, c.FieldValue).Count(&count).Error")
	g.P("  if err != nil {")
	g.P("    return false")
	g.P("  }")
	g.P("  return count == 0")
	g.P("}")
	g.P()

	// ── AsBaseModel ──────────────────────────────────────────────────────────
	// Converts the view row back to the base proto model. Useful for re-saving
	// (View → AsBaseModel → SaveAll). Audit columns (CreatedAt / UpdatedAt /
	// DeletedAt / TxHash) and hashed_* sidecar columns are dropped because they
	// have no counterpart on the base proto model.
	//
	// Per-field conversion:
	//   - scalar              : direct assignment (types match)
	//   - enum                : string → EnumType via EnumType_value map lookup
	//   - *Message            : direct assignment (serializer:protojson already decoded)
	//   - Timestamp           : time.Time → timestamppb.New (skipped if zero)
	//   - (sdm.json)=true str : datatypes.JSON → string
	//   - repeated scalar     : pq.StringArray → []string
	//   - repeated *Message   : direct assignment ([]*Message via protojsonArray serializer)
	g.P("func (v *", modelName, "View) AsBaseModel() *", modelName, " {")
	g.P("  base := &", modelName, "{}")
	for _, field := range msg.Fields {
		opts := getFieldOptions(field)
		switch {
		case isProtoTimestamp(field):
			g.P("  if !v.", field.GoName, ".IsZero() {")
			g.P("    base.", field.GoName, " = timestamppb.New(v.", field.GoName, ")")
			g.P("  }")
		case needsProtojsonMarshal(field):
			g.P("  base.", field.GoName, " = v.", field.GoName)
		case needsRepeatedProtojsonMarshal(field):
			// View is now typed []*Message via protojsonArray serializer —
			// direct assignment, no unmarshal needed.
			g.P("  base.", field.GoName, " = v.", field.GoName)
		case opts.Json:
			g.P("  base.", field.GoName, " = string(v.", field.GoName, ")")
		case field.Desc.IsList():
			g.P("  base.", field.GoName, " = []string(v.", field.GoName, ")")
		case field.Desc.Kind() == protoreflect.EnumKind:
			// View stores the enum as a plain string (fmt.Sprintf("%v", enumVal)
			// produces the proto-registered name, e.g. "User_Status_Active").
			// Recover the typed enum via the generated _value map.
			enumType := field.Enum.GoIdent.GoName
			g.P("  base.", field.GoName, " = ", enumType, "(", enumType, "_value[v.", field.GoName, "])")
		default:
			g.P("  base.", field.GoName, " = v.", field.GoName)
		}
	}
	g.P("  return base")
	g.P("}")
	g.P()
}

// chainKeyCols returns the columns used as the chain key for a message.
func chainKeyCols(msg *protogen.Message) []string {
	var cols []string
	for _, field := range msg.Fields {
		if getFieldOptions(field).ChainIdentifierKey {
			cols = append(cols, string(field.Desc.Name()))
		}
	}
	if len(cols) > 0 {
		return cols
	}
	for _, field := range msg.Fields {
		if getFieldOptions(field).PrimaryKey {
			cols = append(cols, string(field.Desc.Name()))
		}
	}
	return cols
}

// chainKeyGoFields returns the protogen fields used as the chain key.
func chainKeyGoFields(msg *protogen.Message) []*protogen.Field {
	var fields []*protogen.Field
	for _, field := range msg.Fields {
		if getFieldOptions(field).ChainIdentifierKey {
			fields = append(fields, field)
		}
	}
	if len(fields) > 0 {
		return fields
	}
	for _, field := range msg.Fields {
		if getFieldOptions(field).PrimaryKey {
			fields = append(fields, field)
		}
	}
	return fields
}

// sqlCompositeKeyExpr builds the SQL expression that reproduces the compositeKey.
// For chain-only messages the anchor alias is "keys"; for PII-backed messages it is "p".
func sqlCompositeKeyExpr(keyCols []string, tableAlias string) string {
	if len(keyCols) == 1 {
		return tableAlias + "." + keyCols[0]
	}
	parts := make([]string, len(keyCols))
	for i, col := range keyCols {
		parts[i] = tableAlias + "." + col
	}
	return strings.Join(parts, " || ':' || ")
}

func generateSQL(gen *protogen.Plugin, file *protogen.File, opts Options) {
	filename := file.GeneratedFilenamePrefix + "_sdm_schema.sql"
	g := gen.NewGeneratedFile(filename, "")

	g.P("-- Code generated by sdm. DO NOT EDIT.")
	g.P()

	for _, msg := range file.Messages {
		if !isSdmRecord(msg) {
			continue
		}
		modelName := strings.ToLower(msg.GoIdent.GoName)
		chainOnly := isChainOnly(msg)

		// ── PII Table (skipped for chain-only messages) ───────────────────────
		if !chainOnly {
			g.P("CREATE TABLE IF NOT EXISTS pii_", modelName, "s (")
			pkCols := []string{}
			uniqueFields := []string{}
			type fkEntry struct{ col, refTable, refCol string }
			var fkFields []fkEntry

			for _, field := range msg.Fields {
				opts := getFieldOptions(field)
				if opts.PrimaryKey || opts.Pii || opts.QueryIndex || opts.References != "" {
					sqlType := sqlTypeForField(field, opts)
					g.P(fmt.Sprintf("  %s %s,", field.Desc.Name(), sqlType))
					if opts.PrimaryKey {
						pkCols = append(pkCols, string(field.Desc.Name()))
					}
					if opts.Unique {
						uniqueFields = append(uniqueFields, string(field.Desc.Name()))
					}
				}
				if opts.References != "" {
					refTable, refCol := parseReference(opts.References)
					fkFields = append(fkFields, fkEntry{string(field.Desc.Name()), refTable, refCol})
				}
			}

			// Audit columns — always present on every PII table.
			// deleted_at is nullable: NULL means the row is live; non-NULL means soft-deleted.
			// TZ-aware so timestamps remain correct across host/server tz drift.
			// created_by is populated from the actor on the request ctx at
			// INSERT (WithActor(ctx, actorID); else ''); preserved across
			// upserts. "Who updated this row" is captured per-change in
			// audit_pii_<name>s.changed_by — no row-level updated_by column
			// is stored.
			g.P("  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,")
			g.P("  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,")
			g.P("  deleted_at TIMESTAMP WITH TIME ZONE NULL,")
			g.P("  created_by TEXT NOT NULL DEFAULT '',")

			type constraint struct{ line string }
			var constraints []constraint
			if len(pkCols) > 0 {
				constraints = append(constraints, constraint{
					fmt.Sprintf("  PRIMARY KEY (%s)", strings.Join(pkCols, ", ")),
				})
			}
			for _, uf := range uniqueFields {
				constraints = append(constraints, constraint{fmt.Sprintf("  UNIQUE (%s)", uf)})
			}
			for _, fk := range fkFields {
				constraints = append(constraints, constraint{
					fmt.Sprintf("  FOREIGN KEY (%s) REFERENCES %s(%s)", fk.col, fk.refTable, fk.refCol),
				})
			}
			for i, c := range constraints {
				if i < len(constraints)-1 {
					g.P(c.line + ",")
				} else {
					g.P(c.line)
				}
			}
			g.P(");")
			g.P()

			// ── Audit Table + Trigger ─────────────────────────────────────────
			// audit_pii_<name>s captures the full OLD row (as JSONB) on every
			// UPDATE or DELETE against pii_<name>s. INSERTs aren't audited —
			// the chain table already records the newly-introduced values.
			//
			// changed_by reads from the `sdm.actor` Postgres session
			// variable. The generated Save / SaveAll methods set that variable
			// inside their transaction when the context carries a value via
			// WithActor(ctx, actorID). Changes made through other paths
			// (raw db.Exec, db.Delete outside a SaveAll transaction) record
			// '' for changed_by.
			//
			// ref_id is TEXT (cast from the PK via ::text) so the same audit
			// table works for both BIGINT and TEXT primary keys; composite PKs
			// are joined with ':' to mirror the chain compositeKey scheme.
			//
			// Entire block is gated on opts.CreateAuditTables.
			if opts.CreateAuditTables {
				auditTable := fmt.Sprintf("audit_pii_%ss", modelName)
				auditFn := fmt.Sprintf("audit_pii_%ss_log", modelName)
				auditTrigger := fmt.Sprintf("audit_pii_%ss_log_trigger", modelName)
				piiTable := fmt.Sprintf("pii_%ss", modelName)

				g.P("CREATE TABLE IF NOT EXISTS ", auditTable, " (")
				g.P("  id BIGSERIAL PRIMARY KEY,")
				g.P("  ref_id TEXT NOT NULL,")
				g.P("  last_value JSONB NOT NULL,")
				g.P("  change_type TEXT NOT NULL,")
				g.P("  changed_by TEXT NOT NULL DEFAULT '',")
				g.P("  changed_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP")
				g.P(");")
				g.P()

				// Compose the ref_id expression. Single-column PK is the
				// common case (cast to text). Composite PK is joined with
				// ':' to match chain compositeKey construction.
				var refIDExpr string
				switch len(pkCols) {
				case 0:
					// Should not happen for PII-backed messages (isSdmRecord
					// requires PK or chain_identifier_key, and chainOnly is
					// already false here).
					refIDExpr = "''"
				case 1:
					refIDExpr = fmt.Sprintf("OLD.%s::text", pkCols[0])
				default:
					parts := make([]string, len(pkCols))
					for i, c := range pkCols {
						parts[i] = fmt.Sprintf("OLD.%s::text", c)
					}
					refIDExpr = strings.Join(parts, " || ':' || ")
				}

				g.P("CREATE OR REPLACE FUNCTION ", auditFn, "()")
				g.P("RETURNS TRIGGER AS $$")
				g.P("BEGIN")
				g.P("  INSERT INTO ", auditTable, " (ref_id, last_value, change_type, changed_by)")
				g.P("  VALUES (")
				g.P("    ", refIDExpr, ",")
				g.P("    row_to_json(OLD)::jsonb,")
				g.P("    TG_OP,")
				g.P("    COALESCE(current_setting('sdm.actor', true), '')")
				g.P("  );")
				g.P("  RETURN NULL;")
				g.P("END;")
				g.P("$$ LANGUAGE plpgsql;")
				g.P()
				g.P("DROP TRIGGER IF EXISTS ", auditTrigger, " ON ", piiTable, ";")
				g.P("CREATE TRIGGER ", auditTrigger)
				g.P("AFTER UPDATE OR DELETE ON ", piiTable)
				g.P("FOR EACH ROW EXECUTE FUNCTION ", auditFn, "();")
				g.P()
			}
		}

		// ── Chain Table ───────────────────────────────────────────────────────
		// version is scoped to (key, field_name) — each new entry for a field of a
		// given record gets MAX(version)+1 for that group, set by the BEFORE INSERT
		// trigger below.
		g.P("CREATE TABLE IF NOT EXISTS chain_", modelName, "s (")
		g.P("  key TEXT NOT NULL,")
		g.P("  field_name TEXT NOT NULL,")
		g.P("  version BIGINT NOT NULL,")
		g.P("  tx_hash TEXT,")
		g.P("  field_value TEXT,")
		g.P("  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,")
		g.P("  created_by TEXT NOT NULL DEFAULT '',")
		g.P("  PRIMARY KEY (key, field_name, version)")
		g.P(");")
		g.P()

		// ── Per-(key, field_name) version trigger ─────────────────────────────
		triggerFn := fmt.Sprintf("chain_%ss_set_version", modelName)
		triggerName := fmt.Sprintf("chain_%ss_set_version_trigger", modelName)
		chainTable := fmt.Sprintf("chain_%ss", modelName)
		g.P("CREATE OR REPLACE FUNCTION ", triggerFn, "()")
		g.P("RETURNS TRIGGER AS $$")
		g.P("BEGIN")
		g.P("  IF NEW.version IS NULL OR NEW.version = 0 THEN")
		g.P("    NEW.version := COALESCE(")
		g.P("      (SELECT MAX(version) FROM ", chainTable, " WHERE key = NEW.key AND field_name = NEW.field_name),")
		g.P("      0")
		g.P("    ) + 1;")
		g.P("  END IF;")
		g.P("  RETURN NEW;")
		g.P("END;")
		g.P("$$ LANGUAGE plpgsql;")
		g.P()
		g.P("DROP TRIGGER IF EXISTS ", triggerName, " ON ", chainTable, ";")
		g.P("CREATE TRIGGER ", triggerName)
		g.P("BEFORE INSERT ON ", chainTable)
		g.P("FOR EACH ROW EXECUTE FUNCTION ", triggerFn, "();")
		g.P()

		// ── View ──────────────────────────────────────────────────────────────
		g.P("CREATE OR REPLACE VIEW ", modelName, "s AS")

		if chainOnly {
			generateChainOnlyView(g, msg, modelName)
		} else {
			generatePiiBackedView(g, msg, modelName)
		}

		g.P()
	}
}

// generatePiiBackedView emits the SQL view for messages that have a PII table.
// The view anchors on pii_* and left-joins chain fields.
func generatePiiBackedView(g *protogen.GeneratedFile, msg *protogen.Message, modelName string) {
	selects := []string{}
	joins := []string{}

	chainKeyExpr := sqlCompositeKeyExpr(chainKeyCols(msg), "p")

	for _, field := range msg.Fields {
		opts := getFieldOptions(field)
		colName := string(field.Desc.Name())

		if opts.PrimaryKey || opts.Pii || opts.QueryIndex || opts.References != "" {
			selects = append(selects, fmt.Sprintf("p.%s", colName))
		} else {
			alias := "c_" + colName
			joins = append(joins, fmt.Sprintf(
				"LEFT JOIN (SELECT DISTINCT ON (key, field_name) field_value, key FROM chain_%ss WHERE field_name='%s' ORDER BY key, field_name, version DESC) %s ON %s = %s.key",
				modelName, colName, alias, chainKeyExpr, alias))
			valueExpr := fmt.Sprintf("%s.field_value", alias)
			switch {
			case isProtoTimestamp(field):
				valueExpr += "::timestamptz"
			case isJsonStored(field, opts):
				valueExpr += "::jsonb"
			}
			selects = append(selects, fmt.Sprintf("%s AS %s", valueExpr, colName))
		}

		if opts.Hashed {
			hashedName := "hashed_" + colName
			alias := "c_" + hashedName
			joins = append(joins, fmt.Sprintf(
				"LEFT JOIN (SELECT DISTINCT ON (key, field_name) field_value, key FROM chain_%ss WHERE field_name='%s' ORDER BY key, field_name, version DESC) %s ON %s = %s.key",
				modelName, hashedName, alias, chainKeyExpr, alias))
			selects = append(selects, fmt.Sprintf("%s.field_value AS %s", alias, hashedName))
		}
	}

	// Always expose PII audit columns in the view. deleted_at is exposed raw
	// (nullable timestamptz); the view does not compute a boolean — GORM's
	// gorm.DeletedAt type on the View struct, plus an explicit
	// `WHERE deleted_at IS NULL` in read methods, handle the filtering.
	// Only created_by is surfaced; for "who last updated" callers query
	// audit_pii_<name>s directly (Repo.AuditLog).
	selects = append(selects, "p.created_at")
	selects = append(selects, "p.updated_at")
	selects = append(selects, "p.deleted_at")
	selects = append(selects, "p.created_by")

	// Latest tx_hash from the chain table for this record.
	joins = append(joins, fmt.Sprintf(
		"LEFT JOIN (SELECT DISTINCT ON (key) key, tx_hash FROM chain_%ss ORDER BY key, version DESC) c_tx ON %s = c_tx.key",
		modelName, chainKeyExpr))
	selects = append(selects, "c_tx.tx_hash")

	g.P("  SELECT")
	g.P("    ", strings.Join(selects, ",\n    "))
	g.P("  FROM pii_", modelName, "s p")
	for _, join := range joins {
		g.P("  ", join)
	}
	g.P(";")
}

// generateChainOnlyView emits the SQL view for messages with no PII table.
// The anchor is SELECT DISTINCT key FROM chain_*, and every field (including
// the chain_identifier_key itself, returned as keys.key) is a left-joined
// subquery. References fields carry a SQL comment noting the intended FK since
// no database-level constraint is possible without a PII anchor table.
func generateChainOnlyView(g *protogen.GeneratedFile, msg *protogen.Message, modelName string) {
	selects := []string{}
	joins := []string{}

	for _, field := range msg.Fields {
		opts := getFieldOptions(field)
		colName := string(field.Desc.Name())

		if opts.ChainIdentifierKey {
			// The key field maps directly from the anchor — no subquery needed.
			selects = append(selects, fmt.Sprintf("keys.key AS %s", colName))
			continue
		}

		alias := "c_" + colName
		joins = append(joins, fmt.Sprintf(
			"LEFT JOIN (SELECT DISTINCT ON (key) key, field_value FROM chain_%ss WHERE field_name = '%s' ORDER BY key, version DESC) %s ON keys.key = %s.key",
			modelName, colName, alias, alias))

		valueExpr := fmt.Sprintf("%s.field_value", alias)
		switch {
		case isProtoTimestamp(field):
			valueExpr += "::timestamptz"
		case isJsonStored(field, opts):
			valueExpr += "::jsonb"
		}

		comment := ""
		if opts.References != "" {
			comment = fmt.Sprintf(" -- references %s", opts.References)
		}
		selects = append(selects, fmt.Sprintf("%s AS %s%s", valueExpr, colName, comment))

		if opts.Hashed {
			hashedName := "hashed_" + colName
			hashedAlias := "c_" + hashedName
			joins = append(joins, fmt.Sprintf(
				"LEFT JOIN (SELECT DISTINCT ON (key) key, field_value FROM chain_%ss WHERE field_name = '%s' ORDER BY key, version DESC) %s ON keys.key = %s.key",
				modelName, hashedName, hashedAlias, hashedAlias))
			selects = append(selects, fmt.Sprintf("%s.field_value AS %s", hashedAlias, hashedName))
		}
	}

	// tx_hash — latest chain entry's hash for any field.
	joins = append(joins, fmt.Sprintf(
		"LEFT JOIN (SELECT DISTINCT ON (key) key, tx_hash FROM chain_%ss ORDER BY key, version DESC) c_tx ON keys.key = c_tx.key",
		modelName))
	selects = append(selects, "c_tx.tx_hash")

	g.P("  SELECT")
	g.P("    ", strings.Join(selects, ",\n    "))
	g.P("  FROM (SELECT DISTINCT key FROM chain_", modelName, "s) keys")
	for _, join := range joins {
		g.P("  ", join)
	}
	g.P(";")
}

func generateRepo(gen *protogen.Plugin, file *protogen.File, opts Options) {
	filename := file.GeneratedFilenamePrefix + "_sdm_repo.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	needSha256 := false
	needHex := false
	for _, msg := range file.Messages {
		if !isSdmRecord(msg) {
			continue
		}
		for _, field := range msg.Fields {
			opts := getFieldOptions(field)
			if opts.Hashed {
				needSha256 = true
				needHex = true
			}
		}
	}
	needDatatypes := fileHasPiiStringJsonField(file)
	// protojson + strings.Join in the REPO are needed only for chain-stored
	// fields. PII-stored repeated messages go through the protojsonArray
	// serializer in sdm_helpers.go and don't need either import here.
	needProtojson := fileHasChainMessageField(file) || fileHasChainRepeatedMessageField(file)
	needStringsJoin := fileHasChainRepeatedMessageField(file)
	// `time` is referenced by chain-side Timestamp serialization
	// (model.X.AsTime().Format(time.RFC3339Nano)).
	needTime := fileHasChainTimestampField(file)
	// pq.StringArray is used in the PII struct literal for repeated scalar
	// PII fields (`Tags: pq.StringArray(model.Tags)`).
	needPq := fileHasPiiRepeatedScalarField(file)

	g.P("// Code generated by sdm. DO NOT EDIT.")
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	g.P("import (")
	g.P(`	"context"`)
	if needSha256 {
		g.P(`	"crypto/sha256"`)
	}
	if needHex {
		g.P(`	"encoding/hex"`)
	}
	g.P(`	"fmt"`)
	if needTime {
		g.P(`	"time"`)
	}
	if needProtojson {
		g.P(`	"google.golang.org/protobuf/encoding/protojson"`)
	}
	if needStringsJoin {
		g.P(`	"strings"`)
	}
	if needPq {
		g.P(`	"github.com/lib/pq"`)
	}
	if needDatatypes {
		g.P(`	"gorm.io/datatypes"`)
	}
	g.P(`	"gorm.io/gorm"`)
	g.P(`	"gorm.io/gorm/clause"`)
	g.P(")")
	g.P()

	for _, msg := range file.Messages {
		if !isSdmRecord(msg) {
			continue
		}
		modelName := msg.GoIdent.GoName
		chainOnly := isChainOnly(msg)

		// Repo struct. The actor identifier for audit attribution flows
		// exclusively via ctx (see WithActor / actorFromContext); the repo
		// stays a pure data-access layer with no per-call mutable state.
		g.P("type ", modelName, "Repo struct {")
		g.P("  db *gorm.DB")
		g.P("}")
		g.P()

		g.P("func New", modelName, "Repo(db *gorm.DB) *", modelName, "Repo {")
		g.P("  return &", modelName, "Repo{db: db}")
		g.P("}")
		g.P()

		// compositeKeyExpr is the Go expression that produces the chain key string.
		// Uses chain_identifier_key fields if annotated (e.g. ptt_id), else PKs.
		keyFields := chainKeyGoFields(msg)
		var compositeKeyExpr string
		if len(keyFields) == 1 {
			compositeKeyExpr = fmt.Sprintf("fmt.Sprintf(\"%%v\", model.%s)", keyFields[0].GoName)
		} else {
			fmtParts := make([]string, len(keyFields))
			argParts := make([]string, len(keyFields))
			for i, f := range keyFields {
				fmtParts[i] = "%v"
				argParts[i] = "model." + f.GoName
			}
			compositeKeyExpr = fmt.Sprintf("fmt.Sprintf(\"%s\", %s)",
				strings.Join(fmtParts, ":"), strings.Join(argParts, ", "))
		}

		// emitMessageJsonMarshals pre-computes []byte for chain-stored message fields.
		// Singular: protojson.Marshal directly.
		// Repeated: marshal each element, join into a JSON array string.
		emitMessageJsonMarshals := func(accept func(*protogen.Field, SdmOptions) bool) {
			for _, field := range msg.Fields {
				opts := getFieldOptions(field)
				if !accept(field, opts) {
					continue
				}
				varName := jsonVarName(field)
				if needsProtojsonMarshal(field) {
					g.P("    var ", varName, " []byte")
					g.P("    if model.", field.GoName, " != nil {")
					g.P("      _b, err := protojson.Marshal(model.", field.GoName, ")")
					g.P("      if err != nil { return err }")
					g.P("      ", varName, " = _b")
					g.P("    }")
				} else if needsRepeatedProtojsonMarshal(field) {
					// Initialise with the empty JSON array literal so that an empty
					// or nil slice still produces valid JSON in chain field_value.
					// Otherwise the view's `c_X.field_value::jsonb` cast fails with
					// "invalid input syntax for type json" on the empty string.
					g.P("    ", varName, " := []byte(\"[]\")")
					g.P("    if len(model.", field.GoName, ") > 0 {")
					g.P("      _parts := make([]string, 0, len(model.", field.GoName, "))")
					g.P("      for _, _item := range model.", field.GoName, " {")
					g.P("        _b, err := protojson.Marshal(_item)")
					g.P("        if err != nil { return err }")
					g.P("        _parts = append(_parts, string(_b))")
					g.P("      }")
					g.P("      ", varName, " = []byte(\"[\" + strings.Join(_parts, \",\") + \"]\")")
					g.P("    }")
				}
			}
		}

		// chainAccept decides which fields go into the chain table.
		// For PII-backed messages: skip PK, PII, and references fields (those live in PII).
		// For chain-only messages: skip only the chain identifier key itself (it IS the key,
		// not a field_value row); references fields have no PII table to live in, so they
		// go into chain too.
		var chainAccept func(*protogen.Field, SdmOptions) bool
		if chainOnly {
			chainAccept = func(field *protogen.Field, opts SdmOptions) bool {
				return !opts.ChainIdentifierKey
			}
		} else {
			chainAccept = func(field *protogen.Field, opts SdmOptions) bool {
				return !opts.PrimaryKey && !opts.Pii && opts.References == ""
			}
		}

		emitPiiStruct := func() {
			g.P("    pii := ", modelName, "Pii{")
			for _, field := range msg.Fields {
				opts := getFieldOptions(field)
				if !(opts.Pii || opts.PrimaryKey || opts.References != "") {
					continue
				}
				if opts.AutoIncrement {
					continue
				}
				switch {
				case isProtoTimestamp(field):
					// google.protobuf.Timestamp → time.Time via AsTime().
					// AsTime() is nil-safe (returns zero time if the proto
					// pointer is nil), so no explicit nil-check needed.
					g.P("      ", field.GoName, ": model.", field.GoName, ".AsTime(),")
				case needsRepeatedProtojsonMarshal(field):
					// repeated *Message — pass through; protojsonArray
					// serializer marshals on Value, decodes on Scan.
					g.P("      ", field.GoName, ": model.", field.GoName, ",")
				case field.Desc.IsList() && field.Desc.Kind() != protoreflect.MessageKind:
					// repeated scalar → cast []string to pq.StringArray.
					g.P("      ", field.GoName, ": pq.StringArray(model.", field.GoName, "),")
				case needsProtojsonMarshal(field):
					g.P("      ", field.GoName, ": model.", field.GoName, ",")
				case opts.Json:
					g.P("      ", field.GoName, ": datatypes.JSON(model.", field.GoName, "),")
				default:
					g.P("      ", field.GoName, ": model.", field.GoName, ",")
				}
			}
			// Actor column. Set on every INSERT; not in the conflict-UPDATE
			// assignment set (see updatableSqlCols) so the original creator is
			// preserved across upserts. The per-update actor lives in
			// audit_pii_<name>s.changed_by, written by the AFTER UPDATE trigger
			// from the same `sdm.actor` session variable.
			g.P("      CreatedBy: _actor,")
			g.P("    }")
		}

		// emitChainEntries writes chain rows for every chain-stored field, but
		// only when the value differs from the latest version already stored
		// for (key, field_name). Chain is a history of CHANGES, not a history
		// of saves — repeated saves with the same value produce no new rows.
		//
		// Loads all latest values in one DISTINCT ON query, then compares per
		// field. The comparison is on the exact TEXT form that would be
		// written (Format(time.RFC3339Nano), JSON bytes, pgArrayLiteral, etc.)
		// so the comparison matches byte-for-byte what's in the table.
		emitChainEntries := func() {
			chainTable := "chain_" + strings.ToLower(modelName) + "s"
			g.P("    compositeKey := ", compositeKeyExpr)
			g.P("    var _latestRows []struct {")
			g.P("      FieldName  string")
			g.P("      FieldValue string")
			g.P("    }")
			g.P("    if err := tx.Raw(\"SELECT DISTINCT ON (field_name) field_name, field_value FROM ", chainTable, " WHERE key = ? ORDER BY field_name, version DESC\", compositeKey).Scan(&_latestRows).Error; err != nil { return err }")
			g.P("    _latest := make(map[string]string, len(_latestRows))")
			g.P("    for _, _r := range _latestRows { _latest[_r.FieldName] = _r.FieldValue }")
			emitMessageJsonMarshals(chainAccept)
			for _, field := range msg.Fields {
				opts := getFieldOptions(field)

				// Decide whether the main chain row for this field should be written.
				// Note this is independent from the Hashed sidecar below: a PII
				// field can still produce a `hashed_X` chain row even though its
				// main value lives only in the PII table.
				emitMain := true
				if chainOnly && opts.ChainIdentifierKey {
					emitMain = false
				}
				if !chainOnly {
					if opts.PrimaryKey || opts.References != "" || opts.Pii {
						emitMain = false
					}
				}

				if emitMain {
					var fieldValueExpr string
					switch {
					case isProtoTimestamp(field):
						// google.protobuf.Timestamp → RFC3339Nano text. The view
						// casts the chain TEXT back to ::timestamptz, which
						// time.Time scans via lib/pq.
						fieldValueExpr = fmt.Sprintf("model.%s.AsTime().Format(time.RFC3339Nano)", field.GoName)
					case needsProtojsonMarshal(field):
						// Singular proto.Message → pre-marshaled by emitMessageJsonMarshals.
						fieldValueExpr = fmt.Sprintf("string(%s)", jsonVarName(field))
					case needsRepeatedProtojsonMarshal(field):
						// Repeated proto.Message → JSON array pre-built by emitMessageJsonMarshals.
						fieldValueExpr = fmt.Sprintf("string(%s)", jsonVarName(field))
					case opts.Json:
						fieldValueExpr = fmt.Sprintf("string(model.%s)", field.GoName)
					case field.Desc.IsList():
						// Repeated scalar ([]string) → PostgreSQL array literal.
						fieldValueExpr = fmt.Sprintf("pgArrayLiteral(model.%s)", field.GoName)
					default:
						fieldValueExpr = fmt.Sprintf("fmt.Sprintf(\"%%v\", model.%s)", field.GoName)
					}
					colName := string(field.Desc.Name())
					g.P("    {")
					g.P("      _v := ", fieldValueExpr)
					g.P("      if _prev, _ok := _latest[\"", colName, "\"]; !_ok || _prev != _v {")
					g.P("        if err := tx.Create(&", modelName, "Chain{")
					g.P("          Key:        compositeKey,")
					g.P("          FieldName:  \"", colName, "\",")
					g.P("          FieldValue: _v,")
					g.P("          CreatedBy:  _actor,")
					g.P("        }).Error; err != nil { return err }")
					g.P("      }")
					g.P("    }")
				}

				if opts.Hashed {
					hashedName := "hashed_" + string(field.Desc.Name())
					g.P("    {")
					g.P("      // Hash ", field.GoName)
					g.P("      _h := sha256.Sum256([]byte(fmt.Sprintf(\"%v\", model.", field.GoName, ")))")
					g.P("      _hv := hex.EncodeToString(_h[:])")
					g.P("      if _prev, _ok := _latest[\"", hashedName, "\"]; !_ok || _prev != _hv {")
					g.P("        if err := tx.Create(&", modelName, "Chain{")
					g.P("          Key:        compositeKey,")
					g.P("          FieldName:  \"", hashedName, "\",")
					g.P("          FieldValue: _hv,")
					g.P("          CreatedBy:  _actor,")
					g.P("        }).Error; err != nil { return err }")
					g.P("      }")
					g.P("    }")
				}
			}
		}

		emitAutoIncrementCopyback := func() {
			for _, field := range msg.Fields {
				opts := getFieldOptions(field)
				if opts.AutoIncrement {
					g.P("    model.", field.GoName, " = pii.", field.GoName, " // copy DB-generated value back to model")
				}
			}
		}

		// emitResolveActor binds the ctx-carried actor identifier to the
		// local `_actor` variable inside the transaction lambda. The
		// variable is always defined (empty string when no actor is on the
		// ctx) so downstream emit blocks (emitPiiStruct, emitChainEntries)
		// can reference it unconditionally.
		emitResolveActor := func() {
			g.P("    _actor := actorFromContext(ctx)")
		}

		// emitInstallActorSessionVar installs `_actor` into the `sdm.actor`
		// Postgres session variable for the current transaction
		// (`is_local=true`). The audit_pii_<name>s trigger reads the same
		// variable. Skipped when _actor is empty. Requires emitResolveActor
		// to have run first. Becomes a no-op when audit tables are disabled
		// (Options.CreateAuditTables=false) — without a trigger to read the
		// variable, setting it is pure waste.
		emitInstallActorSessionVar := func() {
			if !opts.CreateAuditTables {
				return
			}
			g.P("    if _actor != \"\" {")
			g.P("      if err := tx.Exec(\"SELECT set_config('sdm.actor', ?, true)\", _actor).Error; err != nil { return err }")
			g.P("    }")
		}

		// ── Save (PII-backed only) ────────────────────────────────────────────
		// Strict INSERT of the PII row; errors with the driver-native error on
		// primary-key / unique conflict. Does NOT touch the chain table — use
		// SaveAll for upsert + chain, or SaveChain for chain-only writes.
		if !chainOnly {
			g.P("func (r *", modelName, "Repo) Save(ctx context.Context, model *", modelName, ") error {")
			g.P("  return r.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {")
			emitResolveActor()
			emitInstallActorSessionVar()
			emitPiiStruct()
			g.P("    if err := tx.Create(&pii).Error; err != nil { return err }")
			emitAutoIncrementCopyback()
			g.P("    return nil")
			g.P("  })")
			g.P("}")
			g.P()
		}

		// ── SaveChain ─────────────────────────────────────────────────────────
		// Appends new chain versions per chain-stored field — but only when the
		// value differs from the latest stored version. Repeated calls with
		// unchanged data are no-ops.
		g.P("func (r *", modelName, "Repo) SaveChain(ctx context.Context, model *", modelName, ") error {")
		g.P("  return r.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {")
		emitResolveActor()
		g.P("    // Save Chain Fields (skip-if-unchanged per field)")
		emitChainEntries()
		g.P("    return nil")
		g.P("  })")
		g.P("}")
		g.P()

		// ── SaveAll ───────────────────────────────────────────────────────────
		// Upserts the PII row (INSERT, or on conflict UPDATE the mutable
		// columns) and, when withChain=true, appends new chain versions for
		// every chain-stored field whose value changed. Conflict target is the
		// chain identifier key (PK, or chain_identifier_key + unique).
		//
		// For chain-only messages the PII step is a no-op; behavior collapses
		// to SaveChain when withChain=true, or a no-op when withChain=false.
		g.P("func (r *", modelName, "Repo) SaveAll(ctx context.Context, model *", modelName, ", withChain bool) error {")
		g.P("  return r.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {")
		emitResolveActor()
		if !chainOnly {
			updatableCols := updatableSqlCols(msg)
			conflictCol := string(keyFields[0].Desc.Name())
			emitInstallActorSessionVar()
			emitPiiStruct()
			g.P("    if err := tx.Clauses(clause.OnConflict{")
			g.P("      Columns:   []clause.Column{{Name: \"", conflictCol, "\"}},")
			g.P("      DoUpdates: clause.AssignmentColumns([]string{\"", strings.Join(updatableCols, "\", \""), "\"}),")
			g.P("    }).Create(&pii).Error; err != nil { return err }")
			emitAutoIncrementCopyback()
			g.P()
		}
		g.P("    if !withChain { return nil }")
		g.P("    // Save Chain Fields (skip-if-unchanged per field)")
		emitChainEntries()
		g.P("    return nil")
		g.P("  })")
		g.P("}")
		g.P()

		// ── Fetch / FetchBy* / Exists / ExistsBy* ────────────────────────────
		// For chain-only messages the identifier is the chain key field, not a PK.
		// For PII-backed messages the identifier is the PK field(s).
		if chainOnly {
			// Single key field — chain_identifier_key is always the lookup handle.
			keyField := keyFields[0]
			paramName := strings.ToLower(keyField.GoName[:1]) + keyField.GoName[1:]
			paramType := goTypeForField(keyField)
			colName := string(keyField.Desc.Name())

			// Fetch queries the view by the chain key column (materialized as keys.key AS ptt_id).
			g.P("func (r *", modelName, "Repo) Fetch(ctx context.Context, ", paramName, " ", paramType, ") (*", modelName, "View, error) {")
			g.P("  var view ", modelName, "View")
			g.P("  if err := r.db.WithContext(ctx).Where(\"", colName, " = ?\", ", paramName, ").First(&view).Error; err != nil {")
			g.P("    return nil, err")
			g.P("  }")
			g.P("  return &view, nil")
			g.P("}")
			g.P()

			// Exists queries the chain table directly — no PII table available.
			g.P("func (r *", modelName, "Repo) Exists(ctx context.Context, ", paramName, " ", paramType, ") (bool, error) {")
			g.P("  var count int64")
			g.P("  if err := r.db.WithContext(ctx).Model(&", modelName, "Chain{}).Where(\"key = ?\", ", paramName, ").Count(&count).Error; err != nil {")
			g.P("    return false, err")
			g.P("  }")
			g.P("  return count > 0, nil")
			g.P("}")
			g.P()

			// FetchBy* for unique non-key fields.
			for _, field := range msg.Fields {
				opts := getFieldOptions(field)
				if !opts.Unique || opts.ChainIdentifierKey {
					continue
				}
				fp := strings.ToLower(field.GoName[:1]) + field.GoName[1:]
				g.P("func (r *", modelName, "Repo) FetchBy", field.GoName,
					"(ctx context.Context, ", fp, " ", goTypeForField(field), ") (*", modelName, "View, error) {")
				g.P("  var view ", modelName, "View")
				g.P("  if err := r.db.WithContext(ctx).Where(\"", field.Desc.Name(), " = ?\", ", fp, ").First(&view).Error; err != nil {")
				g.P("    return nil, err")
				g.P("  }")
				g.P("  return &view, nil")
				g.P("}")
				g.P()
			}
		} else {
			// PII-backed path — Fetch reads the view, Exists counts pii_X. Both
			// emit an explicit `deleted_at IS NULL` filter for clarity (PII and
			// View structs also carry gorm.DeletedAt which adds the same scope
			// automatically — the explicit clause makes the generated SQL
			// obvious to readers).
			const notDeleted = `.Where("deleted_at IS NULL")`

			var pkFields []*protogen.Field
			for _, field := range msg.Fields {
				if getFieldOptions(field).PrimaryKey {
					pkFields = append(pkFields, field)
				}
			}

			fetchParams := make([]string, len(pkFields))
			whereExprs := make([]string, len(pkFields))
			whereArgs := make([]string, len(pkFields))
			for i, f := range pkFields {
				paramName := strings.ToLower(f.GoName[:1]) + f.GoName[1:]
				fetchParams[i] = paramName + " " + goTypeForField(f)
				whereExprs[i] = string(f.Desc.Name()) + " = ?"
				whereArgs[i] = paramName
			}

			g.P("func (r *", modelName, "Repo) Fetch(ctx context.Context, ",
				strings.Join(fetchParams, ", "), ") (*", modelName, "View, error) {")
			g.P("  var view ", modelName, "View")
			g.P("  if err := r.db.WithContext(ctx).Where(\"", strings.Join(whereExprs, " AND "), "\", ",
				strings.Join(whereArgs, ", "), ")", notDeleted, ".First(&view).Error; err != nil {")
			g.P("    return nil, err")
			g.P("  }")
			g.P("  return &view, nil")
			g.P("}")
			g.P()

			for _, field := range msg.Fields {
				opts := getFieldOptions(field)
				if !opts.Unique {
					continue
				}
				paramName := strings.ToLower(field.GoName[:1]) + field.GoName[1:]
				g.P("func (r *", modelName, "Repo) FetchBy", field.GoName,
					"(ctx context.Context, ", paramName, " ", goTypeForField(field), ") (*", modelName, "View, error) {")
				g.P("  var view ", modelName, "View")
				g.P("  if err := r.db.WithContext(ctx).Where(\"", field.Desc.Name(), " = ?\", ", paramName, ")", notDeleted, ".First(&view).Error; err != nil {")
				g.P("    return nil, err")
				g.P("  }")
				g.P("  return &view, nil")
				g.P("}")
				g.P()
			}

			if len(pkFields) > 1 {
				for _, field := range pkFields {
					paramName := strings.ToLower(field.GoName[:1]) + field.GoName[1:]
					g.P("func (r *", modelName, "Repo) FetchBy", field.GoName,
						"(ctx context.Context, ", paramName, " ", goTypeForField(field), ") ([]", modelName, "View, error) {")
					g.P("  var views []", modelName, "View")
					g.P("  if err := r.db.WithContext(ctx).Where(\"", field.Desc.Name(), " = ?\", ", paramName, ")", notDeleted, ".Find(&views).Error; err != nil {")
					g.P("    return nil, err")
					g.P("  }")
					g.P("  return views, nil")
					g.P("}")
					g.P()
				}
			}

			g.P("func (r *", modelName, "Repo) Exists(ctx context.Context, ",
				strings.Join(fetchParams, ", "), ") (bool, error) {")
			g.P("  var count int64")
			g.P("  if err := r.db.WithContext(ctx).Model(&", modelName, "Pii{}).Where(\"",
				strings.Join(whereExprs, " AND "), "\", ", strings.Join(whereArgs, ", "), ")", notDeleted, ".Count(&count).Error; err != nil {")
			g.P("    return false, err")
			g.P("  }")
			g.P("  return count > 0, nil")
			g.P("}")
			g.P()

			for _, field := range msg.Fields {
				opts := getFieldOptions(field)
				if !opts.Unique {
					continue
				}
				paramName := strings.ToLower(field.GoName[:1]) + field.GoName[1:]
				g.P("func (r *", modelName, "Repo) ExistsBy", field.GoName,
					"(ctx context.Context, ", paramName, " ", goTypeForField(field), ") (bool, error) {")
				g.P("  var count int64")
				g.P("  if err := r.db.WithContext(ctx).Model(&", modelName, "Pii{}).Where(\"",
					field.Desc.Name(), " = ?\", ", paramName, ")", notDeleted, ".Count(&count).Error; err != nil {")
				g.P("    return false, err")
				g.P("  }")
				g.P("  return count > 0, nil")
				g.P("}")
				g.P()
			}

			// ── AuditLog (PII-backed only) ───────────────────────────────────
			// Returns the audit_pii_<name>s history for a single record,
			// chronologically (oldest first). Each row is a snapshot of the
			// PII row immediately BEFORE an UPDATE or DELETE. Empty slice if
			// the record was inserted but never modified.
			//
			// Param signature mirrors Fetch's — takes the PK fields. The audit
			// table's ref_id is the PK joined with ':' for composite PKs.
			// Skipped when audit tables are disabled (no <Name>PiiAudit struct
			// or audit_pii_<name>s table exists in that mode).
			if opts.CreateAuditTables {
				var refIDExpr string
				if len(whereArgs) == 1 {
					refIDExpr = fmt.Sprintf("fmt.Sprintf(\"%%v\", %s)", whereArgs[0])
				} else {
					fmtParts := make([]string, len(whereArgs))
					for i := range whereArgs {
						fmtParts[i] = "%v"
					}
					refIDExpr = fmt.Sprintf("fmt.Sprintf(\"%s\", %s)",
						strings.Join(fmtParts, ":"), strings.Join(whereArgs, ", "))
				}
				g.P("func (r *", modelName, "Repo) AuditLog(ctx context.Context, ",
					strings.Join(fetchParams, ", "), ") ([]", modelName, "PiiAudit, error) {")
				g.P("  var rows []", modelName, "PiiAudit")
				g.P("  if err := r.db.WithContext(ctx).")
				g.P("    Where(\"ref_id = ?\", ", refIDExpr, ").")
				g.P("    Order(\"changed_at ASC, id ASC\").")
				g.P("    Find(&rows).Error; err != nil {")
				g.P("    return nil, err")
				g.P("  }")
				g.P("  return rows, nil")
				g.P("}")
				g.P()
			}
		}

		// ── ChangeLog ────────────────────────────────────────────────────────
		// Returns the full per-field version history for a single record,
		// grouped by chain field_name then version. Soft-deleted PII rows do
		// NOT mask chain history — chain entries persist independently and
		// remain queryable. Returns gorm.ErrRecordNotFound if the key has no
		// chain rows at all.
		//
		// Param signature mirrors Save's compositeKey construction: takes the
		// chain identifier key field(s) and composes the lookup key the same
		// way Save does, so callers hand it whatever they originally Saved.
		{
			chParams := make([]string, len(keyFields))
			chArgs := make([]string, len(keyFields))
			for i, f := range keyFields {
				pn := strings.ToLower(f.GoName[:1]) + f.GoName[1:]
				chParams[i] = pn + " " + goTypeForField(f)
				chArgs[i] = pn
			}
			var chainKeyExpr string
			if len(keyFields) == 1 {
				chainKeyExpr = fmt.Sprintf("fmt.Sprintf(\"%%v\", %s)", chArgs[0])
			} else {
				fmtParts := make([]string, len(keyFields))
				for i := range keyFields {
					fmtParts[i] = "%v"
				}
				chainKeyExpr = fmt.Sprintf("fmt.Sprintf(\"%s\", %s)",
					strings.Join(fmtParts, ":"), strings.Join(chArgs, ", "))
			}

			g.P("func (r *", modelName, "Repo) ChangeLog(ctx context.Context, ",
				strings.Join(chParams, ", "), ") (ChangeLog, error) {")
			g.P("  var rows []", modelName, "Chain")
			g.P("  if err := r.db.WithContext(ctx).")
			g.P("    Where(\"key = ?\", ", chainKeyExpr, ").")
			g.P("    Order(\"field_name, version\").")
			g.P("    Find(&rows).Error; err != nil {")
			g.P("    return nil, err")
			g.P("  }")
			g.P("  if len(rows) == 0 { return nil, gorm.ErrRecordNotFound }")
			g.P("  log := make(ChangeLog)")
			g.P("  for _, row := range rows {")
			g.P("    if _, ok := log[row.FieldName]; !ok {")
			g.P("      log[row.FieldName] = make(map[int64]ChangeLogEntry)")
			g.P("    }")
			g.P("    log[row.FieldName][row.Version] = ChangeLogEntry{")
			g.P("      Value:     row.FieldValue,")
			g.P("      Timestamp: row.CreatedAt,")
			g.P("    }")
			g.P("  }")
			g.P("  return log, nil")
			g.P("}")
			g.P()
		}
	}
}

// parseReference splits a "MessageName.field_name" references annotation into
// the PII table name and column name used in SQL FK constraints.
func parseReference(ref string) (table, column string) {
	parts := strings.SplitN(ref, ".", 2)
	if len(parts) != 2 {
		return "", ""
	}
	return "pii_" + strings.ToLower(parts[0]) + "s", parts[1]
}

type SdmOptions struct {
	PrimaryKey         bool
	ChainIdentifierKey bool // if set, this field is used as the chain key instead of the PK
	Pii                bool
	QueryIndex         bool
	Hashed             bool
	Unique             bool
	AutoIncrement      bool
	Json               bool // stored as Postgres JSONB and Go datatypes.JSON
	References         string
}

func getFieldOptions(field *protogen.Field) SdmOptions {
	opts := field.Desc.Options()

	getBool := func(ext protoreflect.ExtensionType) bool {
		if proto.HasExtension(opts, ext) {
			return proto.GetExtension(opts, ext).(bool)
		}
		return false
	}

	getString := func(ext protoreflect.ExtensionType) string {
		if proto.HasExtension(opts, ext) {
			return proto.GetExtension(opts, ext).(string)
		}
		return ""
	}

	return SdmOptions{
		PrimaryKey:         getBool(sdm.E_PrimaryKey),
		ChainIdentifierKey: getBool(sdm.E_ChainIdentifierKey),
		Pii:                getBool(sdm.E_Pii),
		QueryIndex:         getBool(sdm.E_QueryIndex),
		Hashed:             getBool(sdm.E_Hashed),
		Unique:             getBool(sdm.E_Unique),
		AutoIncrement:      getBool(sdm.E_AutoIncrement),
		Json:               getBool(sdm.E_Json),
		References:         getString(sdm.E_References),
	}
}

// isProtoTimestamp reports whether a field is the well-known
// google.protobuf.Timestamp message. We special-case it so the Go side uses
// time.Time (not *Timestamppb / JSON bytes) and the DB column is a real
// `timestamp with time zone`, not JSONB.
func isProtoTimestamp(field *protogen.Field) bool {
	if field.Desc.Kind() != protoreflect.MessageKind {
		return false
	}
	if field.Message == nil {
		return false
	}
	return field.Message.Desc.FullName() == "google.protobuf.Timestamp"
}

// isJsonStored reports whether a field is materialized as JSON: either marked
// with (sdm.json)=true on a string field, or any message-kind field (which has
// no scalar SQL mapping and is always serialized as JSON). google.protobuf.Timestamp
// is excluded — it has a first-class SQL mapping (timestamptz).
func isJsonStored(field *protogen.Field, opts SdmOptions) bool {
	if isProtoTimestamp(field) {
		return false
	}
	return opts.Json || field.Desc.Kind() == protoreflect.MessageKind
}

// needsProtojsonMarshal reports whether a singular (non-list) message-kind field
// requires protojson.Marshal. Repeated message fields are handled separately by
// needsRepeatedProtojsonMarshal — they are slices, not proto.Message values.
// google.protobuf.Timestamp is excluded — it maps to time.Time via .AsTime().
func needsProtojsonMarshal(field *protogen.Field) bool {
	if isProtoTimestamp(field) {
		return false
	}
	return field.Desc.Kind() == protoreflect.MessageKind && !field.Desc.IsList()
}

// needsRepeatedProtojsonMarshal reports whether a repeated message-kind field
// requires element-wise protojson marshaling into a JSON array string.
// google.protobuf.Timestamp is excluded (repeated timestamps unsupported today).
func needsRepeatedProtojsonMarshal(field *protogen.Field) bool {
	if isProtoTimestamp(field) {
		return false
	}
	return field.Desc.Kind() == protoreflect.MessageKind && field.Desc.IsList()
}

// jsonVarName produces the local variable name used to hold the marshaled JSON
// bytes for a message-kind field, e.g. field.GoName=Amount → "amountJSON".
func jsonVarName(field *protogen.Field) string {
	return strings.ToLower(field.GoName[:1]) + field.GoName[1:] + "JSON"
}

// goTypeForField maps proto field kinds to Go types.
// Enum fields map to their Go type name (int32 alias) — NOT string.
// The View struct stores enums as string (chain field_value); the PII struct
// and proto model use the typed enum. goTypeForField is used for PII structs,
// proto model fields, and repo parameters — all of which want the typed enum.
func goTypeForField(field *protogen.Field) string {
	// google.protobuf.Timestamp → time.Time (not *Timestamppb).
	// Conversions happen at the model boundary via .AsTime() in Save.
	if isProtoTimestamp(field) {
		return "time.Time"
	}
	if field.Desc.Kind() == protoreflect.MessageKind {
		if field.Desc.IsList() {
			return "[]*" + field.Message.GoIdent.GoName
		}
		return "*" + field.Message.GoIdent.GoName
	}
	if field.Desc.Kind() == protoreflect.EnumKind {
		return field.Enum.GoIdent.GoName
	}
	if getFieldOptions(field).Json {
		return "datatypes.JSON"
	}
	base := func() string {
		switch field.Desc.Kind() {
		case protoreflect.StringKind:
			return "string"
		case protoreflect.Int64Kind, protoreflect.Int32Kind:
			return "int64"
		default:
			return "string"
		}
	}()
	if field.Desc.IsList() {
		return "[]" + base
	}
	return base
}

// goTypeForViewField is goTypeForField for View struct fields.
// Enum fields in the View are stored as string (chain field_value is TEXT),
// so the GORM scan target must be string. Everything else delegates to goTypeForField.
func goTypeForViewField(field *protogen.Field) string {
	if field.Desc.Kind() == protoreflect.EnumKind {
		return "string"
	}
	return goTypeForField(field)
}

// sqlTypeForField emits BIGSERIAL for auto_increment fields, TIMESTAMP WITH
// TIME ZONE for google.protobuf.Timestamp, JSONB for other json-stored fields,
// TEXT/BIGINT otherwise.
func sqlTypeForField(field *protogen.Field, opts SdmOptions) string {
	if opts.AutoIncrement {
		return "BIGSERIAL"
	}
	if isProtoTimestamp(field) {
		return "TIMESTAMP WITH TIME ZONE"
	}
	if isJsonStored(field, opts) {
		// Repeated messages and any (sdm.json)=true field — including
		// `repeated MessageType` in PII — store as a single JSONB column
		// (a JSON array of objects for the slice case).
		return "JSONB"
	}
	base := func() string {
		switch field.Desc.Kind() {
		case protoreflect.StringKind:
			return "TEXT"
		case protoreflect.Int64Kind, protoreflect.Int32Kind:
			return "BIGINT"
		default:
			return "TEXT"
		}
	}()
	if field.Desc.IsList() {
		// `repeated string` / `repeated intN` in PII → native Postgres array.
		return base + "[]"
	}
	return base
}

// fileHasStringJsonField reports whether any string field is annotated with
// (sdm.json)=true.
func fileHasStringJsonField(file *protogen.File) bool {
	for _, msg := range file.Messages {
		if !isSdmRecord(msg) {
			continue
		}
		for _, field := range msg.Fields {
			opts := getFieldOptions(field)
			if opts.Json && field.Desc.Kind() == protoreflect.StringKind {
				return true
			}
		}
	}
	return false
}

// fileHasMessageJsonField reports whether any field is a nested proto message
// on a recorded message — drives the protojson serializer emission in helpers.
func fileHasMessageJsonField(file *protogen.File) bool {
	for _, msg := range file.Messages {
		if !isSdmRecord(msg) {
			continue
		}
		for _, field := range msg.Fields {
			if needsProtojsonMarshal(field) {
				return true
			}
		}
	}
	return false
}

// fileHasChainMessageField reports whether any chain-stored (non-PII, non-PK)
// field is a nested proto message.
func fileHasChainMessageField(file *protogen.File) bool {
	for _, msg := range file.Messages {
		if !isSdmRecord(msg) {
			continue
		}
		for _, field := range msg.Fields {
			if !needsProtojsonMarshal(field) {
				continue
			}
			opts := getFieldOptions(field)
			if !opts.Pii && !opts.PrimaryKey && opts.References == "" {
				return true
			}
		}
	}
	return false
}

// fileHasRepeatedMessageField reports whether any chain-stored field is a
// repeated message — drives the "strings" import in the repo file for the
// strings.Join call in the element-wise JSON array marshaling loop.
func fileHasRepeatedMessageField(file *protogen.File) bool {
	for _, msg := range file.Messages {
		if !isSdmRecord(msg) {
			continue
		}
		for _, field := range msg.Fields {
			if needsRepeatedProtojsonMarshal(field) {
				opts := getFieldOptions(field)
				if chainAcceptDefault(opts) {
					return true
				}
			}
		}
	}
	return false
}

// updatableSqlCols returns the SQL column names that Upsert/Update mutate on
// the PII table. Excludes: PK, auto_increment, chain_identifier_key (the
// natural lookup key is immutable), and audit columns the DB manages. Always
// appends "updated_at" so callers can rebump it on conflict. "created_at"
// and "created_by" are intentionally NOT in the update set — they're
// preserved from the original insert across upserts. There's no
// "updated_by" column; per-update actor lives in audit_pii_<name>s.
func updatableSqlCols(msg *protogen.Message) []string {
	var cols []string
	for _, f := range updatableGoFields(msg) {
		cols = append(cols, string(f.Desc.Name()))
	}
	cols = append(cols, "updated_at")
	return cols
}

// updatableGoFields returns the proto fields whose values flow into the
// Update/Upsert PII struct. Mirrors updatableSqlCols, but as *protogen.Fields
// so callers can emit `<GoName>: model.<GoName>`.
func updatableGoFields(msg *protogen.Message) []*protogen.Field {
	var fields []*protogen.Field
	for _, f := range msg.Fields {
		opts := getFieldOptions(f)
		if opts.PrimaryKey || opts.AutoIncrement || opts.ChainIdentifierKey {
			continue
		}
		if !(opts.Pii || opts.QueryIndex || opts.References != "") {
			continue
		}
		fields = append(fields, f)
	}
	return fields
}

// fileHasTimestampField reports whether any field on any recorded message in
// the file is google.protobuf.Timestamp — regardless of PII vs chain placement.
// Drives the timestamppb import in the model file for AsBaseModel.
func fileHasTimestampField(file *protogen.File) bool {
	for _, msg := range file.Messages {
		if !isSdmRecord(msg) {
			continue
		}
		for _, field := range msg.Fields {
			if isProtoTimestamp(field) {
				return true
			}
		}
	}
	return false
}

// fileHasPiiBackedMessage reports whether any recorded message in the file
// has a PII table (i.e. is not chain-only). PII-backed messages generate the
// PiiAudit struct (which uses datatypes.JSON), so the model file's
// `gorm.io/datatypes` import must be present.
func fileHasPiiBackedMessage(file *protogen.File) bool {
	for _, msg := range file.Messages {
		if !isSdmRecord(msg) {
			continue
		}
		if !isChainOnly(msg) {
			return true
		}
	}
	return false
}
// fileHasChainRepeatedMessageField reports whether any chain-stored repeated
// message field exists on a recorded message. PII-stored repeated messages
// are excluded — those go through the protojsonArray serializer in
// sdm_helpers.go, not the repo's chain marshal loop.
func fileHasChainRepeatedMessageField(file *protogen.File) bool {
	for _, msg := range file.Messages {
		if !isSdmRecord(msg) {
			continue
		}
		chainOnly := isChainOnly(msg)
		for _, field := range msg.Fields {
			if !needsRepeatedProtojsonMarshal(field) {
				continue
			}
			opts := getFieldOptions(field)
			if chainOnly {
				if !opts.ChainIdentifierKey {
					return true
				}
			} else {
				if !opts.PrimaryKey && !opts.Pii && opts.References == "" {
					return true
				}
			}
		}
	}
	return false
}

// fileHasPiiRepeatedScalarField reports whether any PII-stored repeated scalar
// field exists on a recorded message. Drives the `github.com/lib/pq` import
// in the generated repo for the `pq.StringArray(model.X)` cast in the PII
// struct literal.
func fileHasPiiRepeatedScalarField(file *protogen.File) bool {
	for _, msg := range file.Messages {
		if !isSdmRecord(msg) {
			continue
		}
		for _, field := range msg.Fields {
			if !field.Desc.IsList() {
				continue
			}
			if field.Desc.Kind() == protoreflect.MessageKind {
				continue
			}
			opts := getFieldOptions(field)
			if opts.Pii || opts.QueryIndex || opts.References != "" {
				return true
			}
		}
	}
	return false
}

// fileHasChainTimestampField reports whether any chain-stored field is a
// google.protobuf.Timestamp. Drives the `time` import in the generated repo
// for the RFC3339Nano chain-serialization expression.
func fileHasChainTimestampField(file *protogen.File) bool {
	for _, msg := range file.Messages {
		if !isSdmRecord(msg) {
			continue
		}
		for _, field := range msg.Fields {
			if !isProtoTimestamp(field) {
				continue
			}
			opts := getFieldOptions(field)
			if !opts.Pii && !opts.PrimaryKey && opts.References == "" {
				return true
			}
		}
	}
	return false
}

// chainAcceptDefault is the chain-only accept predicate used outside a per-message
// closure — it matches the same logic as the chain-only chainAccept inside generateRepo.
func chainAcceptDefault(opts SdmOptions) bool {
	return !opts.ChainIdentifierKey
}

// fileHasPiiStringJsonField reports whether any PII-routed string field is
// annotated (sdm.json)=true.
func fileHasPiiStringJsonField(file *protogen.File) bool {
	for _, msg := range file.Messages {
		if !isSdmRecord(msg) {
			continue
		}
		for _, field := range msg.Fields {
			opts := getFieldOptions(field)
			if opts.Pii && opts.Json && field.Desc.Kind() == protoreflect.StringKind {
				return true
			}
		}
	}
	return false
}

// isSdmRecord reports whether a message should produce SDM tables.
// A record needs at least one primary_key OR chain_identifier_key field.
// Value-type messages (e.g. Money, RequiredDocument) used inline as JSON have
// neither and are skipped to avoid empty tables and broken views.
func isSdmRecord(msg *protogen.Message) bool {
	for _, field := range msg.Fields {
		opts := getFieldOptions(field)
		if opts.PrimaryKey || opts.ChainIdentifierKey {
			return true
		}
	}
	return false
}

// isChainOnly reports whether a message has no PII-routed fields (no primary_key,
// no pii-annotated fields). For chain-only messages the generator skips the PII
// table, SavePii, and FK constraints, and emits a pivot view over chain_* instead
// of a join-based view anchored on pii_*.
func isChainOnly(msg *protogen.Message) bool {
	for _, field := range msg.Fields {
		opts := getFieldOptions(field)
		if opts.PrimaryKey || opts.Pii {
			return false
		}
	}
	return true
}
