package generator

import (
	"path"

	"google.golang.org/protobuf/compiler/protogen"
)

// GenerateHelpers emits sdm_helpers.go exactly once for the whole package.
// Must be called from main.go AFTER the GenerateFile loop — not inside it.
// GenerateFile runs once per proto file; calling this inside it would produce
// one helpers file per message type, causing "pgArrayLiteral redeclared" errors.
func GenerateHelpers(gen *protogen.Plugin, file *protogen.File, opts Options) {
	// Derive the package directory from the file prefix, e.g.:
	//   file.GeneratedFilenamePrefix = "ttf/users"  →  dir = "ttf"
	// Using path.Dir (not filepath) because protogen paths are always forward-slash.
	dir := path.Dir(file.GeneratedFilenamePrefix)
	filename := path.Join(dir, "sdm_helpers.go")
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	needProtojson := packageHasMessageJsonField(gen)
	needProtojsonArray := packageHasRepeatedMessageField(gen)
	needReflectStack := needProtojson || needProtojsonArray
	// encoding/json is used by the array serializer to split the bytes into
	// per-element JSON.RawMessage before per-element protojson.Unmarshal.
	needEncodingJson := needProtojsonArray
	// errors is imported only by ErrPendingDraftExists when the draft
	// workflow is enabled.
	needErrors := opts.ChainDrafts

	g.P("// Code generated by sdm. DO NOT EDIT.")
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	g.P("import (")
	if needEncodingJson {
		g.P(`	"encoding/json"`)
	}
	// `context` is always needed: WithActor / actorFromContext use it.
	g.P(`	"context"`)
	if needErrors {
		g.P(`	"errors"`)
	}
	g.P(`	"strings"`)
	g.P(`	"time"`)
	if needReflectStack {
		g.P(`	"fmt"`)
		g.P(`	"reflect"`)
		g.P(`	"google.golang.org/protobuf/encoding/protojson"`)
		g.P(`	"google.golang.org/protobuf/proto"`)
		g.P(`	"gorm.io/gorm/schema"`)
	}
	g.P(")")
	g.P()
	g.P("// pgArrayLiteral serialises a string slice as a PostgreSQL array literal.")
	g.P("// e.g. []string{\"A\", \"B\"} → \"{A,B}\"")
	g.P("// fmt.Sprintf(\"%v\", slice) produces \"[A B]\" which is NOT valid PostgreSQL —")
	g.P("// this helper produces \"{A,B}\" which survives a ::text[] cast.")
	g.P("func pgArrayLiteral(vals []string) string {")
	g.P(`  return "{" + strings.Join(vals, ",") + "}"`)
	g.P("}")
	g.P()
	g.P("// ChangeLogEntry is a single (version → value, timestamp) row in a ChangeLog.")
	g.P("// Value is the raw chain field_value (TEXT). Numeric / JSON / array fields")
	g.P("// are returned as their stored string form — callers cast as needed.")
	g.P("type ChangeLogEntry struct {")
	g.P("  Value     string    `json:\"value\"`")
	g.P("  Timestamp time.Time `json:\"timestamp\"`")
	g.P("}")
	g.P()
	g.P("// ChangeLog maps field_name → version → entry. Versions are 1-based and")
	g.P("// monotonically increasing per (key, field_name), assigned by the chain")
	g.P("// table's BEFORE INSERT trigger.")
	g.P("type ChangeLog map[string]map[int64]ChangeLogEntry")
	g.P()
	g.P("// actorKey is the context key carrying the actor identifier that")
	g.P("// populates created_by on PII rows, created_by on chain rows, and")
	g.P("// changed_by on audit rows (via the AFTER UPDATE/DELETE trigger).")
	g.P("// Unexported so callers must go through WithActor / actorFromContext.")
	g.P("type actorKey struct{}")
	g.P()
	g.P("// WithActor returns a derived context that propagates the actor")
	g.P("// identifier to any PII mutation made through the generated")
	g.P("// Save / SaveAll / SaveChain methods. Inside the same transaction")
	g.P("// as the write the repo sets the Postgres session variable")
	g.P("// `sdm.actor` from this value (scoping the attribution to that")
	g.P("// transaction) AND assigns it to the created_by column on INSERT.")
	g.P("// The AFTER UPDATE/DELETE trigger reads the same session variable")
	g.P("// to populate audit_pii_<name>s.changed_by. Direct GORM operations")
	g.P("// (db.Exec / db.Delete) that do not pass through Save / SaveAll")
	g.P("// record '' for changed_by.")
	g.P("func WithActor(ctx context.Context, actorID string) context.Context {")
	g.P("  return context.WithValue(ctx, actorKey{}, actorID)")
	g.P("}")
	g.P()
	g.P("// actorFromContext extracts the actor identifier installed by")
	g.P("// WithActor, or \"\" if absent. Used by generated repo methods.")
	g.P("func actorFromContext(ctx context.Context) string {")
	g.P("  if v, ok := ctx.Value(actorKey{}).(string); ok { return v }")
	g.P("  return \"\"")
	g.P("}")
	if opts.ChainDrafts {
		g.P()
		g.P("// ErrPendingDraftExists is returned by Create / Upsert / Update /")
		g.P("// DraftChain when a record already has a DRAFTED chain row for one")
		g.P("// of the fields being staged. The caller's recourse is to commit")
		g.P("// the existing draft (CommitChain) or drop it (DropChain) before")
		g.P("// re-drafting. Match with errors.Is.")
		g.P("var ErrPendingDraftExists = errors.New(\"sdm: pending draft exists for this record; commit or drop the existing draft first\")")
	}
	if needProtojson {
		g.P()
		emitProtojsonSerializer(g)
	}
	if needProtojsonArray {
		g.P()
		emitProtojsonArraySerializer(g)
	}
}

// emitProtojsonSerializer writes a GORM serializer that marshals/unmarshals
// proto messages using protojson, registered as "protojson" in init(). View
// and PII struct fields use it via the tag `serializer:protojson`, so reads
// surface a typed *Message rather than raw JSON bytes and writes accept the
// same typed value (GORM calls Value() to produce JSONB bytes).
func emitProtojsonSerializer(g *protogen.GeneratedFile) {
	g.P("type protojsonSerializer struct{}")
	g.P()
	g.P("func init() {")
	g.P(`	schema.RegisterSerializer("protojson", protojsonSerializer{})`)
	g.P("}")
	g.P()
	g.P("func (protojsonSerializer) Scan(ctx context.Context, field *schema.Field, dst reflect.Value, dbValue interface{}) error {")
	g.P("	if dbValue == nil { return nil }")
	g.P("	var data []byte")
	g.P("	switch v := dbValue.(type) {")
	g.P("	case []byte: data = v")
	g.P("	case string:  data = []byte(v)")
	g.P("	default: return fmt.Errorf(\"protojson: unsupported source type %T for field %s\", dbValue, field.Name)")
	g.P("	}")
	g.P("	if len(data) == 0 { return nil }")
	g.P("	ft := field.FieldType")
	g.P("	if ft.Kind() != reflect.Ptr {")
	g.P("		return fmt.Errorf(\"protojson: field %s must be a pointer to a proto.Message\", field.Name)")
	g.P("	}")
	g.P("	ptr := reflect.New(ft.Elem())")
	g.P("	msg, ok := ptr.Interface().(proto.Message)")
	g.P("	if !ok {")
	g.P("		return fmt.Errorf(\"protojson: field %s does not implement proto.Message\", field.Name)")
	g.P("	}")
	g.P("	if err := protojson.Unmarshal(data, msg); err != nil { return err }")
	g.P("	field.ReflectValueOf(ctx, dst).Set(ptr)")
	g.P("	return nil")
	g.P("}")
	g.P()
	g.P("func (protojsonSerializer) Value(ctx context.Context, field *schema.Field, dst reflect.Value, fieldValue interface{}) (interface{}, error) {")
	g.P("	if fieldValue == nil { return nil, nil }")
	g.P("	v := reflect.ValueOf(fieldValue)")
	g.P("	if v.Kind() == reflect.Ptr && v.IsNil() { return nil, nil }")
	g.P("	msg, ok := fieldValue.(proto.Message)")
	g.P("	if !ok {")
	g.P("		return nil, fmt.Errorf(\"protojson: field %s does not implement proto.Message (got %T)\", field.Name, fieldValue)")
	g.P("	}")
	g.P("	return protojson.Marshal(msg)")
	g.P("}")
}

// emitProtojsonArraySerializer writes a GORM serializer that handles slices of
// proto messages — i.e. `[]*MessageType` fields with the tag
// `serializer:protojsonArray`. The wire format is a JSON array of objects, one
// per element, each canonical protojson. Used by both View and PII when a
// repeated message field is present.
//
// Scan: splits the bytes via encoding/json into []json.RawMessage, then
// protojson.Unmarshals each element into a fresh *Message of the slice's
// element type. Empty / nil input is treated as a nil slice.
//
// Value: walks the slice via reflection, protojson.Marshals each element,
// and joins the bytes as `[a,b,c]`. Nil / empty slice produces `[]` so the
// stored bytes remain valid JSON (the view's `::jsonb` cast would otherwise
// reject an empty string).
func emitProtojsonArraySerializer(g *protogen.GeneratedFile) {
	g.P("type protojsonArraySerializer struct{}")
	g.P()
	g.P("func init() {")
	g.P(`	schema.RegisterSerializer("protojsonArray", protojsonArraySerializer{})`)
	g.P("}")
	g.P()
	g.P("func (protojsonArraySerializer) Scan(ctx context.Context, field *schema.Field, dst reflect.Value, dbValue interface{}) error {")
	g.P("	if dbValue == nil { return nil }")
	g.P("	var data []byte")
	g.P("	switch v := dbValue.(type) {")
	g.P("	case []byte: data = v")
	g.P("	case string:  data = []byte(v)")
	g.P("	default: return fmt.Errorf(\"protojsonArray: unsupported source type %T for field %s\", dbValue, field.Name)")
	g.P("	}")
	g.P("	if len(data) == 0 { return nil }")
	g.P("	ft := field.FieldType")
	g.P("	if ft.Kind() != reflect.Slice {")
	g.P("		return fmt.Errorf(\"protojsonArray: field %s must be a slice\", field.Name)")
	g.P("	}")
	g.P("	elemType := ft.Elem()")
	g.P("	if elemType.Kind() != reflect.Ptr {")
	g.P("		return fmt.Errorf(\"protojsonArray: field %s slice element must be a pointer\", field.Name)")
	g.P("	}")
	g.P("	var raw []json.RawMessage")
	g.P("	if err := json.Unmarshal(data, &raw); err != nil { return err }")
	g.P("	slice := reflect.MakeSlice(ft, 0, len(raw))")
	g.P("	for _, r := range raw {")
	g.P("		ptr := reflect.New(elemType.Elem())")
	g.P("		msg, ok := ptr.Interface().(proto.Message)")
	g.P("		if !ok {")
	g.P("			return fmt.Errorf(\"protojsonArray: field %s element does not implement proto.Message\", field.Name)")
	g.P("		}")
	g.P("		if err := protojson.Unmarshal(r, msg); err != nil { return err }")
	g.P("		slice = reflect.Append(slice, ptr)")
	g.P("	}")
	g.P("	field.ReflectValueOf(ctx, dst).Set(slice)")
	g.P("	return nil")
	g.P("}")
	g.P()
	g.P("func (protojsonArraySerializer) Value(ctx context.Context, field *schema.Field, dst reflect.Value, fieldValue interface{}) (interface{}, error) {")
	g.P("	if fieldValue == nil { return []byte(\"[]\"), nil }")
	g.P("	v := reflect.ValueOf(fieldValue)")
	g.P("	if v.Kind() != reflect.Slice {")
	g.P("		return nil, fmt.Errorf(\"protojsonArray: field %s must be a slice (got %T)\", field.Name, fieldValue)")
	g.P("	}")
	g.P("	if v.Len() == 0 { return []byte(\"[]\"), nil }")
	g.P("	parts := make([]string, 0, v.Len())")
	g.P("	for i := 0; i < v.Len(); i++ {")
	g.P("		elem := v.Index(i).Interface()")
	g.P("		msg, ok := elem.(proto.Message)")
	g.P("		if !ok {")
	g.P("			return nil, fmt.Errorf(\"protojsonArray: field %s element %d does not implement proto.Message (got %T)\", field.Name, i, elem)")
	g.P("		}")
	g.P("		b, err := protojson.Marshal(msg)")
	g.P("		if err != nil { return nil, err }")
	g.P("		parts = append(parts, string(b))")
	g.P("	}")
	g.P("	return []byte(\"[\" + strings.Join(parts, \",\") + \"]\"), nil")
	g.P("}")
}

// packageHasMessageJsonField scans all files this plugin is generating to
// decide whether sdm_helpers.go should emit the protojson serializer + init.
func packageHasMessageJsonField(gen *protogen.Plugin) bool {
	for _, f := range gen.Files {
		if !f.Generate {
			continue
		}
		if fileHasMessageJsonField(f) {
			return true
		}
	}
	return false
}

// packageHasRepeatedMessageField scans all files for any repeated message
// field on a recorded message — drives the protojsonArray serializer emission
// in helpers. Used by both the View `[]*Message` column type and the PII
// `[]*Message` column type.
func packageHasRepeatedMessageField(gen *protogen.Plugin) bool {
	for _, f := range gen.Files {
		if !f.Generate {
			continue
		}
		if fileHasRepeatedMessageField(f) {
			return true
		}
	}
	return false
}
