package generator

import (
	"fmt"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// generateModels emits <prefix>_sdm_model.go — one Pii / Chain / View
// (and optional PiiAudit) Go struct per recorded message, plus the
// EnsureUnique chain probe and AsBaseModel view-to-proto converter.
func generateModels(gen *protogen.Plugin, file *protogen.File, opts Options) {
	filename := file.GeneratedFilenamePrefix + "_sdm_model.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	// Repeated scalar fields — in either View or PII — use pq.StringArray.
	needPq := false
	for _, msg := range file.Messages {
		if !isSdmRecord(msg) {
			continue
		}
		for _, field := range msg.Fields {
			if field.Desc.IsList() && field.Desc.Kind() != protoreflect.MessageKind {
				needPq = true
				break
			}
		}
	}

	// timestamppb is needed by AsBaseModel for Timestamp fields
	// (time.Time → *timestamppb.Timestamp).
	needTimestamppb := fileHasTimestampField(file)

	g.P("// Code generated by sdm. DO NOT EDIT.")
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	// datatypes.JSON is used by string fields annotated (sdm.json)=true AND by
	// every PII-backed message's `<Name>PiiAudit.LastValue` column (jsonb).
	// The audit-table contribution is gated by opts.CreateAuditTables — when
	// audit is off, no PiiAudit struct is emitted so the import isn't needed
	// solely for that.
	needDatatypes := fileHasStringJsonField(file) ||
		(opts.CreateAuditTables && fileHasPiiBackedMessage(file))

	g.P("import (")
	g.P(`	"time"`)
	if needDatatypes {
		g.P(`	"gorm.io/datatypes"`)
	}
	if needPq {
		g.P(`	"github.com/lib/pq"`)
	}
	g.P(`	"gorm.io/gorm"`)
	if needTimestamppb {
		g.P(`	"google.golang.org/protobuf/types/known/timestamppb"`)
	}
	g.P(")")
	g.P()

	for _, msg := range file.Messages {
		if !isSdmRecord(msg) {
			continue // value-type message (e.g. Money) — used inline as JSON, no tables
		}
		generateMessageModels(g, msg, opts)
	}
}

// generateMessageModels emits the Go structs (Pii / Chain / View / PiiAudit)
// and their helper methods (TableName, EnsureUnique, AsBaseModel) for a single
// recorded message.
func generateMessageModels(g *protogen.GeneratedFile, msg *protogen.Message, genOpts Options) {
	modelName := msg.GoIdent.GoName
	chainOnly := isChainOnly(msg)

	// ── PII Table Structure (skipped for chain-only messages) ────────────────
	if !chainOnly {
		g.P("// ", modelName, "Pii is the GORM model for table pii_", strings.ToLower(modelName), "s — the")
		g.P("// storage for fields marked (sdm.pii), plus the primary key, foreign")
		g.P("// keys, and audit columns (CreatedAt / UpdatedAt / DeletedAt / CreatedBy).")
		g.P("// Mutations should flow through the generated Create / Upsert / Update /")
		g.P("// SaveAll methods on ", modelName, "Repo — direct GORM writes bypass chain")
		g.P("// bookkeeping and actor attribution. DeletedAt is gorm.DeletedAt, so")
		g.P("// GORM's soft-delete scope applies automatically.")
		g.P("type ", modelName, "Pii struct {")
		for _, field := range msg.Fields {
			opts := getFieldOptions(field)
			if !(opts.PrimaryKey || opts.Pii || opts.QueryIndex || opts.References != "") {
				continue
			}
			var goType, tag string
			switch {
			case field.Desc.IsList() && field.Desc.Kind() == protoreflect.MessageKind:
				// repeated *MessageType in PII — typed slice with JSONB storage
				// via the protojsonArray serializer.
				goType = "[]*" + field.Message.GoIdent.GoName
				tag = "column:" + string(field.Desc.Name()) + ";type:jsonb;serializer:protojsonArray"
			case field.Desc.IsList():
				// repeated scalar in PII — pq.StringArray maps to text[].
				goType = "pq.StringArray"
				tag = "column:" + string(field.Desc.Name()) + ";type:text[]"
			default:
				goType = goTypeForField(field)
				tag = "column:" + string(field.Desc.Name())
				if opts.PrimaryKey {
					tag += ";primaryKey"
				}
				if opts.Unique {
					tag += ";uniqueIndex"
				}
				if opts.AutoIncrement {
					tag += ";autoIncrement"
				}
				if isJsonStored(field, opts) {
					tag += ";type:jsonb"
				}
				if needsProtojsonMarshal(field) {
					tag += ";serializer:protojson"
				}
			}
			g.P(field.GoName, " ", goType, " `gorm:\"", tag, "\"`")
		}
		// Audit columns — always present on every PII table.
		// DeletedAt uses gorm.DeletedAt so GORM's soft-delete scope applies automatically.
		// CreatedBy captures the actor at INSERT (from sdm.CtxWithActor(ctx, …))
		// and is preserved across upserts. "Who last updated this row" is
		// not stored here — read it from the latest audit_pii_<name>s row,
		// which the AFTER UPDATE trigger writes from the same `sdm.actor`
		// session variable.
		g.P("CreatedAt time.Time `gorm:\"column:created_at\"`")
		g.P("UpdatedAt time.Time `gorm:\"column:updated_at\"`")
		g.P("DeletedAt gorm.DeletedAt `gorm:\"column:deleted_at\"`")
		g.P("CreatedBy string `gorm:\"column:created_by\"`")
		g.P("}")
		g.P()
	}

	// ── Chain Table Structure ─────────────────────────────────────────────────
	// Chain rows are append-only, so the only actor column is CreatedBy
	// (populated from sdm.CtxWithActor(ctx, …) at insert time).
	// When chain-drafts is enabled, each row also carries a Status
	// (DRAFTED / CREATED / DROPPED). New rows are written as DRAFTED by
	// DraftChain and promoted to CREATED by CommitChain or DROPPED by
	// DropChain. Legal transitions are enforced by a BEFORE UPDATE trigger.
	g.P("// ", modelName, "Chain is the GORM model for table chain_", strings.ToLower(modelName), "s — the")
	g.P("// append-only per-field history. Each row records a single")
	g.P("// (key, field_name, version) triple with the value at that version and")
	g.P("// the actor that wrote it. Version is auto-assigned by a BEFORE INSERT")
	g.P("// trigger (1-based, per (key, field_name)). With chain-drafts enabled,")
	g.P("// rows also carry a Status (DRAFTED / CREATED / DROPPED); state")
	g.P("// transitions are guarded by a BEFORE UPDATE trigger.")
	g.P("type ", modelName, "Chain struct {")
	g.P("Key string `gorm:\"primaryKey;column:key\"`")
	g.P("FieldName string `gorm:\"primaryKey;column:field_name\"`")
	g.P("Version int64 `gorm:\"primaryKey;column:version;autoIncrement\"`")
	g.P("TxHash string `gorm:\"column:tx_hash\"`")
	g.P("FieldValue string `gorm:\"column:field_value\"`")
	g.P("CreatedAt time.Time `gorm:\"column:created_at\"`")
	g.P("CreatedBy string `gorm:\"column:created_by\"`")
	if genOpts.ChainDrafts {
		g.P("Status string `gorm:\"column:status\"`")
	}
	g.P("}")
	g.P()

	// ── View Structure ────────────────────────────────────────────────────────
	// repeated scalar fields use pq.StringArray (text[] column).
	// repeated message fields use []*Message via protojsonArray serializer —
	// the underlying column is JSONB (chain TEXT cast to ::jsonb in the view,
	// or PII's native JSONB column) and the serializer decodes per-element.
	g.P("// ", modelName, "View is the read model returned by Fetch / FetchBy*. It joins")
	g.P("// the latest committed value of every chain field with the PII row,")
	g.P("// surfaces hashed_* sidecar columns, and (with chain-drafts enabled)")
	g.P("// exposes HasPendingDrafts to signal that an uncommitted edit exists.")
	g.P("//")
	g.P("// Maps to view ", strings.ToLower(modelName), "s by default; with chain-drafts enabled, the")
	g.P("// repo's Fetch methods route to ", strings.ToLower(modelName), "s_with_drafts when called with")
	g.P("// drafted=true (the overlay shows uncommitted DRAFTED values).")
	g.P("type ", modelName, "View struct {")
	for _, field := range msg.Fields {
		var goType, viewTag string
		if field.Desc.IsList() {
			if field.Desc.Kind() == protoreflect.MessageKind {
				goType = "[]*" + field.Message.GoIdent.GoName
				viewTag = fmt.Sprintf("column:%s;type:jsonb;serializer:protojsonArray", field.Desc.Name())
			} else {
				goType = "pq.StringArray"
				viewTag = fmt.Sprintf("column:%s;type:text[]", field.Desc.Name())
			}
		} else {
			goType = goTypeForViewField(field)
			viewTag = "column:" + string(field.Desc.Name())
			if needsProtojsonMarshal(field) {
				// View column comes from a ::jsonb cast over the chain's TEXT field_value
				// (or directly from the PII JSONB column). The serializer decodes those
				// bytes into a typed *Message on read.
				viewTag += ";serializer:protojson"
			}
		}
		g.P(field.GoName, " ", goType, " `gorm:\"", viewTag, "\"`")

		opts := getFieldOptions(field)
		if opts.Hashed {
			g.P("Hashed", field.GoName, " string `gorm:\"column:hashed_", field.Desc.Name(), "\"`")
		}
	}
	// Audit columns surfaced from the PII table on the view.
	// DeletedAt uses gorm.DeletedAt so GORM's soft-delete scope also applies
	// to view queries (a redundant safety net; read methods also emit an
	// explicit `deleted_at IS NULL` filter for clarity).
	// CreatedBy is the actor at INSERT; "who last updated" is intentionally
	// not exposed here — query audit_pii_<name>s for that.
	// HasPendingDrafts (chain-drafts only) signals whether any chain row
	// for this record is currently DRAFTED — independent of which view
	// (committed vs with-drafts) the caller fetched from.
	g.P("CreatedAt time.Time `gorm:\"column:created_at\"`")
	g.P("UpdatedAt time.Time `gorm:\"column:updated_at\"`")
	g.P("DeletedAt gorm.DeletedAt `gorm:\"column:deleted_at\"`")
	g.P("CreatedBy string `gorm:\"column:created_by\"`")
	g.P("TxHash string `gorm:\"column:tx_hash\"`")
	if genOpts.ChainDrafts {
		g.P("HasPendingDrafts bool `gorm:\"column:has_pending_drafts\"`")
	}
	g.P("}")
	g.P()

	// ── TableName overrides ───────────────────────────────────────────────────
	if !chainOnly {
		g.P("// TableName returns the SQL table name backing ", modelName, "Pii.")
		g.P("func (", modelName, "Pii) TableName() string { return \"pii_", strings.ToLower(modelName), "s\" }")
	}
	g.P("// TableName returns the SQL table name backing ", modelName, "Chain.")
	g.P("func (", modelName, "Chain) TableName() string { return \"chain_", strings.ToLower(modelName), "s\" }")
	g.P("// TableName returns the default (committed-only) view name. With chain-drafts")
	g.P("// enabled, the repo's Fetch methods may route to ", strings.ToLower(modelName), "s_with_drafts via .Table()")
	g.P("// when drafted=true, bypassing this default.")
	g.P("func (", modelName, "View) TableName() string { return \"", strings.ToLower(modelName), "s\" }")
	g.P()

	// ── PII Audit struct ──────────────────────────────────────────────────────
	// Mirror of audit_pii_<name>s. The table + trigger are emitted by
	// generateSQL only for PII-backed messages, so the struct is only emitted
	// here when !chainOnly. Skipped entirely when audit tables are disabled
	// via Options.CreateAuditTables=false.
	if !chainOnly && genOpts.CreateAuditTables {
		g.P("// ", modelName, "PiiAudit is the GORM model for audit_pii_", strings.ToLower(modelName), "s — a per-row")
		g.P("// snapshot taken by the AFTER UPDATE/DELETE trigger immediately BEFORE")
		g.P("// each mutation. LastValue is the full PII row at the moment of capture")
		g.P("// (JSONB). ChangeType is 'UPDATE' or 'DELETE'; INSERTs do not produce")
		g.P("// audit rows. ChangedBy is the actor read from the `sdm.actor` Postgres")
		g.P("// session variable installed by the repo (see sdm.CtxWithActor); direct GORM")
		g.P("// writes that do not pass through the repo record '' there.")
		g.P("type ", modelName, "PiiAudit struct {")
		g.P("  Id         int64          `gorm:\"column:id;primaryKey;autoIncrement\"`")
		g.P("  RefId      string         `gorm:\"column:ref_id\"`")
		g.P("  LastValue  datatypes.JSON `gorm:\"column:last_value;type:jsonb\"`")
		g.P("  ChangeType string         `gorm:\"column:change_type\"`")
		g.P("  ChangedBy  string         `gorm:\"column:changed_by\"`")
		g.P("  ChangedAt  time.Time      `gorm:\"column:changed_at\"`")
		g.P("}")
		g.P()
		g.P("// TableName returns the SQL table name backing ", modelName, "PiiAudit.")
		g.P("func (", modelName, "PiiAudit) TableName() string { return \"audit_pii_", strings.ToLower(modelName), "s\" }")
		g.P()
	}

	// ── EnsureUnique method ───────────────────────────────────────────────────
	g.P("// EnsureUnique reports whether no other chain row has the same")
	g.P("// (FieldName, FieldValue) — a uniqueness probe for callers that want to")
	g.P("// enforce global uniqueness of a specific chain value before staging or")
	g.P("// committing it. Returns false if the query errors.")
	g.P("func (c *", modelName, "Chain) EnsureUnique(tx *gorm.DB) bool {")
	g.P("  var count int64")
	g.P("  err := tx.Model(&", modelName, "Chain{}).Where(\"field_name = ? AND field_value = ?\", c.FieldName, c.FieldValue).Count(&count).Error")
	g.P("  if err != nil {")
	g.P("    return false")
	g.P("  }")
	g.P("  return count == 0")
	g.P("}")
	g.P()

	// ── AsBaseModel ──────────────────────────────────────────────────────────
	// Converts the view row back to the base proto model. Useful for re-saving
	// (View → AsBaseModel → SaveAll). Audit columns (CreatedAt / UpdatedAt /
	// DeletedAt / TxHash) and hashed_* sidecar columns are dropped because they
	// have no counterpart on the base proto model.
	//
	// Per-field conversion:
	//   - scalar              : direct assignment (types match)
	//   - enum                : string → EnumType via EnumType_value map lookup
	//   - *Message            : direct assignment (serializer:protojson already decoded)
	//   - Timestamp           : time.Time → timestamppb.New (skipped if zero)
	//   - (sdm.json)=true str : datatypes.JSON → string
	//   - repeated scalar     : pq.StringArray → []string
	//   - repeated *Message   : direct assignment ([]*Message via protojsonArray serializer)
	g.P("// AsBaseModel converts the view back to a base proto ", modelName, " — useful for")
	g.P("// re-saving (View → AsBaseModel → mutate → Upsert/Update/SaveAll). Audit")
	g.P("// columns (CreatedAt / UpdatedAt / DeletedAt / TxHash / CreatedBy) and")
	g.P("// hashed_* sidecars are not copied; they have no counterpart on the base")
	g.P("// proto. Per-field: Timestamps become *timestamppb.Timestamp (skipped if")
	g.P("// zero), repeated scalars (pq.StringArray) become []string, JSON sidecars")
	g.P("// (datatypes.JSON) become string, and singular/repeated messages are")
	g.P("// passed through (the serializers already decoded them on the View).")
	g.P("func (v *", modelName, "View) AsBaseModel() *", modelName, " {")
	g.P("  base := &", modelName, "{}")
	for _, field := range msg.Fields {
		opts := getFieldOptions(field)
		switch {
		case isProtoTimestamp(field):
			g.P("  if !v.", field.GoName, ".IsZero() {")
			g.P("    base.", field.GoName, " = timestamppb.New(v.", field.GoName, ")")
			g.P("  }")
		case needsProtojsonMarshal(field):
			g.P("  base.", field.GoName, " = v.", field.GoName)
		case needsRepeatedProtojsonMarshal(field):
			// View is now typed []*Message via protojsonArray serializer —
			// direct assignment, no unmarshal needed.
			g.P("  base.", field.GoName, " = v.", field.GoName)
		case opts.Json:
			g.P("  base.", field.GoName, " = string(v.", field.GoName, ")")
		case field.Desc.IsList():
			g.P("  base.", field.GoName, " = []string(v.", field.GoName, ")")
		case field.Desc.Kind() == protoreflect.EnumKind:
			// View stores the enum as a plain string (fmt.Sprintf("%v", enumVal)
			// produces the proto-registered name, e.g. "User_Status_Active").
			// Recover the typed enum via the generated _value map.
			enumType := field.Enum.GoIdent.GoName
			g.P("  base.", field.GoName, " = ", enumType, "(", enumType, "_value[v.", field.GoName, "])")
		default:
			g.P("  base.", field.GoName, " = v.", field.GoName)
		}
	}
	g.P("  return base")
	g.P("}")
	g.P()
}
