package generator

import (
	"fmt"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// generateRepo emits <prefix>_sdm_repo.go — the GORM repository for each
// recorded message: Create / Upsert / Update / SaveAll / DraftChain /
// CommitChain / DropChain mutation methods plus Fetch / FetchBy* / Exists /
// ExistsBy* / AuditLog / ChangeLog read methods. Method surface differs by
// Options (chain-drafts toggles Upsert/Update vs SaveAll, drafted bool on
// Fetch; create-audit-tables gates AuditLog and the session-var install).
func generateRepo(gen *protogen.Plugin, file *protogen.File, opts Options) {
	filename := file.GeneratedFilenamePrefix + "_sdm_repo.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	needSha256 := false
	needHex := false
	// sdm runtime is imported whenever a repo method that resolves the actor
	// from ctx is emitted — that's every PII / chain mutation method, so any
	// SDM record in the file pulls it in.
	needSdmRuntime := false
	// gorm/clause is only referenced from the ON-CONFLICT upsert path —
	// SaveAll (OFF mode) and Upsert (ON mode), both PII-backed only.
	// A file with nothing but chain-only messages must not import it.
	needClause := false
	for _, msg := range file.Messages {
		if !isSdmRecord(msg) {
			continue
		}
		needSdmRuntime = true
		if !isChainOnly(msg) {
			needClause = true
		}
		for _, field := range msg.Fields {
			opts := getFieldOptions(field)
			if opts.Hashed {
				needSha256 = true
				needHex = true
			}
		}
	}
	needDatatypes := fileHasPiiStringJsonField(file)
	// protojson + strings.Join in the REPO are needed only for chain-stored
	// fields. PII-stored repeated messages go through the protojsonArray
	// serializer in sdm_helpers.go and don't need either import here.
	needProtojson := fileHasChainMessageField(file) || fileHasChainRepeatedMessageField(file)
	needStringsJoin := fileHasChainRepeatedMessageField(file)
	// `time` is referenced by chain-side Timestamp serialization
	// (model.X.AsTime().Format(time.RFC3339Nano)).
	needTime := fileHasChainTimestampField(file)
	// pq.StringArray is used in the PII struct literal for repeated scalar
	// PII fields (`Tags: pq.StringArray(model.Tags)`).
	needPq := fileHasPiiRepeatedScalarField(file)

	g.P("// Code generated by sdm. DO NOT EDIT.")
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	g.P("import (")
	g.P(`	"context"`)
	if needSha256 {
		g.P(`	"crypto/sha256"`)
	}
	if needHex {
		g.P(`	"encoding/hex"`)
	}
	if opts.ChainDrafts {
		// errors.As + *pgconn.PgError used to map the partial-unique-index
		// violation (SQLSTATE 23505) to the ErrPendingDraftExists sentinel.
		g.P(`	"errors"`)
	}
	g.P(`	"fmt"`)
	if needTime {
		g.P(`	"time"`)
	}
	if needProtojson {
		g.P(`	"google.golang.org/protobuf/encoding/protojson"`)
	}
	if needStringsJoin {
		g.P(`	"strings"`)
	}
	if opts.ChainDrafts {
		g.P(`	"github.com/jackc/pgx/v5/pgconn"`)
	}
	if needSdmRuntime {
		g.P(`	"github.com/kapow-tech/sdm/pkg/sdm"`)
	}
	if needPq {
		g.P(`	"github.com/lib/pq"`)
	}
	if needDatatypes {
		g.P(`	"gorm.io/datatypes"`)
	}
	g.P(`	"gorm.io/gorm"`)
	if needClause {
		g.P(`	"gorm.io/gorm/clause"`)
	}
	g.P(")")
	g.P()

	for _, msg := range file.Messages {
		if !isSdmRecord(msg) {
			continue
		}
		modelName := msg.GoIdent.GoName
		chainOnly := isChainOnly(msg)

		// Repo struct. The actor identifier for audit attribution flows
		// exclusively via ctx (see sdm.CtxWithActor / sdm.ActorFromContext);
		// the repo stays a pure data-access layer with no per-call mutable state.
		g.P("// ", modelName, "Repo is the data-access handle for ", modelName, ". The actor")
		g.P("// identifier used for audit attribution flows via ctx (see sdm.CtxWithActor);")
		g.P("// the repo is stateless and safe for concurrent use by multiple goroutines.")
		g.P("type ", modelName, "Repo struct {")
		g.P("  db *gorm.DB")
		g.P("}")
		g.P()

		g.P("// New", modelName, "Repo returns a repo bound to db. Pass a *gorm.DB configured")
		g.P("// against the same database the generated schema was applied to. Sharing")
		g.P("// a single *gorm.DB across goroutines is fine — GORM's connection pool")
		g.P("// handles per-call isolation.")
		g.P("func New", modelName, "Repo(db *gorm.DB) *", modelName, "Repo {")
		g.P("  return &", modelName, "Repo{db: db}")
		g.P("}")
		g.P()

		// compositeKeyExpr is the Go expression that produces the chain key string.
		// Uses chain_identifier_key fields if annotated (e.g. ptt_id), else PKs.
		keyFields := chainKeyGoFields(msg)
		var compositeKeyExpr string
		if len(keyFields) == 1 {
			compositeKeyExpr = fmt.Sprintf("fmt.Sprintf(\"%%v\", model.%s)", keyFields[0].GoName)
		} else {
			fmtParts := make([]string, len(keyFields))
			argParts := make([]string, len(keyFields))
			for i, f := range keyFields {
				fmtParts[i] = "%v"
				argParts[i] = "model." + f.GoName
			}
			compositeKeyExpr = fmt.Sprintf("fmt.Sprintf(\"%s\", %s)",
				strings.Join(fmtParts, ":"), strings.Join(argParts, ", "))
		}

		// emitMessageJsonMarshals pre-computes []byte for chain-stored message fields.
		// Singular: protojson.Marshal directly.
		// Repeated: marshal each element, join into a JSON array string.
		emitMessageJsonMarshals := func(accept func(*protogen.Field, SdmOptions) bool) {
			for _, field := range msg.Fields {
				opts := getFieldOptions(field)
				if !accept(field, opts) {
					continue
				}
				varName := jsonVarName(field)
				if needsProtojsonMarshal(field) {
					g.P("    var ", varName, " []byte")
					g.P("    if model.", field.GoName, " != nil {")
					g.P("      _b, err := protojson.Marshal(model.", field.GoName, ")")
					g.P("      if err != nil { return err }")
					g.P("      ", varName, " = _b")
					g.P("    }")
				} else if needsRepeatedProtojsonMarshal(field) {
					// Initialise with the empty JSON array literal so that an empty
					// or nil slice still produces valid JSON in chain field_value.
					// Otherwise the view's `c_X.field_value::jsonb` cast fails with
					// "invalid input syntax for type json" on the empty string.
					g.P("    ", varName, " := []byte(\"[]\")")
					g.P("    if len(model.", field.GoName, ") > 0 {")
					g.P("      _parts := make([]string, 0, len(model.", field.GoName, "))")
					g.P("      for _, _item := range model.", field.GoName, " {")
					g.P("        _b, err := protojson.Marshal(_item)")
					g.P("        if err != nil { return err }")
					g.P("        _parts = append(_parts, string(_b))")
					g.P("      }")
					g.P("      ", varName, " = []byte(\"[\" + strings.Join(_parts, \",\") + \"]\")")
					g.P("    }")
				}
			}
		}

		// chainAccept decides which fields go into the chain table.
		// For PII-backed messages: skip PK, PII, and references fields (those live in PII).
		// For chain-only messages: skip only the chain identifier key itself (it IS the key,
		// not a field_value row); references fields have no PII table to live in, so they
		// go into chain too.
		var chainAccept func(*protogen.Field, SdmOptions) bool
		if chainOnly {
			chainAccept = func(field *protogen.Field, opts SdmOptions) bool {
				return !opts.ChainIdentifierKey
			}
		} else {
			chainAccept = func(field *protogen.Field, opts SdmOptions) bool {
				return !opts.PrimaryKey && !opts.Pii && opts.References == ""
			}
		}

		emitPiiStruct := func() {
			g.P("    pii := ", modelName, "Pii{")
			for _, field := range msg.Fields {
				opts := getFieldOptions(field)
				if !(opts.Pii || opts.PrimaryKey || opts.References != "") {
					continue
				}
				if opts.AutoIncrement {
					continue
				}
				switch {
				case isProtoTimestamp(field):
					// google.protobuf.Timestamp → time.Time via AsTime().
					// AsTime() is nil-safe (returns zero time if the proto
					// pointer is nil), so no explicit nil-check needed.
					g.P("      ", field.GoName, ": model.", field.GoName, ".AsTime(),")
				case needsRepeatedProtojsonMarshal(field):
					// repeated *Message — pass through; protojsonArray
					// serializer marshals on Value, decodes on Scan.
					g.P("      ", field.GoName, ": model.", field.GoName, ",")
				case field.Desc.IsList() && field.Desc.Kind() != protoreflect.MessageKind:
					// repeated scalar → cast []string to pq.StringArray.
					g.P("      ", field.GoName, ": pq.StringArray(model.", field.GoName, "),")
				case needsProtojsonMarshal(field):
					g.P("      ", field.GoName, ": model.", field.GoName, ",")
				case opts.Json:
					g.P("      ", field.GoName, ": datatypes.JSON(model.", field.GoName, "),")
				default:
					g.P("      ", field.GoName, ": model.", field.GoName, ",")
				}
			}
			// Actor column. Set on every INSERT; not in the conflict-UPDATE
			// assignment set (see updatableSqlCols) so the original creator is
			// preserved across upserts. The per-update actor lives in
			// audit_pii_<name>s.changed_by, written by the AFTER UPDATE trigger
			// from the same `sdm.actor` session variable.
			g.P("      CreatedBy: _actor,")
			g.P("    }")
		}

		// emitChainEntries writes chain rows for every chain-stored field, but
		// only when the value differs from the latest version already stored
		// for (key, field_name). Chain is a history of CHANGES, not a history
		// of saves — repeated saves with the same value produce no new rows.
		//
		// Loads all latest values in one DISTINCT ON query, then compares per
		// field. The comparison is on the exact TEXT form that would be
		// written (Format(time.RFC3339Nano), JSON bytes, pgArrayLiteral, etc.)
		// so the comparison matches byte-for-byte what's in the table.
		//
		// isDraft=true (the DraftChain code path with chain-drafts enabled):
		//   - skip-if-unchanged baseline = latest CREATED only (so re-drafting
		//     a value identical to the committed state is a no-op even if
		//     intermediate drafts/drops happened)
		//   - rows are written with Status='DRAFTED'
		//   - a partial-unique-index violation (existing DRAFTED for the same
		//     (key, field_name)) is wrapped as ErrPendingDraftExists
		// isDraft=false (today's SaveAll chain path):
		//   - skip-if-unchanged baseline = latest of any status (which equals
		//     latest CREATED in OFF mode since DRAFTED/DROPPED don't exist)
		//   - rows are written with the column's default (CREATED)
		emitChainEntries := func(isDraft bool) {
			chainTable := "chain_" + strings.ToLower(modelName) + "s"
			baselineFilter := ""
			if isDraft {
				baselineFilter = " AND status = 'CREATED'"
			}
			g.P("    compositeKey := ", compositeKeyExpr)
			g.P("    var _latestRows []struct {")
			g.P("      FieldName  string")
			g.P("      FieldValue string")
			g.P("    }")
			g.P("    if err := tx.Raw(\"SELECT DISTINCT ON (field_name) field_name, field_value FROM ", chainTable, " WHERE key = ?", baselineFilter, " ORDER BY field_name, version DESC\", compositeKey).Scan(&_latestRows).Error; err != nil { return err }")
			g.P("    _latest := make(map[string]string, len(_latestRows))")
			g.P("    for _, _r := range _latestRows { _latest[_r.FieldName] = _r.FieldValue }")
			emitMessageJsonMarshals(chainAccept)
			// emitCreate writes a single chain row, optionally wrapping a
			// partial-unique-index violation in ErrPendingDraftExists when
			// drafting.
			emitCreate := func() {
				if isDraft {
					g.P("        if err := tx.Create(&_row).Error; err != nil {")
					g.P("          var _pg *pgconn.PgError")
					g.P("          if errors.As(err, &_pg) && _pg.Code == \"23505\" { return ErrPendingDraftExists }")
					g.P("          return err")
					g.P("        }")
				} else {
					g.P("        if err := tx.Create(&_row).Error; err != nil { return err }")
				}
			}
			for _, field := range msg.Fields {
				opts := getFieldOptions(field)

				// Decide whether the main chain row for this field should be written.
				// Note this is independent from the Hashed sidecar below: a PII
				// field can still produce a `hashed_X` chain row even though its
				// main value lives only in the PII table.
				emitMain := true
				if chainOnly && opts.ChainIdentifierKey {
					emitMain = false
				}
				if !chainOnly {
					if opts.PrimaryKey || opts.References != "" || opts.Pii {
						emitMain = false
					}
				}

				if emitMain {
					var fieldValueExpr string
					switch {
					case isProtoTimestamp(field):
						// google.protobuf.Timestamp → RFC3339Nano text. The view
						// casts the chain TEXT back to ::timestamptz, which
						// time.Time scans via lib/pq.
						fieldValueExpr = fmt.Sprintf("model.%s.AsTime().Format(time.RFC3339Nano)", field.GoName)
					case needsProtojsonMarshal(field):
						// Singular proto.Message → pre-marshaled by emitMessageJsonMarshals.
						fieldValueExpr = fmt.Sprintf("string(%s)", jsonVarName(field))
					case needsRepeatedProtojsonMarshal(field):
						// Repeated proto.Message → JSON array pre-built by emitMessageJsonMarshals.
						fieldValueExpr = fmt.Sprintf("string(%s)", jsonVarName(field))
					case opts.Json:
						fieldValueExpr = fmt.Sprintf("string(model.%s)", field.GoName)
					case field.Desc.IsList():
						// Repeated scalar ([]string) → PostgreSQL array literal.
						fieldValueExpr = fmt.Sprintf("pgArrayLiteral(model.%s)", field.GoName)
					default:
						fieldValueExpr = fmt.Sprintf("fmt.Sprintf(\"%%v\", model.%s)", field.GoName)
					}
					colName := string(field.Desc.Name())
					g.P("    {")
					g.P("      _v := ", fieldValueExpr)
					g.P("      if _prev, _ok := _latest[\"", colName, "\"]; !_ok || _prev != _v {")
					g.P("        _row := ", modelName, "Chain{")
					g.P("          Key:        compositeKey,")
					g.P("          FieldName:  \"", colName, "\",")
					g.P("          FieldValue: _v,")
					g.P("          CreatedBy:  _actor,")
					if isDraft {
						g.P("          Status:     \"DRAFTED\",")
					}
					g.P("        }")
					emitCreate()
					g.P("      }")
					g.P("    }")
				}

				if opts.Hashed {
					hashedName := "hashed_" + string(field.Desc.Name())
					g.P("    {")
					g.P("      // Hash ", field.GoName)
					g.P("      _h := sha256.Sum256([]byte(fmt.Sprintf(\"%v\", model.", field.GoName, ")))")
					g.P("      _hv := hex.EncodeToString(_h[:])")
					g.P("      if _prev, _ok := _latest[\"", hashedName, "\"]; !_ok || _prev != _hv {")
					g.P("        _row := ", modelName, "Chain{")
					g.P("          Key:        compositeKey,")
					g.P("          FieldName:  \"", hashedName, "\",")
					g.P("          FieldValue: _hv,")
					g.P("          CreatedBy:  _actor,")
					if isDraft {
						g.P("          Status:     \"DRAFTED\",")
					}
					g.P("        }")
					emitCreate()
					g.P("      }")
					g.P("    }")
				}
			}
		}

		emitAutoIncrementCopyback := func() {
			for _, field := range msg.Fields {
				opts := getFieldOptions(field)
				if opts.AutoIncrement {
					g.P("    model.", field.GoName, " = pii.", field.GoName, " // copy DB-generated value back to model")
				}
			}
		}

		// emitResolveActor binds the ctx-carried actor identifier to the
		// local `_actor` variable inside the transaction lambda. The
		// variable is always defined (empty string when no actor is on the
		// ctx) so downstream emit blocks (emitPiiStruct, emitChainEntries)
		// can reference it unconditionally.
		emitResolveActor := func() {
			g.P("    _actor := sdm.ActorFromContext(ctx)")
		}

		// emitInstallActorSessionVar installs `_actor` into the `sdm.actor`
		// Postgres session variable for the current transaction
		// (`is_local=true`). The audit_pii_<name>s trigger reads the same
		// variable. Skipped when _actor is empty. Requires emitResolveActor
		// to have run first. Becomes a no-op when audit tables are disabled
		// (Options.CreateAuditTables=false) — without a trigger to read the
		// variable, setting it is pure waste.
		emitInstallActorSessionVar := func() {
			if !opts.CreateAuditTables {
				return
			}
			g.P("    if _actor != \"\" {")
			g.P("      if err := tx.Exec(\"SELECT set_config('sdm.actor', ?, true)\", _actor).Error; err != nil { return err }")
			g.P("    }")
		}

		// chainKeyParams / chainKeyArgs build the (k1 typeA, k2 typeB, ...)
		// parameter list used by CommitChain / DropChain, which take the
		// chain identifier key fields rather than a model. Mirrors the
		// ChangeLog signature pattern.
		chainKeyParams := make([]string, len(keyFields))
		chainKeyArgs := make([]string, len(keyFields))
		for i, f := range keyFields {
			pn := strings.ToLower(f.GoName[:1]) + f.GoName[1:]
			chainKeyParams[i] = pn + " " + goTypeForField(f)
			chainKeyArgs[i] = pn
		}
		var chainKeyExprStandalone string
		if len(keyFields) == 1 {
			chainKeyExprStandalone = fmt.Sprintf("fmt.Sprintf(\"%%v\", %s)", chainKeyArgs[0])
		} else {
			fmtParts := make([]string, len(keyFields))
			for i := range keyFields {
				fmtParts[i] = "%v"
			}
			chainKeyExprStandalone = fmt.Sprintf("fmt.Sprintf(\"%s\", %s)",
				strings.Join(fmtParts, ":"), strings.Join(chainKeyArgs, ", "))
		}
		if !chainOnly {
			// ── Create (PII-backed only) ──────────────────────────────────
			// Strict INSERT of the PII row; errors with the driver-native
			// error on PK / unique conflict.
			//
			// OFF mode: PII insert only — caller chains via SaveAll if they
			// want the chain step too.
			// ON mode: PII insert, then DraftChain stages chain rows as
			// DRAFTED in the same transaction. The chain rows are NOT
			// visible from the committed view; callers must CommitChain to
			// promote them. ErrPendingDraftExists surfaces if any chain
			// field already has a pending DRAFTED row for this key.
			g.P("// Create inserts a new PII row strictly — PK / unique-index violations")
			g.P("// surface as the driver-native error (e.g. *pgconn.PgError SQLSTATE")
			g.P("// 23505), not an upsert. Auto-increment PKs are copied back onto the")
			g.P("// passed model.")
			if opts.ChainDrafts {
				g.P("//")
				g.P("// chain-drafts ON: in the same transaction, every chain-stored field")
				g.P("// (and any hashed sidecars) is written as a DRAFTED chain row. Those")
				g.P("// rows are NOT yet visible in the committed view — callers must call")
				g.P("// CommitChain(...) to promote them, or DropChain(...) to discard.")
				g.P("// ErrPendingDraftExists is returned if any chain field already has a")
				g.P("// DRAFTED row for this key.")
			} else {
				g.P("//")
				g.P("// chain-drafts OFF: writes the PII row only. Pair with SaveAll(_, true)")
				g.P("// (or use SaveAll directly with the upsert semantics) when you also")
				g.P("// want chain history appended.")
			}
			g.P("func (r *", modelName, "Repo) Create(ctx context.Context, model *", modelName, ") error {")
			g.P("  return r.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {")
			emitResolveActor()
			emitInstallActorSessionVar()
			emitPiiStruct()
			g.P("    if err := tx.Create(&pii).Error; err != nil { return err }")
			emitAutoIncrementCopyback()
			if opts.ChainDrafts {
				g.P("    // chain-drafts: stage chain fields as DRAFTED in the same transaction")
				emitChainEntries(true)
			}
			g.P("    return nil")
			g.P("  })")
			g.P("}")
			g.P()
		}

		if !opts.ChainDrafts {
			// ── SaveAll (OFF mode only) ───────────────────────────────────
			// Upserts the PII row (INSERT, or on conflict UPDATE the mutable
			// columns) and, when withChain=true, appends new chain versions
			// for every chain-stored field whose value changed (status defaults
			// to CREATED). Conflict target is the chain identifier key
			// (PK, or chain_identifier_key + unique).
			//
			// For chain-only messages the PII step is a no-op; behavior
			// collapses to a chain-only append when withChain=true, or a
			// no-op when withChain=false.
			g.P("// SaveAll upserts the PII row (INSERT on miss, UPDATE on conflict against")
			g.P("// the chain identifier key for the mutable columns) and, when")
			g.P("// withChain=true, appends new chain versions for every chain-stored")
			g.P("// field whose value differs from the latest stored value (skip-if-")
			g.P("// unchanged per field). Chain rows are written with the column default")
			g.P("// status (CREATED) — they are immediately visible from Fetch / FetchBy*.")
			g.P("// For chain-only messages the PII step is skipped: withChain=true")
			g.P("// collapses to a chain-only append, withChain=false is a no-op.")
			g.P("func (r *", modelName, "Repo) SaveAll(ctx context.Context, model *", modelName, ", withChain bool) error {")
			g.P("  return r.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {")
			emitResolveActor()
			if !chainOnly {
				updatableCols := updatableSqlCols(msg)
				conflictCols := make([]string, len(keyFields))
				for i, f := range keyFields {
					conflictCols[i] = "{Name: \"" + string(f.Desc.Name()) + "\"}"
				}
				emitInstallActorSessionVar()
				emitPiiStruct()
				g.P("    if err := tx.Clauses(clause.OnConflict{")
				g.P("      Columns:   []clause.Column{", strings.Join(conflictCols, ", "), "},")
				g.P("      DoUpdates: clause.AssignmentColumns([]string{\"", strings.Join(updatableCols, "\", \""), "\"}),")
				g.P("    }).Create(&pii).Error; err != nil { return err }")
				emitAutoIncrementCopyback()
				g.P()
			}
			g.P("    if !withChain { return nil }")
			g.P("    // Save Chain Fields (skip-if-unchanged per field)")
			emitChainEntries(false)
			g.P("    return nil")
			g.P("  })")
			g.P("}")
			g.P()
		}

		if opts.ChainDrafts && !chainOnly {
			updatableCols := updatableSqlCols(msg)
			conflictCols := make([]string, len(keyFields))
			for i, f := range keyFields {
				conflictCols[i] = "{Name: \"" + string(f.Desc.Name()) + "\"}"
			}

			// ── Upsert (ON mode, PII-backed only) ─────────────────────────
			// PII upsert (INSERT, or on conflict UPDATE the mutable columns)
			// + DraftChain. Same shape as today's SaveAll(_, true) but the
			// chain rows are written as DRAFTED, not CREATED — caller must
			// CommitChain to publish them.
			g.P("// Upsert is the chain-drafts equivalent of SaveAll: PII INSERT on miss")
			g.P("// or UPDATE on conflict against the chain identifier key (mutable")
			g.P("// columns only), followed by DraftChain in the same transaction.")
			g.P("// Chain rows are written as DRAFTED — they are NOT visible in the")
			g.P("// committed view until CommitChain is called. Returns")
			g.P("// ErrPendingDraftExists if any chain field already has a pending")
			g.P("// DRAFTED row for this key.")
			g.P("func (r *", modelName, "Repo) Upsert(ctx context.Context, model *", modelName, ") error {")
			g.P("  return r.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {")
			emitResolveActor()
			emitInstallActorSessionVar()
			emitPiiStruct()
			g.P("    if err := tx.Clauses(clause.OnConflict{")
			g.P("      Columns:   []clause.Column{", strings.Join(conflictCols, ", "), "},")
			g.P("      DoUpdates: clause.AssignmentColumns([]string{\"", strings.Join(updatableCols, "\", \""), "\"}),")
			g.P("    }).Create(&pii).Error; err != nil { return err }")
			emitAutoIncrementCopyback()
			g.P("    // chain-drafts: stage chain fields as DRAFTED in the same transaction")
			emitChainEntries(true)
			g.P("    return nil")
			g.P("  })")
			g.P("}")
			g.P()

			// ── Update (ON mode, PII-backed only) ─────────────────────────
			// Strict UPDATE on the PII row + DraftChain. Returns
			// gorm.ErrRecordNotFound if the PII row doesn't exist (no upsert
			// — use Upsert for that). Only the conflict-updatable columns
			// are written; created_by stays intact.
			g.P("// Update strictly UPDATEs the PII row (no insert-on-miss — use Upsert")
			g.P("// for that) and stages DRAFTED chain entries for every chain-stored")
			g.P("// field whose value differs from the latest committed value. Only the")
			g.P("// mutable columns are touched; created_by and created_at stay intact.")
			g.P("// Returns gorm.ErrRecordNotFound if the PII row does not exist, or")
			g.P("// ErrPendingDraftExists if any chain field already has a pending")
			g.P("// DRAFTED row for this key.")
			g.P("func (r *", modelName, "Repo) Update(ctx context.Context, model *", modelName, ") error {")
			g.P("  return r.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {")
			emitResolveActor()
			emitInstallActorSessionVar()
			emitPiiStruct()
			updateWhereCols := make([]string, len(keyFields))
			updateWhereArgs := make([]string, len(keyFields))
			for i, f := range keyFields {
				updateWhereCols[i] = string(f.Desc.Name()) + " = ?"
				updateWhereArgs[i] = "model." + f.GoName
			}
			g.P("    _result := tx.Model(&", modelName, "Pii{}).")
			g.P("      Where(\"", strings.Join(updateWhereCols, " AND "), "\", ", strings.Join(updateWhereArgs, ", "), ").")
			g.P("      Select([]string{\"", strings.Join(updatableCols, "\", \""), "\"}).")
			g.P("      Updates(pii)")
			g.P("    if _result.Error != nil { return _result.Error }")
			g.P("    if _result.RowsAffected == 0 { return gorm.ErrRecordNotFound }")
			g.P("    // chain-drafts: stage chain fields as DRAFTED in the same transaction")
			emitChainEntries(true)
			g.P("    return nil")
			g.P("  })")
			g.P("}")
			g.P()
		}

		if opts.ChainDrafts {
			// ── DraftChain ────────────────────────────────────────────────
			// Standalone draft entry point — appends DRAFTED rows for every
			// chain-stored field that differs from the latest CREATED value.
			// At-most-one DRAFTED row per (key, field_name) is enforced by
			// a partial unique index; violations surface as
			// ErrPendingDraftExists. For chain-only messages this is the
			// only ingestion path.
			g.P("// DraftChain stages chain edits without touching the PII row. For every")
			g.P("// chain-stored field whose value differs from the latest CREATED entry,")
			g.P("// a new row is appended with Status='DRAFTED'. At most one DRAFTED row")
			g.P("// per (key, field_name) is allowed (enforced by a partial unique")
			g.P("// index); a second draft surfaces ErrPendingDraftExists. For chain-only")
			g.P("// messages this is the primary ingestion path; for PII-backed messages")
			g.P("// it lets callers stage chain edits separately from PII writes.")
			g.P("func (r *", modelName, "Repo) DraftChain(ctx context.Context, model *", modelName, ") error {")
			g.P("  return r.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {")
			emitResolveActor()
			emitChainEntries(true)
			g.P("    return nil")
			g.P("  })")
			g.P("}")
			g.P()

			// ── CommitChain ───────────────────────────────────────────────
			// Promotes every DRAFTED row for this key to CREATED in a single
			// UPDATE, atomically across all drafted fields, and stamps the
			// supplied tx_hash on the promoted rows (pass "" if not
			// applicable). The state-machine trigger guards the transition.
			// Idempotent — no-op when no DRAFTED rows exist for the key.
			g.P("// CommitChain promotes every DRAFTED row for this key to CREATED in a")
			g.P("// single atomic UPDATE and stamps the supplied txHash on the promoted")
			g.P("// rows (pass \"\" if not applicable). The state-machine BEFORE UPDATE")
			g.P("// trigger guards the DRAFTED → CREATED transition. Idempotent: a no-op")
			g.P("// when no DRAFTED rows exist for the key. After commit, the rows are")
			g.P("// visible from the committed view.")
			g.P("func (r *", modelName, "Repo) CommitChain(ctx context.Context, ",
				strings.Join(chainKeyParams, ", "), ", txHash string) error {")
			g.P("  return r.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {")
			// _actor is only consumed by the audit session-var install (the
			// chain UPDATE itself doesn't reference it). Skip emitting it
			// when audit is off so the generated code stays compilable.
			if opts.CreateAuditTables {
				emitResolveActor()
				emitInstallActorSessionVar()
			}
			g.P("    _key := ", chainKeyExprStandalone)
			g.P("    return tx.Model(&", modelName, "Chain{}).")
			g.P("      Where(\"key = ? AND status = ?\", _key, \"DRAFTED\").")
			g.P("      Updates(map[string]interface{}{\"status\": \"CREATED\", \"tx_hash\": txHash}).Error")
			g.P("  })")
			g.P("}")
			g.P()

			// ── DropChain ─────────────────────────────────────────────────
			// Promotes every DRAFTED row for this key to DROPPED in a single
			// UPDATE. Idempotent — no-op when no DRAFTED rows exist for the
			// key. Use to discard a pending edit without committing it.
			g.P("// DropChain promotes every DRAFTED row for this key to DROPPED in a")
			g.P("// single UPDATE — discards a pending edit without committing. The")
			g.P("// dropped rows remain in the chain table as audit history; they are")
			g.P("// not visible from either view. Idempotent: no-op when no DRAFTED rows")
			g.P("// exist for the key.")
			g.P("func (r *", modelName, "Repo) DropChain(ctx context.Context, ",
				strings.Join(chainKeyParams, ", "), ") error {")
			g.P("  return r.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {")
			// Same as CommitChain: _actor is only consumed by the audit
			// session-var install. Skip when audit is off.
			if opts.CreateAuditTables {
				emitResolveActor()
				emitInstallActorSessionVar()
			}
			g.P("    _key := ", chainKeyExprStandalone)
			g.P("    return tx.Model(&", modelName, "Chain{}).")
			g.P("      Where(\"key = ? AND status = ?\", _key, \"DRAFTED\").")
			g.P("      Update(\"status\", \"DROPPED\").Error")
			g.P("  })")
			g.P("}")
			g.P()
		}

		// ── Fetch / FetchBy* / Exists / ExistsBy* ────────────────────────────
		// For chain-only messages the identifier is the chain key field, not a PK.
		// For PII-backed messages the identifier is the PK field(s).
		//
		// When chain-drafts is enabled, Fetch / FetchBy* take an additional
		// `drafted bool` parameter and dispatch to either `<name>s`
		// (committed) or `<name>s_with_drafts` (overlay) view via .Table().
		// HasPendingDrafts is populated regardless of which view is queried.
		// Exists / ExistsBy* are not draft-aware — they probe the PII table
		// (or chain table for chain-only) and the existence question is
		// answered by committed state.
		draftedSig := ""
		draftedTableInject := ""
		emitDraftedTableSetup := func() {}
		if opts.ChainDrafts {
			draftedSig = ", drafted bool"
			lowerName := strings.ToLower(modelName)
			draftedTableInject = ".Table(_table)"
			emitDraftedTableSetup = func() {
				g.P("  _table := \"", lowerName, "s\"")
				g.P("  if drafted { _table = \"", lowerName, "s_with_drafts\" }")
			}
		}

		if chainOnly {
			// Single key field — chain_identifier_key is always the lookup handle.
			keyField := keyFields[0]
			paramName := strings.ToLower(keyField.GoName[:1]) + keyField.GoName[1:]
			paramType := goTypeForField(keyField)
			colName := string(keyField.Desc.Name())

			// Fetch queries the view by the chain key column (materialized as keys.key AS ptt_id).
			g.P("// Fetch reads the view row keyed by the chain identifier column. Returns")
			g.P("// gorm.ErrRecordNotFound if no row matches.")
			if opts.ChainDrafts {
				g.P("//")
				g.P("// drafted=true reads from the ", strings.ToLower(modelName), "s_with_drafts overlay view,")
				g.P("// surfacing uncommitted DRAFTED values; drafted=false reads from the")
				g.P("// committed view. HasPendingDrafts is populated either way.")
			}
			g.P("func (r *", modelName, "Repo) Fetch(ctx context.Context, ", paramName, " ", paramType, draftedSig, ") (*", modelName, "View, error) {")
			g.P("  var view ", modelName, "View")
			emitDraftedTableSetup()
			g.P("  if err := r.db.WithContext(ctx)", draftedTableInject, ".Where(\"", colName, " = ?\", ", paramName, ").First(&view).Error; err != nil {")
			g.P("    return nil, err")
			g.P("  }")
			g.P("  return &view, nil")
			g.P("}")
			g.P()

			// Exists queries the chain table directly — no PII table
			// available. Not draft-aware: existence is answered by committed
			// rows. In ON mode we narrow to CREATED so a key that only has
			// DRAFTED rows doesn't appear to "exist" yet.
			existsStatusFilter := ""
			if opts.ChainDrafts {
				existsStatusFilter = " AND status = ?"
			}
			if opts.ChainDrafts {
				g.P("// Exists reports whether any committed (CREATED) chain row exists for the")
				g.P("// given key. Not draft-aware — a key whose chain rows are still entirely")
				g.P("// DRAFTED returns false (the record is not yet committed).")
			} else {
				g.P("// Exists reports whether any chain row exists for the given key.")
			}
			g.P("func (r *", modelName, "Repo) Exists(ctx context.Context, ", paramName, " ", paramType, ") (bool, error) {")
			g.P("  var count int64")
			if opts.ChainDrafts {
				g.P("  if err := r.db.WithContext(ctx).Model(&", modelName, "Chain{}).Where(\"key = ?", existsStatusFilter, "\", ", paramName, ", \"CREATED\").Count(&count).Error; err != nil {")
			} else {
				g.P("  if err := r.db.WithContext(ctx).Model(&", modelName, "Chain{}).Where(\"key = ?\", ", paramName, ").Count(&count).Error; err != nil {")
			}
			g.P("    return false, err")
			g.P("  }")
			g.P("  return count > 0, nil")
			g.P("}")
			g.P()

			// FetchBy* for unique non-key fields.
			for _, field := range msg.Fields {
				opts := getFieldOptions(field)
				if !opts.Unique || opts.ChainIdentifierKey {
					continue
				}
				fp := strings.ToLower(field.GoName[:1]) + field.GoName[1:]
				g.P("// FetchBy", field.GoName, " reads the view row by the unique ", field.Desc.Name(), " column.")
				g.P("// Returns gorm.ErrRecordNotFound if no row matches.")
				if draftedSig != "" {
					g.P("// Same drafted-bool semantics as Fetch (overlay vs committed view).")
				}
				g.P("func (r *", modelName, "Repo) FetchBy", field.GoName,
					"(ctx context.Context, ", fp, " ", goTypeForField(field), draftedSig, ") (*", modelName, "View, error) {")
				g.P("  var view ", modelName, "View")
				emitDraftedTableSetup()
				g.P("  if err := r.db.WithContext(ctx)", draftedTableInject, ".Where(\"", field.Desc.Name(), " = ?\", ", fp, ").First(&view).Error; err != nil {")
				g.P("    return nil, err")
				g.P("  }")
				g.P("  return &view, nil")
				g.P("}")
				g.P()
			}
		} else {
			// PII-backed path — Fetch reads the view, Exists counts pii_X. Both
			// emit an explicit `deleted_at IS NULL` filter for clarity (PII and
			// View structs also carry gorm.DeletedAt which adds the same scope
			// automatically — the explicit clause makes the generated SQL
			// obvious to readers).
			const notDeleted = `.Where("deleted_at IS NULL")`

			var pkFields []*protogen.Field
			for _, field := range msg.Fields {
				if getFieldOptions(field).PrimaryKey {
					pkFields = append(pkFields, field)
				}
			}

			fetchParams := make([]string, len(pkFields))
			whereExprs := make([]string, len(pkFields))
			whereArgs := make([]string, len(pkFields))
			for i, f := range pkFields {
				paramName := strings.ToLower(f.GoName[:1]) + f.GoName[1:]
				fetchParams[i] = paramName + " " + goTypeForField(f)
				whereExprs[i] = string(f.Desc.Name()) + " = ?"
				whereArgs[i] = paramName
			}

			g.P("// Fetch reads the view row keyed by the primary key, scoped to")
			g.P("// non-soft-deleted records (deleted_at IS NULL). Returns")
			g.P("// gorm.ErrRecordNotFound if no row matches.")
			if draftedSig != "" {
				g.P("//")
				g.P("// drafted=true reads from the ", strings.ToLower(modelName), "s_with_drafts overlay view")
				g.P("// (uncommitted DRAFTED values visible); drafted=false reads from the")
				g.P("// committed view. HasPendingDrafts on the result is populated either way.")
			}
			g.P("func (r *", modelName, "Repo) Fetch(ctx context.Context, ",
				strings.Join(fetchParams, ", "), draftedSig, ") (*", modelName, "View, error) {")
			g.P("  var view ", modelName, "View")
			emitDraftedTableSetup()
			g.P("  if err := r.db.WithContext(ctx)", draftedTableInject, ".Where(\"", strings.Join(whereExprs, " AND "), "\", ",
				strings.Join(whereArgs, ", "), ")", notDeleted, ".First(&view).Error; err != nil {")
			g.P("    return nil, err")
			g.P("  }")
			g.P("  return &view, nil")
			g.P("}")
			g.P()

			for _, field := range msg.Fields {
				opts := getFieldOptions(field)
				if !opts.Unique {
					continue
				}
				paramName := strings.ToLower(field.GoName[:1]) + field.GoName[1:]
				g.P("// FetchBy", field.GoName, " reads the view row by the unique ", field.Desc.Name(), " column,")
				g.P("// scoped to non-soft-deleted records. Returns gorm.ErrRecordNotFound if no")
				g.P("// row matches.")
				if draftedSig != "" {
					g.P("// Same drafted-bool semantics as Fetch (overlay vs committed view).")
				}
				g.P("func (r *", modelName, "Repo) FetchBy", field.GoName,
					"(ctx context.Context, ", paramName, " ", goTypeForField(field), draftedSig, ") (*", modelName, "View, error) {")
				g.P("  var view ", modelName, "View")
				emitDraftedTableSetup()
				g.P("  if err := r.db.WithContext(ctx)", draftedTableInject, ".Where(\"", field.Desc.Name(), " = ?\", ", paramName, ")", notDeleted, ".First(&view).Error; err != nil {")
				g.P("    return nil, err")
				g.P("  }")
				g.P("  return &view, nil")
				g.P("}")
				g.P()
			}

			if len(pkFields) > 1 {
				for _, field := range pkFields {
					paramName := strings.ToLower(field.GoName[:1]) + field.GoName[1:]
					g.P("// FetchBy", field.GoName, " returns every view row whose ", field.Desc.Name(), " equals the")
					g.P("// given value — for composite primary keys, this is one PK component and")
					g.P("// can match multiple rows. Scoped to non-soft-deleted records.")
					if draftedSig != "" {
						g.P("// Same drafted-bool semantics as Fetch (overlay vs committed view).")
					}
					g.P("func (r *", modelName, "Repo) FetchBy", field.GoName,
						"(ctx context.Context, ", paramName, " ", goTypeForField(field), draftedSig, ") ([]", modelName, "View, error) {")
					g.P("  var views []", modelName, "View")
					emitDraftedTableSetup()
					g.P("  if err := r.db.WithContext(ctx)", draftedTableInject, ".Where(\"", field.Desc.Name(), " = ?\", ", paramName, ")", notDeleted, ".Find(&views).Error; err != nil {")
					g.P("    return nil, err")
					g.P("  }")
					g.P("  return views, nil")
					g.P("}")
					g.P()
				}
			}

			g.P("// Exists reports whether a non-soft-deleted PII row exists for the given")
			g.P("// primary key. Not draft-aware — answered by committed PII state.")
			g.P("func (r *", modelName, "Repo) Exists(ctx context.Context, ",
				strings.Join(fetchParams, ", "), ") (bool, error) {")
			g.P("  var count int64")
			g.P("  if err := r.db.WithContext(ctx).Model(&", modelName, "Pii{}).Where(\"",
				strings.Join(whereExprs, " AND "), "\", ", strings.Join(whereArgs, ", "), ")", notDeleted, ".Count(&count).Error; err != nil {")
			g.P("    return false, err")
			g.P("  }")
			g.P("  return count > 0, nil")
			g.P("}")
			g.P()

			for _, field := range msg.Fields {
				opts := getFieldOptions(field)
				if !opts.Unique {
					continue
				}
				paramName := strings.ToLower(field.GoName[:1]) + field.GoName[1:]
				g.P("// ExistsBy", field.GoName, " reports whether a non-soft-deleted PII row exists for")
				g.P("// the given ", field.Desc.Name(), " value.")
				g.P("func (r *", modelName, "Repo) ExistsBy", field.GoName,
					"(ctx context.Context, ", paramName, " ", goTypeForField(field), ") (bool, error) {")
				g.P("  var count int64")
				g.P("  if err := r.db.WithContext(ctx).Model(&", modelName, "Pii{}).Where(\"",
					field.Desc.Name(), " = ?\", ", paramName, ")", notDeleted, ".Count(&count).Error; err != nil {")
				g.P("    return false, err")
				g.P("  }")
				g.P("  return count > 0, nil")
				g.P("}")
				g.P()
			}

			// ── AuditLog (PII-backed only) ───────────────────────────────────
			// Returns the audit_pii_<name>s history for a single record,
			// chronologically (oldest first). Each row is a snapshot of the
			// PII row immediately BEFORE an UPDATE or DELETE. Empty slice if
			// the record was inserted but never modified.
			//
			// Param signature mirrors Fetch's — takes the PK fields. The audit
			// table's ref_id is the PK joined with ':' for composite PKs.
			// Skipped when audit tables are disabled (no <Name>PiiAudit struct
			// or audit_pii_<name>s table exists in that mode).
			if opts.CreateAuditTables {
				var refIDExpr string
				if len(whereArgs) == 1 {
					refIDExpr = fmt.Sprintf("fmt.Sprintf(\"%%v\", %s)", whereArgs[0])
				} else {
					fmtParts := make([]string, len(whereArgs))
					for i := range whereArgs {
						fmtParts[i] = "%v"
					}
					refIDExpr = fmt.Sprintf("fmt.Sprintf(\"%s\", %s)",
						strings.Join(fmtParts, ":"), strings.Join(whereArgs, ", "))
				}
				g.P("// AuditLog returns the audit_pii_", strings.ToLower(modelName), "s history for a single")
				g.P("// record, chronologically (oldest first). Each row is a snapshot of the")
				g.P("// PII row taken immediately BEFORE an UPDATE or DELETE by the AFTER")
				g.P("// trigger; INSERTs do not produce audit rows, so a record that was")
				g.P("// inserted but never modified returns the empty slice. Param signature")
				g.P("// mirrors Fetch — takes the PK; for composite PKs the audit ref_id is")
				g.P("// the PK components joined with ':'.")
				g.P("func (r *", modelName, "Repo) AuditLog(ctx context.Context, ",
					strings.Join(fetchParams, ", "), ") ([]", modelName, "PiiAudit, error) {")
				g.P("  var rows []", modelName, "PiiAudit")
				g.P("  if err := r.db.WithContext(ctx).")
				g.P("    Where(\"ref_id = ?\", ", refIDExpr, ").")
				g.P("    Order(\"changed_at ASC, id ASC\").")
				g.P("    Find(&rows).Error; err != nil {")
				g.P("    return nil, err")
				g.P("  }")
				g.P("  return rows, nil")
				g.P("}")
				g.P()
			}
		}

		// ── ChangeLog ────────────────────────────────────────────────────────
		// Returns the full per-field version history for a single record,
		// grouped by chain field_name then version. Soft-deleted PII rows do
		// NOT mask chain history — chain entries persist independently and
		// remain queryable. Returns gorm.ErrRecordNotFound if the key has no
		// chain rows at all.
		//
		// Param signature mirrors Create's compositeKey construction: takes
		// the chain identifier key field(s) and composes the lookup key the
		// same way Create does, so callers hand it whatever they originally
		// wrote.
		{
			chParams := make([]string, len(keyFields))
			chArgs := make([]string, len(keyFields))
			for i, f := range keyFields {
				pn := strings.ToLower(f.GoName[:1]) + f.GoName[1:]
				chParams[i] = pn + " " + goTypeForField(f)
				chArgs[i] = pn
			}
			var chainKeyExpr string
			if len(keyFields) == 1 {
				chainKeyExpr = fmt.Sprintf("fmt.Sprintf(\"%%v\", %s)", chArgs[0])
			} else {
				fmtParts := make([]string, len(keyFields))
				for i := range keyFields {
					fmtParts[i] = "%v"
				}
				chainKeyExpr = fmt.Sprintf("fmt.Sprintf(\"%s\", %s)",
					strings.Join(fmtParts, ":"), strings.Join(chArgs, ", "))
			}

			g.P("// ChangeLog returns the full per-field version history for a single record,")
			g.P("// grouped by field_name then version (1-based, ascending). With")
			g.P("// chain-drafts enabled the result includes rows of every status (DRAFTED")
			g.P("// / CREATED / DROPPED) — filter by status on the returned entries if")
			g.P("// only committed history is wanted. Soft-deleted PII rows do NOT mask")
			g.P("// chain history (chain entries persist independently). Returns")
			g.P("// gorm.ErrRecordNotFound when no chain rows exist for the key. Param")
			g.P("// signature mirrors Create — takes the chain identifier key field(s).")
			g.P("func (r *", modelName, "Repo) ChangeLog(ctx context.Context, ",
				strings.Join(chParams, ", "), ") (ChangeLog, error) {")
			g.P("  var rows []", modelName, "Chain")
			g.P("  if err := r.db.WithContext(ctx).")
			g.P("    Where(\"key = ?\", ", chainKeyExpr, ").")
			g.P("    Order(\"field_name, version\").")
			g.P("    Find(&rows).Error; err != nil {")
			g.P("    return nil, err")
			g.P("  }")
			g.P("  if len(rows) == 0 { return nil, gorm.ErrRecordNotFound }")
			g.P("  log := make(ChangeLog)")
			g.P("  for _, row := range rows {")
			g.P("    if _, ok := log[row.FieldName]; !ok {")
			g.P("      log[row.FieldName] = make(map[int64]ChangeLogEntry)")
			g.P("    }")
			g.P("    log[row.FieldName][row.Version] = ChangeLogEntry{")
			g.P("      Value:     row.FieldValue,")
			g.P("      Timestamp: row.CreatedAt,")
			g.P("      Actor:     row.CreatedBy,")
			g.P("    }")
			g.P("  }")
			g.P("  return log, nil")
			g.P("}")
			g.P()
		}
	}
}
