package generator

import (
	"fmt"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
)

// generateSQL emits <prefix>_sdm_schema.sql — the full DDL for each recorded
// message: PII table (with audit table + trigger when enabled), chain table
// (with state-machine trigger + partial unique index when chain-drafts is on),
// the per-(key, field_name) version trigger, and one or two views.
func generateSQL(gen *protogen.Plugin, file *protogen.File, opts Options) {
	filename := file.GeneratedFilenamePrefix + "_sdm_schema.sql"
	g := gen.NewGeneratedFile(filename, "")

	g.P("-- Code generated by sdm. DO NOT EDIT.")
	g.P()

	for _, msg := range file.Messages {
		if !isSdmRecord(msg) {
			continue
		}
		modelName := strings.ToLower(msg.GoIdent.GoName)
		chainOnly := isChainOnly(msg)

		// ── PII Table (skipped for chain-only messages) ───────────────────────
		if !chainOnly {
			g.P("CREATE TABLE IF NOT EXISTS pii_", modelName, "s (")
			pkCols := []string{}
			uniqueFields := []string{}
			type fkEntry struct{ col, refTable, refCol string }
			var fkFields []fkEntry

			for _, field := range msg.Fields {
				opts := getFieldOptions(field)
				if opts.PrimaryKey || opts.Pii || opts.QueryIndex || opts.References != "" {
					sqlType := sqlTypeForField(field, opts)
					g.P(fmt.Sprintf("  %s %s,", field.Desc.Name(), sqlType))
					if opts.PrimaryKey {
						pkCols = append(pkCols, string(field.Desc.Name()))
					}
					if opts.Unique {
						uniqueFields = append(uniqueFields, string(field.Desc.Name()))
					}
				}
				if opts.References != "" {
					refTable, refCol := parseReference(opts.References)
					fkFields = append(fkFields, fkEntry{string(field.Desc.Name()), refTable, refCol})
				}
			}

			// Audit columns — always present on every PII table.
			// deleted_at is nullable: NULL means the row is live; non-NULL means soft-deleted.
			// TZ-aware so timestamps remain correct across host/server tz drift.
			// created_by is populated from the actor on the request ctx at
			// INSERT (WithActor(ctx, actorID); else ''); preserved across
			// upserts. "Who updated this row" is captured per-change in
			// audit_pii_<name>s.changed_by — no row-level updated_by column
			// is stored.
			g.P("  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,")
			g.P("  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,")
			g.P("  deleted_at TIMESTAMP WITH TIME ZONE NULL,")
			g.P("  created_by TEXT NOT NULL DEFAULT '',")

			type constraint struct{ line string }
			var constraints []constraint
			if len(pkCols) > 0 {
				constraints = append(constraints, constraint{
					fmt.Sprintf("  PRIMARY KEY (%s)", strings.Join(pkCols, ", ")),
				})
			}
			for _, uf := range uniqueFields {
				constraints = append(constraints, constraint{fmt.Sprintf("  UNIQUE (%s)", uf)})
			}
			for _, fk := range fkFields {
				constraints = append(constraints, constraint{
					fmt.Sprintf("  FOREIGN KEY (%s) REFERENCES %s(%s)", fk.col, fk.refTable, fk.refCol),
				})
			}
			for i, c := range constraints {
				if i < len(constraints)-1 {
					g.P(c.line + ",")
				} else {
					g.P(c.line)
				}
			}
			g.P(");")
			g.P()

			// ── Audit Table + Trigger ─────────────────────────────────────────
			// audit_pii_<name>s captures the full OLD row (as JSONB) on every
			// UPDATE or DELETE against pii_<name>s. INSERTs aren't audited —
			// the chain table already records the newly-introduced values.
			//
			// changed_by reads from the `sdm.actor` Postgres session
			// variable. The generated Save / SaveAll methods set that variable
			// inside their transaction when the context carries a value via
			// WithActor(ctx, actorID). Changes made through other paths
			// (raw db.Exec, db.Delete outside a SaveAll transaction) record
			// '' for changed_by.
			//
			// ref_id is TEXT (cast from the PK via ::text) so the same audit
			// table works for both BIGINT and TEXT primary keys; composite PKs
			// are joined with ':' to mirror the chain compositeKey scheme.
			//
			// Entire block is gated on opts.CreateAuditTables.
			if opts.CreateAuditTables {
				auditTable := fmt.Sprintf("audit_pii_%ss", modelName)
				auditFn := fmt.Sprintf("audit_pii_%ss_log", modelName)
				auditTrigger := fmt.Sprintf("audit_pii_%ss_log_trigger", modelName)
				piiTable := fmt.Sprintf("pii_%ss", modelName)

				g.P("CREATE TABLE IF NOT EXISTS ", auditTable, " (")
				g.P("  id BIGSERIAL PRIMARY KEY,")
				g.P("  ref_id TEXT NOT NULL,")
				g.P("  last_value JSONB NOT NULL,")
				g.P("  change_type TEXT NOT NULL,")
				g.P("  changed_by TEXT NOT NULL DEFAULT '',")
				g.P("  changed_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP")
				g.P(");")
				g.P()

				// Compose the ref_id expression. Single-column PK is the
				// common case (cast to text). Composite PK is joined with
				// ':' to match chain compositeKey construction.
				var refIDExpr string
				switch len(pkCols) {
				case 0:
					// Should not happen for PII-backed messages (isSdmRecord
					// requires PK or chain_identifier_key, and chainOnly is
					// already false here).
					refIDExpr = "''"
				case 1:
					refIDExpr = fmt.Sprintf("OLD.%s::text", pkCols[0])
				default:
					parts := make([]string, len(pkCols))
					for i, c := range pkCols {
						parts[i] = fmt.Sprintf("OLD.%s::text", c)
					}
					refIDExpr = strings.Join(parts, " || ':' || ")
				}

				g.P("CREATE OR REPLACE FUNCTION ", auditFn, "()")
				g.P("RETURNS TRIGGER AS $$")
				g.P("BEGIN")
				g.P("  INSERT INTO ", auditTable, " (ref_id, last_value, change_type, changed_by)")
				g.P("  VALUES (")
				g.P("    ", refIDExpr, ",")
				g.P("    row_to_json(OLD)::jsonb,")
				g.P("    TG_OP,")
				g.P("    COALESCE(current_setting('sdm.actor', true), '')")
				g.P("  );")
				g.P("  RETURN NULL;")
				g.P("END;")
				g.P("$$ LANGUAGE plpgsql;")
				g.P()
				g.P("DROP TRIGGER IF EXISTS ", auditTrigger, " ON ", piiTable, ";")
				g.P("CREATE TRIGGER ", auditTrigger)
				g.P("AFTER UPDATE OR DELETE ON ", piiTable)
				g.P("FOR EACH ROW EXECUTE FUNCTION ", auditFn, "();")
				g.P()
			}
		}

		// ── Chain Table ───────────────────────────────────────────────────────
		// version is scoped to (key, field_name) — each new entry for a field of a
		// given record gets MAX(version)+1 for that group, set by the BEFORE INSERT
		// trigger below.
		g.P("CREATE TABLE IF NOT EXISTS chain_", modelName, "s (")
		g.P("  key TEXT NOT NULL,")
		g.P("  field_name TEXT NOT NULL,")
		g.P("  version BIGINT NOT NULL,")
		g.P("  tx_hash TEXT,")
		g.P("  field_value TEXT,")
		g.P("  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,")
		g.P("  created_by TEXT NOT NULL DEFAULT '',")
		if opts.ChainDrafts {
			// status defaults to CREATED so that:
			//   - migrations that just add the column to existing tables backfill
			//     to CREATED without an explicit UPDATE, preserving history
			//   - bulk loaders / external writers that omit the column produce
			//     committed rows (matches the safer interpretation)
			// DraftChain explicitly sets DRAFTED on the rows it appends.
			g.P("  status TEXT NOT NULL DEFAULT 'CREATED' CHECK (status IN ('DRAFTED', 'CREATED', 'DROPPED')),")
		}
		g.P("  PRIMARY KEY (key, field_name, version)")
		g.P(");")
		g.P()

		chainTable := fmt.Sprintf("chain_%ss", modelName)
		if opts.ChainDrafts {
			// At-most-one DRAFTED row per (key, field_name). DraftChain
			// returns ErrPendingDraftExists (sentinel) when this constraint
			// fires — caller's recourse is CommitChain or DropChain.
			draftIdx := fmt.Sprintf("chain_%ss_one_draft", modelName)
			g.P("CREATE UNIQUE INDEX IF NOT EXISTS ", draftIdx)
			g.P("  ON ", chainTable, " (key, field_name)")
			g.P("  WHERE status = 'DRAFTED';")
			g.P()

			// State-machine trigger. Legal transitions:
			//   DRAFTED → CREATED  (commit)
			//   DRAFTED → DROPPED  (drop)
			//   status unchanged   (other column updates are still allowed —
			//                       e.g. CommitChain also writes tx_hash)
			// Everything else raises an exception, defending the invariants
			// even against raw db.Exec callers that bypass the generated repo.
			guardFn := fmt.Sprintf("chain_%ss_status_guard", modelName)
			guardTrigger := fmt.Sprintf("chain_%ss_status_guard_trigger", modelName)
			g.P("CREATE OR REPLACE FUNCTION ", guardFn, "()")
			g.P("RETURNS TRIGGER AS $$")
			g.P("BEGIN")
			g.P("  IF OLD.status = NEW.status THEN")
			g.P("    RETURN NEW;")
			g.P("  ELSIF OLD.status = 'DRAFTED' AND NEW.status IN ('CREATED', 'DROPPED') THEN")
			g.P("    RETURN NEW;")
			g.P("  ELSE")
			g.P("    RAISE EXCEPTION 'illegal chain status transition: % -> %', OLD.status, NEW.status")
			g.P("      USING ERRCODE = '23514';")
			g.P("  END IF;")
			g.P("END;")
			g.P("$$ LANGUAGE plpgsql;")
			g.P()
			g.P("DROP TRIGGER IF EXISTS ", guardTrigger, " ON ", chainTable, ";")
			g.P("CREATE TRIGGER ", guardTrigger)
			g.P("BEFORE UPDATE ON ", chainTable)
			g.P("FOR EACH ROW EXECUTE FUNCTION ", guardFn, "();")
			g.P()
		}

		// ── Per-(key, field_name) version trigger ─────────────────────────────
		triggerFn := fmt.Sprintf("chain_%ss_set_version", modelName)
		triggerName := fmt.Sprintf("chain_%ss_set_version_trigger", modelName)
		g.P("CREATE OR REPLACE FUNCTION ", triggerFn, "()")
		g.P("RETURNS TRIGGER AS $$")
		g.P("BEGIN")
		g.P("  IF NEW.version IS NULL OR NEW.version = 0 THEN")
		g.P("    NEW.version := COALESCE(")
		g.P("      (SELECT MAX(version) FROM ", chainTable, " WHERE key = NEW.key AND field_name = NEW.field_name),")
		g.P("      0")
		g.P("    ) + 1;")
		g.P("  END IF;")
		g.P("  RETURN NEW;")
		g.P("END;")
		g.P("$$ LANGUAGE plpgsql;")
		g.P()
		g.P("DROP TRIGGER IF EXISTS ", triggerName, " ON ", chainTable, ";")
		g.P("CREATE TRIGGER ", triggerName)
		g.P("BEFORE INSERT ON ", chainTable)
		g.P("FOR EACH ROW EXECUTE FUNCTION ", triggerFn, "();")
		g.P()

		// ── View(s) ───────────────────────────────────────────────────────────
		// OFF mode: one view, no status filter (today's behavior).
		// ON mode: two views — `<name>s` (CREATED only) and
		// `<name>s_with_drafts` (latest non-DROPPED). Both expose
		// `has_pending_drafts` so callers can detect the half-state without
		// a second query.
		emitView := func(viewName, statusFilter string, exposeHasDrafts bool) {
			g.P("CREATE OR REPLACE VIEW ", viewName, " AS")
			if chainOnly {
				generateChainOnlyView(g, msg, modelName, statusFilter, exposeHasDrafts)
			} else {
				generatePiiBackedView(g, msg, modelName, statusFilter, exposeHasDrafts)
			}
			g.P()
		}
		if opts.ChainDrafts {
			emitView(modelName+"s", "status = 'CREATED'", true)
			emitView(modelName+"s_with_drafts", "status <> 'DROPPED'", true)
		} else {
			emitView(modelName+"s", "", false)
		}
	}
}

// generatePiiBackedView emits the SQL view for messages that have a PII table.
// The view anchors on pii_* and left-joins chain fields.
//
// statusFilter (without leading WHERE/AND) is appended to every chain-side
// subquery's WHERE clause. Empty string means no filter (OFF mode).
// exposeHasDrafts adds a has_pending_drafts column from an EXISTS subquery
// against chain_<name>s; used by both ON-mode views so callers can detect
// pending drafts regardless of which view they queried.
func generatePiiBackedView(g *protogen.GeneratedFile, msg *protogen.Message, modelName, statusFilter string, exposeHasDrafts bool) {
	selects := []string{}
	joins := []string{}

	chainKeyExpr := sqlCompositeKeyExpr(chainKeyCols(msg), "p")

	// Build the " AND <filter>" snippet for embedding after an existing
	// WHERE, and " WHERE <filter>" for subqueries that don't already have one.
	andFilter := ""
	whereFilter := ""
	if statusFilter != "" {
		andFilter = " AND " + statusFilter
		whereFilter = " WHERE " + statusFilter
	}

	for _, field := range msg.Fields {
		opts := getFieldOptions(field)
		colName := string(field.Desc.Name())

		if opts.PrimaryKey || opts.Pii || opts.QueryIndex || opts.References != "" {
			selects = append(selects, fmt.Sprintf("p.%s", colName))
		} else {
			alias := "c_" + colName
			joins = append(joins, fmt.Sprintf(
				"LEFT JOIN (SELECT DISTINCT ON (key, field_name) field_value, key FROM chain_%ss WHERE field_name='%s'%s ORDER BY key, field_name, version DESC) %s ON %s = %s.key",
				modelName, colName, andFilter, alias, chainKeyExpr, alias))
			valueExpr := fmt.Sprintf("%s.field_value", alias)
			switch {
			case isProtoTimestamp(field):
				valueExpr += "::timestamptz"
			case isJsonStored(field, opts):
				valueExpr += "::jsonb"
			}
			selects = append(selects, fmt.Sprintf("%s AS %s", valueExpr, colName))
		}

		if opts.Hashed {
			hashedName := "hashed_" + colName
			alias := "c_" + hashedName
			joins = append(joins, fmt.Sprintf(
				"LEFT JOIN (SELECT DISTINCT ON (key, field_name) field_value, key FROM chain_%ss WHERE field_name='%s'%s ORDER BY key, field_name, version DESC) %s ON %s = %s.key",
				modelName, hashedName, andFilter, alias, chainKeyExpr, alias))
			selects = append(selects, fmt.Sprintf("%s.field_value AS %s", alias, hashedName))
		}
	}

	// Always expose PII audit columns in the view. deleted_at is exposed raw
	// (nullable timestamptz); the view does not compute a boolean — GORM's
	// gorm.DeletedAt type on the View struct, plus an explicit
	// `WHERE deleted_at IS NULL` in read methods, handle the filtering.
	// Only created_by is surfaced; for "who last updated" callers query
	// audit_pii_<name>s directly (Repo.AuditLog).
	selects = append(selects, "p.created_at")
	selects = append(selects, "p.updated_at")
	selects = append(selects, "p.deleted_at")
	selects = append(selects, "p.created_by")

	// Latest tx_hash from the chain table for this record. When a status
	// filter is in effect, we only consider rows matching the filter so the
	// committed view's tx_hash reflects the latest committed write.
	joins = append(joins, fmt.Sprintf(
		"LEFT JOIN (SELECT DISTINCT ON (key) key, tx_hash FROM chain_%ss%s ORDER BY key, version DESC) c_tx ON %s = c_tx.key",
		modelName, whereFilter, chainKeyExpr))
	selects = append(selects, "c_tx.tx_hash")

	if exposeHasDrafts {
		// Indicates a record has at least one DRAFTED chain row regardless of
		// which view is being queried. Read in Go as View.HasPendingDrafts.
		selects = append(selects, fmt.Sprintf(
			"EXISTS (SELECT 1 FROM chain_%ss c WHERE c.key = %s AND c.status = 'DRAFTED') AS has_pending_drafts",
			modelName, chainKeyExpr))
	}

	g.P("  SELECT")
	g.P("    ", strings.Join(selects, ",\n    "))
	g.P("  FROM pii_", modelName, "s p")
	for _, join := range joins {
		g.P("  ", join)
	}
	g.P(";")
}

// generateChainOnlyView emits the SQL view for messages with no PII table.
// The anchor is SELECT DISTINCT key FROM chain_*, and every field (including
// the chain_identifier_key itself, returned as keys.key) is a left-joined
// subquery. References fields carry a SQL comment noting the intended FK since
// no database-level constraint is possible without a PII anchor table.
//
// statusFilter, when non-empty, narrows both the anchor (keys with any row
// matching the filter) and every chain-side subquery (latest row matching the
// filter). exposeHasDrafts adds a has_pending_drafts column.
func generateChainOnlyView(g *protogen.GeneratedFile, msg *protogen.Message, modelName, statusFilter string, exposeHasDrafts bool) {
	selects := []string{}
	joins := []string{}

	andFilter := ""
	whereFilter := ""
	if statusFilter != "" {
		andFilter = " AND " + statusFilter
		whereFilter = " WHERE " + statusFilter
	}

	for _, field := range msg.Fields {
		opts := getFieldOptions(field)
		colName := string(field.Desc.Name())

		if opts.ChainIdentifierKey {
			// The key field maps directly from the anchor — no subquery needed.
			selects = append(selects, fmt.Sprintf("keys.key AS %s", colName))
			continue
		}

		alias := "c_" + colName
		joins = append(joins, fmt.Sprintf(
			"LEFT JOIN (SELECT DISTINCT ON (key) key, field_value FROM chain_%ss WHERE field_name = '%s'%s ORDER BY key, version DESC) %s ON keys.key = %s.key",
			modelName, colName, andFilter, alias, alias))

		valueExpr := fmt.Sprintf("%s.field_value", alias)
		switch {
		case isProtoTimestamp(field):
			valueExpr += "::timestamptz"
		case isJsonStored(field, opts):
			valueExpr += "::jsonb"
		}

		comment := ""
		if opts.References != "" {
			comment = fmt.Sprintf(" -- references %s", opts.References)
		}
		selects = append(selects, fmt.Sprintf("%s AS %s%s", valueExpr, colName, comment))

		if opts.Hashed {
			hashedName := "hashed_" + colName
			hashedAlias := "c_" + hashedName
			joins = append(joins, fmt.Sprintf(
				"LEFT JOIN (SELECT DISTINCT ON (key) key, field_value FROM chain_%ss WHERE field_name = '%s'%s ORDER BY key, version DESC) %s ON keys.key = %s.key",
				modelName, hashedName, andFilter, hashedAlias, hashedAlias))
			selects = append(selects, fmt.Sprintf("%s.field_value AS %s", hashedAlias, hashedName))
		}
	}

	// tx_hash — latest chain entry's hash for any field. Narrowed by the
	// status filter so the committed view's tx_hash reflects the latest
	// committed write.
	joins = append(joins, fmt.Sprintf(
		"LEFT JOIN (SELECT DISTINCT ON (key) key, tx_hash FROM chain_%ss%s ORDER BY key, version DESC) c_tx ON keys.key = c_tx.key",
		modelName, whereFilter))
	selects = append(selects, "c_tx.tx_hash")

	if exposeHasDrafts {
		selects = append(selects, fmt.Sprintf(
			"EXISTS (SELECT 1 FROM chain_%ss c WHERE c.key = keys.key AND c.status = 'DRAFTED') AS has_pending_drafts",
			modelName))
	}

	g.P("  SELECT")
	g.P("    ", strings.Join(selects, ",\n    "))
	g.P("  FROM (SELECT DISTINCT key FROM chain_", modelName, "s", whereFilter, ") keys")
	for _, join := range joins {
		g.P("  ", join)
	}
	g.P(";")
}

// parseReference splits a "MessageName.field_name" references annotation into
// the PII table name and column name used in SQL FK constraints.
func parseReference(ref string) (table, column string) {
	parts := strings.SplitN(ref, ".", 2)
	if len(parts) != 2 {
		return "", ""
	}
	return "pii_" + strings.ToLower(parts[0]) + "s", parts[1]
}
