// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sdmprotos/annotations.proto

package sdmprotos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_sdmprotos_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50000,
		Name:          "sdm.primary_key",
		Tag:           "varint,50000,opt,name=primary_key",
		Filename:      "sdmprotos/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50001,
		Name:          "sdm.chain_identifier_key",
		Tag:           "varint,50001,opt,name=chain_identifier_key",
		Filename:      "sdmprotos/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50002,
		Name:          "sdm.pii",
		Tag:           "varint,50002,opt,name=pii",
		Filename:      "sdmprotos/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50003,
		Name:          "sdm.query_index",
		Tag:           "varint,50003,opt,name=query_index",
		Filename:      "sdmprotos/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50004,
		Name:          "sdm.hashed",
		Tag:           "varint,50004,opt,name=hashed",
		Filename:      "sdmprotos/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50005,
		Name:          "sdm.unique",
		Tag:           "varint,50005,opt,name=unique",
		Filename:      "sdmprotos/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50006,
		Name:          "sdm.references",
		Tag:           "bytes,50006,opt,name=references",
		Filename:      "sdmprotos/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50007,
		Name:          "sdm.auto_increment",
		Tag:           "varint,50007,opt,name=auto_increment",
		Filename:      "sdmprotos/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50008,
		Name:          "sdm.json",
		Tag:           "varint,50008,opt,name=json",
		Filename:      "sdmprotos/annotations.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional bool primary_key = 50000;
	E_PrimaryKey = &file_sdmprotos_annotations_proto_extTypes[0]
	// optional bool chain_identifier_key = 50001;
	E_ChainIdentifierKey = &file_sdmprotos_annotations_proto_extTypes[1]
	// optional bool pii = 50002;
	E_Pii = &file_sdmprotos_annotations_proto_extTypes[2]
	// optional bool query_index = 50003;
	E_QueryIndex = &file_sdmprotos_annotations_proto_extTypes[3]
	// optional bool hashed = 50004;
	E_Hashed = &file_sdmprotos_annotations_proto_extTypes[4]
	// optional bool unique = 50005;
	E_Unique = &file_sdmprotos_annotations_proto_extTypes[5]
	// optional string references = 50006;
	E_References = &file_sdmprotos_annotations_proto_extTypes[6] // FK annotation, format "MessageName.field_name" e.g. "Organisation.id"
	// optional bool auto_increment = 50007;
	E_AutoIncrement = &file_sdmprotos_annotations_proto_extTypes[7] // generates BIGSERIAL in SQL and autoIncrement GORM tag
	// optional bool json = 50008;
	E_Json = &file_sdmprotos_annotations_proto_extTypes[8] // string field stored as Postgres JSONB and Go datatypes.JSON
)

var File_sdmprotos_annotations_proto protoreflect.FileDescriptor

const file_sdmprotos_annotations_proto_rawDesc = "" +
	"\n" +
	"\x1bsdmprotos/annotations.proto\x12\x03sdm\x1a google/protobuf/descriptor.proto:@\n" +
	"\vprimary_key\x12\x1d.google.protobuf.FieldOptions\x18І\x03 \x01(\bR\n" +
	"primaryKey:Q\n" +
	"\x14chain_identifier_key\x12\x1d.google.protobuf.FieldOptions\x18ц\x03 \x01(\bR\x12chainIdentifierKey:1\n" +
	"\x03pii\x12\x1d.google.protobuf.FieldOptions\x18҆\x03 \x01(\bR\x03pii:@\n" +
	"\vquery_index\x12\x1d.google.protobuf.FieldOptions\x18ӆ\x03 \x01(\bR\n" +
	"queryIndex:7\n" +
	"\x06hashed\x12\x1d.google.protobuf.FieldOptions\x18Ԇ\x03 \x01(\bR\x06hashed:7\n" +
	"\x06unique\x12\x1d.google.protobuf.FieldOptions\x18Ն\x03 \x01(\bR\x06unique:?\n" +
	"\n" +
	"references\x12\x1d.google.protobuf.FieldOptions\x18ֆ\x03 \x01(\tR\n" +
	"references:F\n" +
	"\x0eauto_increment\x12\x1d.google.protobuf.FieldOptions\x18׆\x03 \x01(\bR\rautoIncrement:3\n" +
	"\x04json\x12\x1d.google.protobuf.FieldOptions\x18؆\x03 \x01(\bR\x04jsonB%Z#github.com/kapow-tech/sdm/sdmprotosb\x06proto3"

var file_sdmprotos_annotations_proto_goTypes = []any{
	(*descriptorpb.FieldOptions)(nil), // 0: google.protobuf.FieldOptions
}
var file_sdmprotos_annotations_proto_depIdxs = []int32{
	0, // 0: sdm.primary_key:extendee -> google.protobuf.FieldOptions
	0, // 1: sdm.chain_identifier_key:extendee -> google.protobuf.FieldOptions
	0, // 2: sdm.pii:extendee -> google.protobuf.FieldOptions
	0, // 3: sdm.query_index:extendee -> google.protobuf.FieldOptions
	0, // 4: sdm.hashed:extendee -> google.protobuf.FieldOptions
	0, // 5: sdm.unique:extendee -> google.protobuf.FieldOptions
	0, // 6: sdm.references:extendee -> google.protobuf.FieldOptions
	0, // 7: sdm.auto_increment:extendee -> google.protobuf.FieldOptions
	0, // 8: sdm.json:extendee -> google.protobuf.FieldOptions
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	0, // [0:9] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sdmprotos_annotations_proto_init() }
func file_sdmprotos_annotations_proto_init() {
	if File_sdmprotos_annotations_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sdmprotos_annotations_proto_rawDesc), len(file_sdmprotos_annotations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 9,
			NumServices:   0,
		},
		GoTypes:           file_sdmprotos_annotations_proto_goTypes,
		DependencyIndexes: file_sdmprotos_annotations_proto_depIdxs,
		ExtensionInfos:    file_sdmprotos_annotations_proto_extTypes,
	}.Build()
	File_sdmprotos_annotations_proto = out.File
	file_sdmprotos_annotations_proto_goTypes = nil
	file_sdmprotos_annotations_proto_depIdxs = nil
}
